### ISSUE TITLE
Update screenshots for redeploy

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-force-lab#100]
This sim will need to be redeployed in conjunction with the publication of its ISLC siblings. Several changes have been made so the [current screenshots](https://github.com/phetsims/gravity-force-lab/tree/master/assets) will need to be retaken from the latest version of the sim. 

With the addition of the scientific notation feature, I would recommend that we add an additional alternate screenshot, similar to this:
![image](https://user-images.githubusercontent.com/8419308/42844640-dbb0e292-89d0-11e8-93df-4d07ea8d800a.png)

**Comment by zepumph** [comment]
Over to @KatieWoe, I'll leave it up to her when to do this during the RC process.

**Comment by zepumph** [comment]
@arouinfar, I think we are ready for this, but I thought we should check with you. Does this sim seem to be in its final visual state? Ready to pass them over to @KatieWoe to do screenshots?

**Comment by zepumph** [comment]
Note: nothing came out of rc.1 that I would expect to change the visuals of the sim.

**Comment by arouinfar** [comment]
Yes, we're ready to finalize the screenshots. @KatieWoe please retake the current screenshots plus the alternate proposed in https://github.com/phetsims/gravity-force-lab/issues/100#issue-342080345.

**Comment by KatieWoe** [comment]
Above commits should do it.

**Comment by zepumph** [comment]
I'll make sure they end up in the RC.

**Comment by arouinfar** [comment]
Looks good @KatieWoe, thanks!

**Comment by KatieWoe** [comment]
This was done in rc.1. This can be closed. Let me know if something else is needed.
