### ISSUE TITLE
Focus order incorrect

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#103]
Just starting A11y work on this sim and noticed that the current focus order is a little wonky. 
Focus order will eventually be:

1. m1, blue sphere position, slider
2. m2, Red Sphere position, slider
3. m1 mass, slider
4. m2 mass, slider 
5. Ruler, move in 4 directions
6. Constant Size, checkbox, not checked
7. Force Values, checkbox, checked
8. Scientific Notation, checkbox, not checked
9. Reset All, button

**Comment by emily-phet** [comment]
As part of full description work, focus order will be finalized. Closing this issue, as it's part of other work (the only remaining question - I believe - being where to put the Ruler in the focus order).
