### ISSUE TITLE
Constrain movement of ruler?

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#104]
I am just looking at the accessibility of this sim, and I would like to ask if we could consider putting useful constraints on the movement of the ruler to simplify description. For example, preventing it from going off screen, or under the controls?

Question is not high priority, but just want to put it out there.

**Comment by arouinfar** [comment]
@terracoda there are already limits on how far the ruler can be moved. Are you proposing tighter restrictions?

![gfl_ruler](https://user-images.githubusercontent.com/8419308/45178929-54482f00-b1d4-11e8-86a0-d84c4da4974a.gif)

Allowing for the ruler to go a bit off the left/right side of the screen is helpful for these sorts of situations:
![image](https://user-images.githubusercontent.com/8419308/45178997-7fcb1980-b1d4-11e8-9489-ffead52c9ca8.png)

The ruler probably doesn't need to go behind the panels, but it is full retrievable in this state. Does it propose a challenge for a11y? 

![image](https://user-images.githubusercontent.com/8419308/45179076-aee18b00-b1d4-11e8-8f21-179f4d25d437.png)

We could be more restrictive on its y-coordinate so it doesn't go below the top of the panels.
![image](https://user-images.githubusercontent.com/8419308/45179178-0122ac00-b1d5-11e8-9815-00c3532c265f.png)

**Comment by terracoda** [comment]
I was thinking of tighter constraints, like not off the screen to the left or right, maybe even not beyond the edge of the robots, and not below the panels.

It may not be an issue for a11y, but it might simplify the movement of the ruler. 

I would think that keeping the ruler above the panels would make it easier to grab for students with upper body dexterity issues, so restriction in the y-coordinates could be beneficial there.

**Comment by terracoda** [comment]
It is not priority at the moment. Maybe we should return to this once I am working on the ruler alerts.

**Comment by arouinfar** [comment]
Thanks @terracoda! Since I've got GFL on my mind, I'll go ahead and add my thoughts here, but I'm always happy to pick this discussion back up later.

I think it's helpful to allow for some portion of the ruler to go off the left/right side. That would give users a bit more freedom to line up the 0 or 10 tick mark with one of the masses.

As for vertical movement, I think we can limit the ruler to the region above the panels. We'll want to give enough freedom to students to move the ruler out of the way.

For keyboard users, it may be useful to have some sort of shortcut keys (like the jump keys for the balloon in BASE) to quickly align the ruler. One potentially useful shortcut would be to align mass 1 with the 0-mark on the ruler. This would currently work when mass 1 on the far left side of the screen, but the current ruler bounds wouldn't allow this for when mass 1 is on the far right side of the screen.
![image](https://user-images.githubusercontent.com/8419308/45180341-5ca26900-b1d8-11e8-8e26-e59b76953309.png)
![image](https://user-images.githubusercontent.com/8419308/45180388-7cd22800-b1d8-11e8-826a-fd4589366962.png)

**Comment by terracoda** [comment]
@arouinfar, that's a very good point. We definitely would not want to constrain the end of the rule, but perhaps rather the zero mark if we constrain the left-right movement any further.

Thanks for these thoughts. They are helpful.

**Comment by terracoda** [comment]
I am marking this _onhold_ until I am directly working on the ruler.

**Comment by terracoda** [comment]
This issue is related to issue #138 
When the new Keyboard Shortcuts are implemented the constraints on the ruler's movement will need updating.

**Comment by terracoda** [comment]
@zepumph, we can discuss this issue when it comes time to work on #138.

**Comment by zepumph** [comment]
Pinging this issue again. It seems like we are moving forward with the full range of the ruler as movement bounds. Should we re-evaluate that, close this issue, or do something else?

**Comment by zepumph** [comment]
Over in https://github.com/phetsims/gravity-force-lab/issues/195, our life would be easier if you couldn't move the ruler to be fully underneath the mass controls. Does it seem reasonable to change the drag bounds for the ruler to be bottom bounded just above the controls, something like the picture below. For a solution for #195 we would just need to make sure that the center point of the ruler could never get behind the control panels. 

![image](https://user-images.githubusercontent.com/6856943/68617364-98d3f800-0473-11ea-8f3d-88a85db11e04.png)

**Comment by arouinfar** [comment]
@zepumph I'm a bit out of the loop on the latest decisions for this sim. If the current spec is allow the ruler to have full range, this issue is likely moot, but it would be good for @terracoda to confirm.

> our life would be easier if you couldn't move the ruler to be fully underneath the mass controls. Does it seem reasonable to change the drag bounds for the ruler to be bottom bounded just above the controls, something like the picture below. 

That sounds reasonable to me @zepumph.

**Comment by terracoda** [comment]
@arouinfar, on a11y mobile it is very difficult to grab the ruler when it ends up behind the masses. It serves no purpose for the ruler to go there, so I think it is fine to restrict the movement, so it is always easy to grab the ruler on mobile a11y.

For accessibility, the ruler is totally optional, but users can still use it.

**Comment by zepumph** [comment]
This was implemented above. Please review in GFL and CL. Assigning to both designers.

**Comment by arouinfar** [comment]
@zepumph the ruler's stopping point behind the mass/charge controls is looking good. This issue seems safe to close, but not sure, so back to @zepumph

**Comment by zepumph** [comment]
Great thanks!
