### ISSUE TITLE
Mass Sliders not fully working with keyboard

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#105]
I'm just getting started with alerts for this, and noticed that keyboard interactions have been implemented which is awesome.

However, I noticed that while the Sphere position sliders seem to work fine with the arrow keys, the Mass sliders do not.

I tried both Safari and Firefox on MacOS 10.13.6. 

The slider seems to get stuck on 500/549 when using just the arrow keys. The other key interactions work fine: Shift plus Left/Right Arrow, Pg Up, Pg Down, Home and End.

**Comment by terracoda** [comment]
Perhaps recent changes to accessible slider have had an impact on these sliders?

**Comment by terracoda** [comment]
@jessegreenberg, @zepumph tagging you both, so you know about this issue. This is not an immediate priority as far as I am concerned. This can likely wait until the full PDOM for this sim is implemented soon.

**Comment by terracoda** [comment]
Another issue is that I can't decrease slider value with Left Arrow key. I can only move Right Arrow key to 500, then I get stuck in both directions.

**Comment by jessegreenberg** [comment]
It looks like these are navigable because AccessibleSlider is mixed into ISLCObjectNode, but the default step size produced non integer values, and the sim wasn't having it. @terracoda can you please see if this is fixed in master?

**Comment by terracoda** [comment]
Looks like it is fixed in master. Thanks @jessegreenberg.
