### ISSUE TITLE
Concepts to communicate with Mass sliders

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#106]
Tackling mass alerts first as it seems easier than proximity alerts.

From my perspective I think we need to communicate:
- Size (or density) of mass
- Forces get stronger as mass of sphere increases in size or density
- Force vectors get bigger as mass of sphere increases in size or density (but, maybe no direction in alert?)

while adjusting with Mass.

**Questions, do we also need to provide:**
- Size (or density) of the other mass in some way during interaction?
- Direction of the vector? It is prominent in the PDOM.

Here's an example of Mass 1, slider with all of above but direction. I provide some size information on focus and then force information in the alert. I am wondering if this combined approach would work, and also wondering if we can drop any of the details.

**On focus:** 
- “Mass 1, slider. {{50}} kilograms{{, very small}}, {{somewhat smaller than}} mass {{2}}”

**Default increase (50 kg)** 
- {{100}} kilograms, forces {{a little stronger}} at {{0.000 000 083 423}} Newtons, force vectors {{very small}}

**Example decrease (50 kg):** 
- {{1}} kilograms, forces {{now very weak}} at {{0.000 000 000 834 Newtons}}, force vectors {{tiny}}

@emily-phet, any thoughts?

**Comment by emily-phet** [comment]
@terracoda 

I think this looks great! I don't think we need to mention the other mass explicitly, or direction of vector. I think people will need to occasionally explore the PDOM to get individual descriptions of the representations for each mass, and that's where they can piece together that the forces are pointed towards each other.

**Comment by terracoda** [comment]
Perfect, that's what I hope you were going to say, as that is what I was thinking as well.

**Comment by terracoda** [comment]
I'll go ahead with this pattern and removing a couple of strings:
**On focus:**
    “Mass 1, slider. {{50}} kilograms{{, very small}}. [[Removing comparative size phrase]]”

**Default increase (50 kg)**
    {{100}} kilograms, forces {{a little stronger}} at {{0.000 000 083 423}} Newtons, force vectors {{very small}}

**Default decrease (50 kg):**
    {{1}} kilograms, forces {{now very weak}} at {{0.000 000 000 834 Newtons}}, force vectors {{tiny}}

**Comment by terracoda** [comment]
@emily-phet, I have chopped the next iteration of the increase/decrease alert attempting to make the forces and the vectors seem less like two separate things.

**Mass alert version 3 - expected read out (increase)**
- {{100}} kilograms. As mass {{grows}} vectors {{grow}}, forces {{now {{0.083 423}} micronewtons}}.

**Mass alert version 3 - expected read out (decrease)**
 - {{1}} kilogram. As mass {{gets smaller}} vectors {{get smaller}}, forces {{now {{0.083 423}} micronewtons}}.

**Alternative phrasing**
- As mass {{grows}}, vectors {{grow}}, forces {{now {{force value}} micronewtons}}.
- As mass {{gets bigger}}, vectors {{get bigger}}, forces {{now {{force value}} micronewtons}}.

@emily-phet, what do you think? Shall we implement these in our first go. Keep in mind, the Focus alert comes before the actual increase or decrease.

**Focus alert for mass slider** 
- Mass 1, slider. “{{50}} kilograms, {{very small}}, {{slightly smaller than}} m{{2}}.”

**Comment by emily-phet** [comment]
@terracoda Love it! I think this latest change helps a lot!

**Comment by terracoda** [comment]
@terracoda to update design document to have just the above increase/decrease Mass Alert.

**Comment by terracoda** [comment]
**I'm going to go with "gets bigger" and "gets smaller"**
- {{100}} kilograms. As mass {{gets bigger}} vectors {{get bigger}}, forces {{now {{0.083 423}} micronewtons}}.
- {{1}} kilogram. As mass {{gets smaller}} vectors {{get smaller}}, forces {{now {{0.083 423}} micronewtons}}.

I've updated the design doc, so I will close this issue.
