### ISSUE TITLE
Mass Sphere Position Sliders - best structure?

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#111]
@mbarlow12  you have implemented the Mass Sphere Position sliders in a list structure. Any particular reason why? 

Ideally, I'd like the position sliders to be communicated as one slider with two thumbs and while this is difficult (possibly impossible from an a11y perspective), I am not sure a list structure is the best choice.

Marking this for discussion at today's design meeting.

**Comment by mbarlow12** [comment]
@terracoda It was ambiguous from the design doc as what sort of markup should wrap the sliders. 

As to a slider with 2 thumbs, the `range` input only accepts a single input, so we'll have to use 2 distinct sliders but there may be some possibility of of using aria attributes to communicate to the user that they're linked.

For now, I'll remove the list and simply have the position sliders in a div.

**Comment by mbarlow12** [comment]
List removed in https://github.com/phetsims/gravity-force-lab/commit/6e88d2ddc47b304c2ea99bfe29668eec43faacf8 and https://github.com/phetsims/inverse-square-law-common/commit/3bbcca0589c76275d97ef20a38386540db1d829f. Made an error in the commit messages.

**Comment by terracoda** [comment]
@mbarlow12, I verified the change, so closing for now.
