### ISSUE TITLE
Small rounding difference in PDOM for newtons/micronewtons

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#113]
Apologies if I have mentioned rounding differences somewhere else. I do not see an issue for it.

@mbarlow12 is it possible to round the micronewtons in the PDOM so they have the same digits as the newtons in the visual sim?

I am tagging and assigning to @arouinfar to see if this is a significant difference or not.

See the small difference here in the A11y View:
<img width="919" alt="rounding-question" src="https://user-images.githubusercontent.com/1902116/48064355-d7cbcf80-e1c7-11e8-802e-d5272eb8014f.png">

**Comment by terracoda** [comment]
Or perhaps, we need one less decimal place for micronewtons. 
@arouinfar, can you verify the number of needed decimal places for micronewtons?

**Comment by emily-phet** [comment]
@terracoda I think the number of significant figures in the PDOM just needs to match the number of decimal places shown in the visuals. If the same number of significant figures is shown, the rounding will take care of itself (note, this is not the same as just 'chopping off' the extra decimal places in the PDOM - as this would not round them final digit).

**Comment by terracoda** [comment]
@emily-phet, understood, but right now there are 7 decimal places in PDOM, and in the visual sim, it looks like (to me anyways) that there are 6 significant figures (041 712).

I was wondering if the micronewtons in the PDOM need to be rounded to 0.041712 from 0.0417115?

**Comment by emily-phet** [comment]
@terracoda agreed - please have the number of decimals place in the PDOM match that in the visuals. This will mean they need to have the same number of 'significant figures', so that the final number is rounded correctly and the PDOM and visuals match exactly.

**Comment by arouinfar** [comment]
@terracoda I agree that the number of decimal places in the PDOM should match the visuals, so I'll reassign to @mbarlow12.

**Comment by mbarlow12** [comment]
Forgot to link the commits that address this issue:
https://github.com/phetsims/inverse-square-law-common/commit/47c7cf8c0d76a020eaca59a721f59cdd2a27b895
and
https://github.com/phetsims/gravity-force-lab/commit/8f6edc2844782a5ee3c9b63c4e70b6945936ebda

**Comment by terracoda** [comment]
Sounds great @mbarlow12! We 6 significant figures in our Parallel Experiences now. Closing this issue.
