### ISSUE TITLE
In non-visual expience, ok to switch between micronewtons and newtons?

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#114]
In yesterday's A11y design meeting for this sim, we were iterating on the alerts for when the Forces Values and Scientific Notation checkboxes become checked and unchecked.

We already agreed that micronewtons is indeed a useful format in "regular view" for the non-visual experience as it prevents a bunch of zero-filled decimal places from being read out.

I want to double-check that it is ok to be switching between micronewtons and newtons in the non-visual experience.

**For example:**
- when Scientific Notation is not checked, students using a screen reader will hear Force Values in micronewtons, which is different than what is on the screen, but with the same significant figures.
- when Scientific Notation is checked, students using a screen reader will hear Force Values in scientific notation, and in Newtons which is what is visually displayed on the sim's screen.

My question to you @arouinfar is:
Should the scientific notation also be read out in micronewtons in the non-visual experience, or should we keep going with this micronewtons/newtons switching until we know this is a problem for students.

**Comment by arouinfar** [comment]
Great question @terracoda. While I think micronewtons is handy for concise descriptions in standard notation, it would be a bit confusing in scientific notation since there would be an extra 10^-6 implied. For clarity, and in keeping with convention, I would prefer that scientific notation is described in Newtons, not micronewtons.

**Comment by terracoda** [comment]
@arouinfar thanks, closing.
