### ISSUE TITLE
Adjust UI alert text for Force Values and Scientific Notation checkboxes

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#115]
Once a decision is made in #114, please update alert text strings to match the updated alerts in the design document in Section [Simple Interactive Alerts for UI Options](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.mp3sseh3ze8h)

The constant size checkbox alerts are working great. Just the other 2 need adjusting.

Interactive Sim Controls | Alert for successful interaction | Notes on interaction
-- | -- | --
Force Values, checkbox | Values in micronewtons. | When Scientific Notation is unchecked, otherwise, “Forces in scientific notation.”
Force Values, checkbox not checked | Force values hidden. |  
Scientific Notation, checkbox | Values in newtons with scientific notation. | When Force Values is checked. Or when Force Values is rechecked and Scientific Notation is already checked.
Scientific Notation, checkbox not checked | Same as Force Values alert, “Values in micronewtons.” |  

Apologies, @mbarlow12 if this update is already in your todo list.

**Edit:** Adding reference to https://github.com/phetsims/gravity-force-lab/issues/109#issuecomment-436557753

**Comment by terracoda** [comment]
@mbarlow12, in #114 @arouinfar confirmed that it is best to describe scientific notation in newtons, so we will stick with switching between micronewtons to newtons when scientific notation checkbox is checked.

**Comment by mbarlow12** [comment]
I must have had some clairvoyance yesterday, as the commits below handled the readout with the micronewtons/newtons switch.
https://github.com/phetsims/inverse-square-law-common/commit/b25ac395bb5261471e4d71a66505c7618a7dab68
https://github.com/phetsims/gravity-force-lab/commit/87d995e8c4bbca5bf08bcd62fabe49c96b8fbd7c
https://github.com/phetsims/inverse-square-law-common/commit/47c7cf8c0d76a020eaca59a721f59cdd2a27b895

Only adjustment left is to match the significant digits in the mantissa.

**Comment by terracoda** [comment]
@mbarlow12, everything sounds great.
I found an issue that position values under 1.2 or 1.3 meters are not rounding to a single decimal point.

I'll close this issue and open a new one for the minor position value change.
