### ISSUE TITLE
Change qualitative description for "a tiny bit" of force/pulling

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#116]
As discussed in Nov 6 design meeting and based on user feedback, we need to make the difference between "a tiny bit" and "a little" more clear.

Please change "a tiny bit" to "very little".

The slightly updated qualitative scale looks like this in section titled [Effort of the robots](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#):

Description of Force Vectors | Range in Newtons | Effort of Robots
-- | -- | --
tiny | 0.000 289 - 0.041 712 | pulling very little
very small | 0.041 713 - 0.074 154 | pulling a little
small | 0.074 155 - 0.260 697 | pulling lightly
medium size | 0.260 698 - 0.789 804 | pulling gently
large | 0.789 805 - 1.564 181 | pulling moderately
very large | 1.564 182 - 2.309 287 | pulling hard
huge | 2.309 288 - 11.586 528 | pulling very hard

@mbarlow12, I think the **"a tiny bit"** string is only used when describing the pulling effort of the robots in the state-of-the-sim list, e.g., "Robots {{pull a tiny bit}} keeping spheres in place."

**Edit:** Adding reference to https://github.com/phetsims/gravity-force-lab/issues/109#issuecomment-436557753

**Comment by mbarlow12** [comment]
Updated in above commit.

**Comment by terracoda** [comment]
Thanks @mbarlow12, sounds great! I'll close this issue.
