### ISSUE TITLE
Make help text for Mass sliders dynamic

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#123]
To help with the concept of density, please change the help text paragraph for the Mass sliders controls when the Constant Size checkbox is checked.

- When Constant Size checkbox is not checked:
  - Change mass of spheres in kilograms. 
- When Constant Size checkbox is checked:
  - Change density of spheres in kilograms. 

Please see [Mass Controls](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.ett50jitz9gs) section of the design document

**Comment by mbarlow12** [comment]
@terracoda both GFL and GFL:B have this change in master. Please review and comment/close. Thanks!

**Comment by terracoda** [comment]
@mbarlow12, this is good in Gravity Force Lab. I made an issue in GFLB because I think it is reversed in that sim.

**Comment by terracoda** [comment]
I think we can close this issue for GFL, regular.
