### ISSUE TITLE
Position slider information ready for implementation

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#124]
@mbarlow12, @emily-phet and I discussed changes to how we could provide position information.

Please see the design document for details. An example is provided here:

[https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.ostp3ek0rn9e](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.ostp3ek0rn9e)

I'll be adding more examples, but would love to know if this is clear.

**Comment by mbarlow12** [comment]
@terracoda the `aria-valuetext` has been implemented and should be functioning correctly in both GFL & GFLB. Let me know if we should tweak the region boundaries. The aria-live text will be forthcoming.

**Comment by terracoda** [comment]
@mbarlow12, this sounds great! It would be great to save this work for comparison with using "distance in meters".

@emily-phet and I discussed a new approach yesterday that still relies on aria-valuetext, but with different parameters. Using actual distance in meters.

Please see the updated focus examples and the updated 8-step interaction. 

The  strings for vector alerts and force magnitude are still the same, and should be nicely handled with aria live region alert

We can discuss at today's meeting.

**Comment by terracoda** [comment]
@mbarlow12, oh, I missed that the object string containing mm1 or m2 is missing from the implementation. For example,

- closer to m2
- farther from m2
- closer to m2

We'll need that string in there, too.

**Comment by terracoda** [comment]
This is sounding good @mbarlow12. Please asign to me when you want me to review it :-)

**Comment by terracoda** [comment]
@mbarlow12, I think we can leave as-is, but it is possible that having the alert change on the step that actually reaches the last stop could be potentially useful in this case.

**Comment by mbarlow12** [comment]
New dev versions for GFL:
https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-dev.10/phet/gravity-force-lab_en_phet.html?a11y
https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-dev.10/phet/gravity-force-lab_a11y_view.html

Note: I somehow missed adding 'kilograms' to the interactive alerts for changing mass. Will be fixed in the next update.

**Comment by mbarlow12** [comment]
Mass alerts are a little messy in general—on my list to fix.

**Comment by terracoda** [comment]
Re-assigned to myself to review.

**Comment by terracoda** [comment]
@zepumph, I have done a very careful review of all position/distance `aria-valuetext` (and alerts).

Much of the implementation is working, but of course I found some issues and have some questions.

I have updated the tables in the design document (green cells mark things working well and red cells and red text identify issues that I found & iterations that I would like to see if possible).

I am marking this for discussion for tomorrow's meeting before I create issues.

Here's a link to the [Position/distance section](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.qvqurriseltj) in the  design doc

**Comment by zepumph** [comment]
2 potential improvements:

1. On focus, when "closest to" we don't have a "meter mark" alert like we do for (a) normal focus, and (b) focus alerts at the edge.
2. when moving a slider to the edge, we don't have an "at left edge" alert , we should.


See design doc table for best details before implementing.

**Comment by terracoda** [comment]
@zepumph, I would say "meter mark" _string_ and "at left edge" _string_ rather than _alert_. Just a reminder, these strings are found in `aria-valuetext`. I think you know this, but just being clear as you are relatively new to the repo.

**Comment by terracoda** [comment]
@zepumph, I just had a listen. It is sounding great! 

I just added a new note in the design doc (assigned to you).

As I said, the dynamic `aria-valuetext` is sounding great! I am wondering if you might be able to add the mass sphere name "to m1" or "to m2" in this case where the user tries to go beyond the last available position?

In the opposite case, when the focused farthest sphere is "Farthest from" the other sphere (i.e. at the edge and obviously not touching) the string would be "Farthest from m1" or "Farthest from m2".

@zepumph, if this request will slow you down, just leave it for now. You are not yet finished and ready for iterations.


I think the name of the sphere might be good for emphasis.

This change might have the benefit of being more like the "Closer to" string, as well, since the word "to" is included.

**Comment by zepumph** [comment]
>1. On focus, when "closest to" we don't have a "meter mark" alert like we do for (a) normal focus, and (b) focus alerts at the edge.

I implemented this so that all three strings use the same code to fill the position mark in. When implementing this, note that I didn't add this to the "Farthest" string because that is added when moving the masses, not on focus. 

>2. when moving a slider to the edge, we don't have an "at left edge" alert , we should.

I gave that a go too, what do you think?


Please review.

**Comment by zepumph** [comment]
From meeting today:

> 2. when moving a slider to the edge, we don't have an "at left edge" alert , we should.

* Instead of having this be an alert, we want it to replace the "farthest from" part of the the aria valuetext, so in REGULAR it would look like: `At left edge, {{4 meters}} away`.  
* In BASICS if distance checkbox isn't checked, then omit the second piece in exchange for qualitative alerts in the.
* In BASICS there is but where "closest to" is actually "farthest from"  
* BASICS focus alert for masses are also messed up, when "closest to" says "at right edge" instead.

**Comment by zepumph** [comment]
The above commit (hopefully) handles:

> Instead of having this be an alert, we want it to replace the "farthest from" part of the the aria valuetext, so in REGULAR it would look like: `At left edge, {{4 meters}} away`.  This text is for when moving a mass and you get to an edge. No need to change the focus text when already on the edge (we like "meter mark, left edge, distance" for that.

**Comment by zepumph** [comment]
The above commit was a bug found in BASICS where the relative distance strings were buggy because the distance was being converted from kilometers to meters when it was already in meters.

**Comment by terracoda** [comment]
@zepumph,I finally finished updating the tables in the design docs for both GFL Regular and Basics.

I haven't reviewed your last commit, but I will now.

GFL Basic's design doc has a good summary of the position/distance interaction from focus to hitting and edge. I think I simplified things.

Here's a link to the relevant section in REGULAR's design doc, [Complex Interaction Alerts - Position/distance information (Updated Feb 7/8)](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.qvqurriseltj)

Here's link to the section in the BASICS design doc, [Complex Interaction Alerts - Position/Distance](https://docs.google.com/document/d/1HdDG9ds2MdbCb21l9qk3cI8yBQxK6-wBWNXC4Tloji8/edit#heading=h.xdhmilgerp8y)

All the info in GFL Basics is a bit better organized.
I tested both sims and have made notes of what is working and not working. The notes are in the right had column of the tables. I made my test for Regular on Feb 8th and my tests for Basics today.

**Comment by terracoda** [comment]
@zepumph, GFL Regular sounds really good, even without the new landmark, "last stop" for the "touching" scenarios.

**Comment by terracoda** [comment]
@zepumph, as I said on slack "I changed the strings a little to simplify the logic to manage the different strings, but it looks like you have implemented the the "At left edge" and "away" strings just fine. No need to change your nice work. We can discuss at our meeting."

**Comment by zepumph** [comment]
The above commits should update the sim according to this line in the REGULAR design doc table:
![image](https://user-images.githubusercontent.com/6856943/52669900-cb8c9800-2ec3-11e9-9a15-448f67c14092.png)

**Comment by zepumph** [comment]
From here I feel like I need to focus on BASICS for interview. Though much of this may apply over there. I'm going to look at phetsims/gravity-force-lab-basics#88 for now.

**Comment by terracoda** [comment]
@zepumph, you have done a great job implementing the `aria-valuetext` and ARIA live alerts for position and distance. I tested everything and there just a few small issues. The issues are highlighted in red in right-hand column of the tables in the design doc, but I will list them here for you. I don't think would significantly impact being ready for interviews next week unless the mistake was copied over to BASICS, which I will be testing later:
- [ ]  **In Focus Table** - `aria-valuetext` is working in all focus scenarios, except when m1 is touching m2 and m2 is at the right edge and has focus. In this single case, m2’s landmark is incorrectly showing as "left edge" when it should be "right edge". Probably just an incorrect string somewhere. 

- [ ] **See Step 8 in changing position table** - On the last step, when we provide "state information" we still want the word “now” before the force value because the force actually changed on that last step. For the next step, Step 9, there is no change in force value, so in that case the word "now" is not included. If you could make it, so we always hear "now" when there is a force change, that would be great.
- [ ] **Punctuation clean-up** - also in Focus Table - Remove period at end of distance string in `aria-valuetext`. VoiceOver puts in a comma automatically. It has taken me a long time to understand this for Voice Over, and it might vary between AT. That said, I think it is safe to remove the period at the end of the distance string in the `aria-valuetext`. All examples were updated.

**There are 2 still-todo's** that do not affect GFL Basics:** 
- using "Force vectors" instead of "Vectors" alone when Force values are not checked, and 
- an issue about reading out the times sign when scientific notation is checked.

I can move the still-todo's to new issues, so they do not fall off the radar. They are not high priority at the moment as they do not affect anything in GFL Basics.

**Comment by terracoda** [comment]
@zepumph, you only need to address the above checklist if they have a direct impact on GFL Basics.

**Comment by terracoda** [comment]
@zepumph, In Step 8, I swear I was hearing the correct alert (below) but minus the word "now" when I tested this morning.
- Vectors {{medium size}}{{, forces now {{0.463461}} micronewtons}}.

I am now hearing the regular changing force alert on the last stop, which does indeed contain "now", but on the last step (edge or last stop) I would like alert above. This special case alert appears in Step 8 and Step 17 in the design doc. 

The same issue exists in GFL Basics.

**Comment by terracoda** [comment]
@zepumph, I see, I am hearing two different alerts. The issue is is that **Step 8 has the correct alert with "now" missing**, and **Step 17 has the wrong alert**.

I would like the special "state information" alert in Step 17 as well. I would like this special case alert at all last steps, the ones that reach an edge and the ones that reach the opposite sphere. Apologies if that was not clear.

**Comment by terracoda** [comment]
@zepumph I added the Step 17 issue into the check list, and I I added that the first 3 items are also in the **BASICS** sim.

Ideally, if you could address the first three items, that would be great. The first 2 items are the most important if you are short on time.

**Comment by terracoda** [comment]
@zepumph, I have verified both sims, just tagging BASICS' related issue https://github.com/phetsims/gravity-force-lab-basics/issues/88

**Comment by zepumph** [comment]
@terracoda I think I got the first two bullets. Please review those, and I can work on them more tomorrow.

**Comment by terracoda** [comment]
The first two checkboxes are verified. Great work!
That's the critical stuff on position. I'll just go make sure it works in BASICS, too.

**Comment by terracoda** [comment]
@zepumph, yes the first 2 checkboxes are verified in BASICS as well.

**Comment by terracoda** [comment]
I am pretty sure all the issues about position will be address by GFLB's issue https://github.com/phetsims/gravity-force-lab-basics/issues/124 

Removing the priority label.

**Comment by terracoda** [comment]
After discussing Step 17 checkbox, I changed my mind. We are not providing state information at last step, only at going beyond an edge. We may consider this further, but for now. It's not an issue. I've updated the https://github.com/phetsims/gravity-force-lab/issues/124#issuecomment-463175345.

Punctuation looks good.
Closing this issue.

Stale distance information should be handled by https://github.com/phetsims/gravity-force-lab-basics/issues/128
