### ISSUE TITLE
The times sign (HTML entity) is not correctly read by Voice Over

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#131]
@mbarlow12 in the scientific notation, `&times;` is read out literally by VoiceOver.
**Is it** being read out correctly as "times" in NVDA?

Edited: That was supposed to be a question.

**Comment by terracoda** [comment]
Here's a screenshot of the problem.
I am wondering if we need a special character set for the browser to recognize the HTML entity?
<img width="844" alt="screen shot 2018-12-15 at 8 40 05 am" src="https://user-images.githubusercontent.com/1902116/50040513-309f4b00-0045-11e9-8035-1ddda75dcd36.png">

**Comment by mbarlow12** [comment]
In our alert implementation, we're setting `textContent` of the `aria-live` elements which strips any html in the content. If we want html entities in the alerts, we'll need to set `innerHTML` instead.

@jessegreenberg I'll make an issue to discuss if we want to go this route or whether for cases such as this, we should simply spell out "times" (which is quite simple).

**Comment by jessegreenberg** [comment]
I like the idea of using innerHTML for this, would there be any consequences in using AccessibilityUtil.setTextContent in AriaHerald?

**Comment by terracoda** [comment]
@mbarlow12, great for trying to resolve this.

I agree, it is more likely that the difference is caused by the aria-live region, rather than whether the content is in a `<p>` versus a `<li>`. Both paragraphs and list items are meant for content and there should not be any difference between them.

I think it is best to use the word, "times", at least in the alert until we have time to investigate this further. It would just be too strange for users to hear, "multiplication", instead of "times" in any interviews that will happen early in the new year.

It seems safe to leave the HTML entity in the PDOM page content if that's easy to do. However, if it is easier to swap them both out, please do so.

**Comment by terracoda** [comment]
@mbarlow12, just adding some references, in case we need them to investigate further:
- https://dev.w3.org/html5/html-author/charref
- other values for times: `&times;`, ` &#x000D7;`, and ` &#215;`

**Comment by terracoda** [comment]
@mbarlow12, we are using a `<meta charset="utf-8">`. Did you try the other entities, `&#x000D7;`, or `&#215;` in case it matters?

It likely won't matter since the entity is correctly rendered in the PDOM, just not in the alert.

**Comment by terracoda** [comment]
@mbarlow12, I also sent a question to the W3C WAI Interest Group list (w3c-wai-ig@w3.org)

**Comment by terracoda** [comment]
@mbarlow12, I think we decided at our design meeting on Dec 17, 2018 that we will use words for scientific notation, at least for sure for the alerts, and I'll move this issue to the a11y-research repo.

**Comment by terracoda** [comment]
@mbarlow12, I assume the text-based strings for scientific notation in the design document are sufficient to implement this change. Let me know if you need anything else.

Once implemented, we can close this issue. 
I have created a new issue in https://github.com/phetsims/a11y-research/issues/128 .

**Comment by terracoda** [comment]
I just verified with VoiceOver that the multiplication sign has not been changed to the word, "times".

I'll mark this issue on hold until we resume work on this sim. There is no scientific notation in GFL:BASICS and that sim is our priority at the moment.

**Comment by terracoda** [comment]
@zepumph, just removing onhold.

**Comment by terracoda** [comment]
@zepumph, I think I took care of this by using the word "times" instead of a coded representation of the symbol, see #150 
I'll mark this for you to review, too. Apologies, I forgot we had an open issue for this.
