### ISSUE TITLE
Mass slider list may benefit from aria-labelledby

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#132]
The Mass Controls are wrapped in a list structure to group them.

@mbarlow12, could you add an `aria-labelledby` on the `ul`. An explicit label for a group is not always necessary, but it in this case, the group may benefit from the name "Mass Controls".

```html
<h3 ... id="label-376-440-453-611">Mass Controls</h3>
<p ...>Change mass of spheres in kilograms.</p>
<ul ... aria-lebelledby="label-376-440-453-611">
	<li ...>
		<label ...>‪Mass 1‬</label>
		<input ...>
	</li>
	<li ...>
		<label ...>‪Mass 2‬</label>
		<input ...>
	</li>
</ul>
```

**Comment by terracoda** [comment]
@zepumph, this might be another easy a11y issue to implement across both sims, Regular and Basics.

Actually, I just noticed that the in REGULAR the parent `ul` surrounding the Mass 1 and Mass 2 sliders has been changed to a `div`, but the elements inside the div are still `li` elements. In the BASICS sim the entire structure is correct list code (`ul` with 2 `li`'s).

Can you make these 2 structures the same (with correct list structure) in both sims, and then once the correct list structure is in place in both sims, add `aria-lablledby="ID-of-Mass-Controls-H3"` to the `ul`?

**Alternative if above is too time intensive**
If fixing the list structure and adding `aria-labelledby` is too time intensive, just remove the list structures in both sims and forget about adding `aria-labelledby`.

Assigning over to @zepumph.

**Comment by zepumph** [comment]
@terracoda aria-lablledby was added and `div` was converted to `ul` in REGULAR. Please review.

**Comment by terracoda** [comment]
Thanks @zepumph, this looks and sounds good. We'll see from interviews if users prefer the "Mass Controls" with a label or without.

Closing issue.
