### ISSUE TITLE
Edge case alerts for when position changes when changing a mass

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#135]
@mbarlow12, we discussed the edge case alerts on Tuesday Dec 17. You mentioned they were working at some point. I am just opening this issue so we can track their implementation and any necessary changes if needed.

**Here's edge case 1:**
- When increasing the mass of m1 with the Mass 1 slider, the increase pushes m2 a little to the right:
  - Changed mass value: {{200}} kilograms. 
  - Alert: As mass {{gets bigger}} {{and moves {{m2}} {{right}}}} vectors {{get bigger}}, forces now {{1.021 506 micronewtons}}.

**Here's edge case 2:**
- When increasing the mass of m1 with the Mass 1 slider, and m2 is at the right edge of the track, m1 moves left:
  - Changed mass value: {{250}} kilograms. 
  - Alert: As mass {{gets bigger}} {{and moves {{left}}}} vectors {{get bigger}}, forces now {{3.604983 micronewtons}}.

More details in the design document under [Edge Case Examples](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit?ts=5c12c712#heading=h.kj3w5ar1mnks)

**Comment by terracoda** [comment]
@zepumph, I am adding screenshots of the sim with these alerts:

**Edge case 1**
<img width="617" alt="m2-mass-increase--m1-moves-left" src="https://user-images.githubusercontent.com/1902116/51529410-eaee5300-1e38-11e9-8af1-e109e8017fb9.png">


**Edge case 2**
<img width="617" alt="m1-mass-increase-m1-moves-left" src="https://user-images.githubusercontent.com/1902116/51529196-8e8b3380-1e38-11e9-8f1d-68f0a7e9e505.png">

The alerts fire sometimes when there is no actual visual movement. There is some funny business of how the spheres move or move each other when they are right next to each other. 

We may need to do some tweaking in the model to align actual movement and alerts, or make sure the visual movement is more consistent. 

That said, I think @mbarlow12 has done a nice job implementing these edge case alerts.

**Comment by terracoda** [comment]
@zepumph, please review this issue before closing. The alerts are implemented correctly in REGULAR, though as I said they may need some tweaking.

However, in BASICS, the alerts are **NOT ALWAYS** correct. Perhaps @mbarlow12 was not able to complete the work in that sim yet.

I am going to open a related issue in the BASICS repo, so we can track BASICS's issues there.

**Comment by zepumph** [comment]
Alright I''ll see you over in https://github.com/phetsims/gravity-force-lab-basics/issues/90 and https://github.com/phetsims/gravity-force-lab-basics/issues/91. Closing
