### ISSUE TITLE
Constant size checkbox - not changing and unchanging radius

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#136]
@mbarlow12, I just noticed some funny business with the Constant Size checkbox. I am marking it as a bug. I am not sure it is a11y-related.

When checked, color changes, but the radius doesn't until I do something else.
<img width="536" alt="screen shot 2018-12-21 at 1 52 02 pm" src="https://user-images.githubusercontent.com/1902116/50343638-f7c11380-0527-11e9-9a22-febd1d1ca4cf.png">

For example, the radius changes after hitting the Force Values check box:
<img width="505" alt="screen shot 2018-12-21 at 1 56 46 pm" src="https://user-images.githubusercontent.com/1902116/50343717-49699e00-0528-11e9-9ace-1df566c2f9a5.png">

Bu then the radia of the masses do not return to their representative mass size when I uncheck the Constant Size checkbox:
<img width="376" alt="screen shot 2018-12-21 at 1 50 49 pm" src="https://user-images.githubusercontent.com/1902116/50343804-99e0fb80-0528-11e9-9da1-6f4d231f2f06.png">

**Comment by mbarlow12** [comment]
This was a side effect from ISLC common changes to address Coulomb's Law RC issues. Handled in the above commit and working on master.

**Comment by terracoda** [comment]
@mbarlow12, looks good. I am closing this issue.
