### ISSUE TITLE
Helptext and grab/release alerts for Measure Distance button

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#141]
Re-writing this issue rather than posting a new one as there are several cross linked issues.

The "Grab Ruler" button has been renamed to be a "Measure Distance" button 

Related to #138 and #140, so @terracoda will make sure those issues are up-to-date-/and still relevant.

With the name change, non-visual users should understand what the button is for, and since they already have access to the distance value in other ways, they should be able to figure out that it is not important to use this Measure Distance, button. 

That said, they will be able to if they want to.

Please see the [Control Area section](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.uyv8gvko1gkk) and the [Interaction Support details](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.g7oj33o6p8qm) in the design doc for the initial help text, and grab and release context responses (alerts). 

I am working on the more context responses and useful location descriptions for the grabbed ruler.

**Comment by zepumph** [comment]
Unassigning until Ruler becomes a higher priority.

**Comment by terracoda** [comment]
See also, https://github.com/phetsims/scenery-phet/issues/536

**Comment by terracoda** [comment]
@zepumph there are 2 tables with all the context responses I think we will need. Please see [Interaction & Design Details for Measure Distance Button ](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.g7oj33o6p8qm) section in the design doc.

**Comment by terracoda** [comment]
Please reassign if you have questions.

**Comment by zepumph** [comment]
From https://github.com/phetsims/scenery-phet/issues/536#issuecomment-544698682, we aren't able to change the grab/drag interaction to support touch better. We are stuck with "double tap and hold" for application roles with mobile screen readers. The next steps for this issue seem to be:

* Note that https://github.com/phetsims/balloons-and-static-electricity/issues/452 is higher priority than this issue to support a haptics interview.
* Create two versions of the ruler help text, one for mobile touch and the other for keyboard.
* Decide/implement what the button roledescription is going to be.
* Audit the alerts @terracoda worked on last week for any changes that need to be done to support the "double tap and hold" interaction.

@terracoda over to you. These were what I thought came out of the meeting. Let me know if this is incorrect or incomplete.

**Comment by terracoda** [comment]
I got all the above done @zepumph 
Please see the table of contents and everything marked (New). 
Some stuff is in PDOM are and some stuff is below that.

**Comment by terracoda** [comment]
Back over to you :-)

**Comment by zepumph** [comment]
First I will do the changes to the PDOM structure and content. I still think here is the best place for that.

**Comment by zepumph** [comment]
I'm a little on the fence about whether or not to add alerts to master, or to a branch. This is because we are unsure if time will permit us to add these. I think for now I will proceed in master, but in a modular ruler alert specific type so if could be easy to omit it from a publication.

**Comment by terracoda** [comment]
@zepumph, I think all the alerts I have provides thus far should be good for master.
The alerts to come wold be for movement with the arrow keys. Those alerts may something we decide not to publish if we can't get them just right.

**Comment by terracoda** [comment]
@zepumph, when you are done and have a chance can you publish a dev version, so I can test on iphone, too.

**Comment by zepumph** [comment]
Alerts when the ruler is grabbed should be implemented now. @terracoda please review.

**Comment by terracoda** [comment]
@zepumph, the grabbed responses are working on keyboard, but as we discussed this morning I made a few tweaks to the actual phrases. 

**Change:**
> Grabbed. In home position below spheres. Centers of spheres 4 ‪meters‬ apart. Press J plus C keys to jump ruler and align zero mark at center of m1. Space to release.

**To:**
> Grabbed. In home position below **mass** spheres. **Centers 4** ‪meters‬ apart. Press J plus C keys to jump ruler **to** center of m1. Space to release.

As you noted as well, the `aria-roledescription` text needs to be changed to "movable".

I haven't tested on mobile yet.

**Comment by terracoda** [comment]
@zepumph, is this ready to test on mobile voice over, too?

**Comment by zepumph** [comment]
I made the phrase changes, and removed the "move in four directions" role description. I also removed it from faradays law, as likely that will become "movable" when we get there too. 

>@zepumph, is this ready to test on mobile voice over, too?

Over in https://github.com/phetsims/gravity-force-lab/issues/140#issuecomment-552534326 you gave good initial feedback from gesture testing. I'm going to close this issue and carry on in sub issues from that feedback. Please reopen if there is anything else for this issue. We can open new issues for future bugs.
