### ISSUE TITLE
dead code in MassControl

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-force-lab#147]
Dead code in MassControl.  Please delete it or document why it's commented out with a TODO and issue number.

```
// accessibleValuePattern: valueKilogramsPatternString, // {{value}} kilograms
```

**Comment by terracoda** [comment]
@pixelzoom, we are actively working on changes to GFL Regular and GFL Basics which both use MassControl. 

Our top priority is to have description in GFL Basics ready for interviews as soon as possible (hopefully by Feb 18). 

I do not think we are ready for a code review yet. Hopefully, the comment is not in your way, and this issue is not too pressing.

**Comment by pixelzoom** [comment]
@terracoda I understand, this was not a formal code review.  I was making changes in other common code, and the only way to change related things in Javascript is via string search.  And looking at this, I had no idea what the reason was for commenting out code, and I apparently did spend unnecessary time on it.  Which is why it's standard practice to document why code is commented out.  I believe that practice applies to a11y work.

**Comment by pixelzoom** [comment]
Looks like the dead code was removed by @zepumph in https://github.com/phetsims/gravity-force-lab/commit/5193dcc0401425819902f6b86d148cc12602828f.   There's no issue number referenced in that commit.  Is there a GitHub issue for the work mentioned by @terracoda in https://github.com/phetsims/gravity-force-lab/issues/147#issuecomment-460918838?

**Comment by zepumph** [comment]
>There's no issue number referenced in that commit.

I'm not sure I understand,  https://github.com/phetsims/gravity-force-lab/commit/5193dcc0401425819902f6b86d148cc12602828f points over to https://github.com/phetsims/gravity-force-lab/issues/146

I agree with @pixelzoom's analysis of the code. There is a fair bit of commented out code in these repos. Now that I am working through files, I am removing code that like as I get to it. I was working on the understanding that it wouldn't be worth my time to delete all of these up front, but instead as I found them while working. Do you disagree?

**Comment by pixelzoom** [comment]
Mea cupla, https://github.com/phetsims/gravity-force-lab/commit/5193dcc0401425819902f6b86d148cc12602828f has a long commit message and WebStorm was truncating the issue number. 

Thanks for the clarification on when dead code will be deleted. That all songs great.

Closing this issue since this code in question is gone.
