### ISSUE TITLE
Use "Force vectors" in place of "Vectors" in all alerts

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#149]
In  #124 I mentioned this item was still todo. It is also highlighted in red in the design document.
This content update does not affect GFL Basics, so it is not a high priority. Just get to it when there is nothing more pressing.

When the Force Values checkbox is not checked "Vectors" back to "Force vectors" in the changing force alerts. Note "Force vectors" is already used in the force focus alert. As a strategy to shorten the long alerts when Force Values is checked, I shortened "Force vectors" to "Vectors".

However, **when Force Values is notchecked**, the changing force alert is much shorter, so it would be nice to keep "Force vectors" in the changing force alert for that case.

For example with Force Values checked we hear:
- Vectors {{get bigger}}, forces now {{force-value}} micronewtons.
- Vectors {{get smaller}}, forces now {{force-value}} micronewtons.
- Vectors {{get bigger}}{{, forces now {{force-scientific-notation}} newtons.
- Vectors {{get smaller}}, forces now {{force-scientific-notation}} newtons.

**With Force Values notchecked** I'd like
- Force vectors {{get bigger}}.
- Force vectors {{get smaller}}.

**Comment by terracoda** [comment]
In design meeting on June 18th, @emily-phet and I discussed this further, and decided it would be best to use "force vectors" all the time and not use a shortened version "vectors" in any cases.

This decision will require some changes to the strings. Assigning to myself to provide examples and to clean up design doc, or to start a new issue.

**Comment by terracoda** [comment]
I think we can continue in this issue with a changed title.

**Comment by terracoda** [comment]
Change, for example the current alerts to use "Force vectors" instead of "Vectors":
- **For position sliders with Force Values checked we currently hear:**
  - Vectors {{get bigger}}, forces now {{force-value}} micronewtons.
  - Vectors {{get smaller}}, forces now {{force-value}} micronewtons.
  - Vectors {{get bigger}}{{, forces now {{force-scientific-notation}} newtons.
  - Vectors {{get smaller}}, forces now {{force-scientific-notation}} newtons.
- **Change force alerts to:**
  - Force vectors {{get bigger}}, forces now {{force-value}} micronewtons.
  - Force vectors {{get smaller}}, forces now {{force-value}} micronewtons.
  - Force vectors {{get bigger}}{{, forces now {{force-scientific-notation}} newtons.
  - Force vectors {{get smaller}}, forces now {{force-scientific-notation}} newtons.

- **With Position sliders with Force Values not checked we currently hear:**
  - Vectors {{get bigger}}.
  - Vectors {{get smaller}}.
- **Change force alerts to:**
  - Force vectors {{get bigger}}.
  - Force vectors {{get smaller}}.

### Mass Alert are also affected
- **With Force Values checked we currently hear:**
  - As mass {{get bigger}}, vectors get bigger, forces now {{force-value}} micronewtons.
  - As mass {{gets smaller}}, vectors get smaller, forces now {{force-value}} micronewtons.
  - As mass {{get bigger}}, vectors get bigger, forces now {{{force-scientific-notation}} newtons.
  - As mass {{gets smaller}}, vectors get smaller, forces now {{force-scientific-notation}} newtons.
- **With Force Values not checked we currently hear:**
  - As mass {{gets bigger}}, vectors {{get bigger}}.
  - As mass {{gets smaller}}, vectors {{get smaller}}.

 **With Force Values checked change to:**
- As mass {{get bigger}}, force vectors get bigger, forces now {{force-value}} micronewtons.
- As mass {{gets smaller}}, force vectors get smaller, forces now {{force-value}} micronewtons.
- As mass {{get bigger}}, force vectors get bigger, forces now {{{force-scientific-notation}} newtons.
- As mass {{gets smaller}}, force vectors get smaller, forces now {{force-scientific-notation}} newtons.

**With Force Values not checked change to:**
- As mass {{gets bigger}}, force vectors {{get bigger}}.
- As mass {{gets smaller}}, force vectors {{get smaller}}.

**Comment by terracoda** [comment]
@zepumph, I made the changes the regular and capitalized strings. The patterns all seem to be working. 

Marking for you to review as this is a shared repo.

**Comment by terracoda** [comment]
@zepumph, adding code review label to remind myself that this is not for me to review.

**Comment by zepumph** [comment]
This looks good to me!
