### ISSUE TITLE
Convert times symbol to the word "times" until we have a better solution

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#150]
As mentioned in #124 this little still-todo will need to be done eventually.
It does not affect GFL Basics, so just get to it when there is nothing more pressing to do.

When scientific notation is checked, the times symbols is read out as "multiplication" by VoiceOver. To make it more clear, and until we have a robust solution for reading math, please convert times symbol to the word “times”.

**Comment by terracoda** [comment]
@zepumph, I updated the first parameter - the one that was being used in the sim. There are actually two lines of code for this parameter.:
``` javascript
scientificNotationPattern: {
      value: '{{mantissa}} times 10 to the {{exponent}}'
    },
scientificNotationPatternNoHtml: {
      value: '{{mantissa}} times 10 to the {{exponent}}'
```
Maybe there is no need for the `scientificNotationPatternNoHtml` pattern now?

This can be dealt with during a code review, maybe.
Marking this issue "ready-to-review" and assigning to you as it is in a shared repo.

**Comment by zepumph** [comment]
Thanks for reviewing. Indeed `scientificNotationPatternNoHtml` wasn't being used, and now that it was the same as the `scientificNotationPattern` we can just remove it.
