### ISSUE TITLE
Spelling error in comparitiveValue

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-force-lab#151]
Discovered during https://github.com/phetsims/chipper/issues/739

`comparitive` should be spelled `comparative`

**Comment by terracoda** [comment]
I'm tagging @zepumph, in case he would like to reassign this to himself.

**Comment by mbarlow12** [comment]
Can't find any more instances of `comparitive`. Ready to close.

**Comment by samreid** [comment]
Looks great, thanks!  Closing.
