### ISSUE TITLE
undocumented use of `utteranceQueue.clear();`

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab#152]
There are only 5 uses of `utteranceQueue.clear();`. @mbarlow12 could you please document the reason why it was chosen to clear the queue before alerting the mass changes.

I'm also wondering if you could reference an issue here (if there is one), or discuss your thoughts on when that pattern should be used. I have not used utteranceQueue beyond simple/straightforward usage, and would like to know that pitfalls you encountered that inspired clearing the queue. Thanks!

In `GravityForceLabAlertManager.js`

```js
  model.object1.valueProperty.lazyLink( ( value, oldValue ) => {
        utteranceQueue.clear();
        this.alertMassValueChanged( OBJECT_ONE, value, oldValue );
      } );

      model.object2.valueProperty.lazyLink( ( value, oldValue ) => {
        utteranceQueue.clear();
        this.alertMassValueChanged( OBJECT_TWO, value, oldValue );
      } );
```

**Comment by mbarlow12** [comment]
@zepumph this may be an error in my understanding for how the queue works. But I was trying to eliminate stacking up a long series of alerts if the user is rapidly pressing one of the arrow keys. I realize that once it's read by the screen reader, there's nothing we can do, but it was an attempt to have what the user hears be a little more in line with the current state of the sim.

As far as I know, it's not vital to the functioning of the alerts, so if it doesn't actually improve the user experience, feel free to remove them.

**Comment by ariel-phet** [comment]
@zepumph back to you to decide if this can be cleaned up/closed

**Comment by zepumph** [comment]
Thanks! Those have since been deleted while working on publishing GFLB
(deleted in 74398ab3dac543f0b9c89fe0aade396b7b17100a)

Closing
