### ISSUE TITLE
Usability on small screen review

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab#153]
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* No needed changes noticed
* Pointer areas not on some intractable pieces (orbs and ruler)

Screenshots:
![Image from iOS](https://user-images.githubusercontent.com/41024075/55908343-676e1380-5b96-11e9-84c3-8667c8f82090.png)

**Comment by arouinfar** [comment]
https://github.com/phetsims/joist/issues/556 will discuss the possibility of automatically showing `pointerAreas` for all UI components, but according to @kathy-phet:
> I don't think its worth  spending time republishing just to make these visible though.
