### ISSUE TITLE
Consider beyond-edge force alerts for mass controls?

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#155]
Related to sounds for edges https://github.com/phetsims/gravity-force-lab-basics/issues/152
and the alerts designed for the position sliders for when a user tries to go beyond an edge... we may need to consider something similar fro the mass controls.

**Comment by terracoda** [comment]
@terracoda to explore in design doc, if state information that included comparative size and size of force information would be useful as a beyond-edge alert, similar to the state information (distance and force) is provided for the position sliders.

**Comment by terracoda** [comment]
@emily-phet and @arouinfar, I have added 4 views of a "going beyond" max mass context response (alert) when using mass 1 slider.

I think this context response makes the mass control interaction more inline with how the distance sliders work when trying to go beyond an edge position. I think it will be useful and perhaps temporarily address the lack of a sound at a mass value edge.

Do you agree, and do you have any feedback on the content of the alert?

Please see [Table: Edge Case 4 examples going beyond max/min mass (added July 22)](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.p1dymmuw4j7q)

Note, I've really only provided one example. Let me know if you need more.

**Comment by terracoda** [comment]
And, I will add that, the same alert could be added to GFL Basics at the appropriate time, maybe that sim's first maintenance release after publication.

**Comment by arouinfar** [comment]
@terracoda is this the table you're referring to? https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.hnch5crz7cij

![image](https://user-images.githubusercontent.com/8419308/61662232-3d46ea00-ac8b-11e9-8f14-f3b72b54af40.png)

It's not clear to me which part of this is the beyond-edge alert.

**Comment by terracoda** [comment]
@arouinfar, yes I am referring to that table. Apologies for the lack of explanation.
This examples in the table would fire after the user reaches a max or min mass value (1 kilogram or 1000 kilograms), and once they try to make the mass larger than 1000 kg or smaller than 1 kg. The alert would only fire once. 
The intention is to cue the end of the mass slider, and to provide an idea of the state of the sim at that point. There is a similar alert for the edges on the position/distance sliders, and these alerts seemed to work well in interviews in GFLBasics
**Here's the position/distance  slider go-beyond-edge alert:**
The alert provides state information rather than describing a change that is happening.
<img width="353" alt="Screen Shot 2019-07-24 at 6 17 27 PM" src="https://user-images.githubusercontent.com/1902116/61810657-fc440680-ae3f-11e9-93cd-812cd3623852.png">

If you look at the next screen shot, the last alert in the orange box (the top alert) describes the mass reaching 1 kg. Then imagine pressing the left arrow key one more time and trying to make the mass smaller.  If you try to make the mass smaller than 1 kg, the next alert in the orange box would describe the state of mass (and force) from the point of view of the mass 1 slider like this:

> Much much smaller than m2, force vectors tiny, forces 0.00927 micronewtons.

<img width="359" alt="Screen Shot 2019-07-24 at 6 18 25 PM" src="https://user-images.githubusercontent.com/1902116/61811489-da4b8380-ae41-11e9-93f2-97c10cc2d55f.png">

**Comment by terracoda** [comment]
@arouinfar, what do you think of this go-beyond min-/max-mass alert?

**Comment by arouinfar** [comment]
Thanks for the clarification @terracoda!

> This examples in the table would fire after the user reaches a max or min mass value (1 kilogram or 1000 kilograms), and once they try to make the mass larger than 1000 kg or smaller than 1 kg. The alert would only fire once.

Seems like it would be useful to communicate you've reached the min/max mass in the alert, similar to "last stop right" in the distance-related alert. The proposed go-beyond-edge alert is missing this information. (Or maybe I'm missing something?)

> There is a similar alert for the edges on the position/distance sliders, and these alerts seemed to work well in interviews in GFLBasics

IMO, that's a pretty compelling reason to include something analogous in GFL.

**Comment by terracoda** [comment]
@arouinfar, you are not missing something. The mass-related alerts have neither "last stop" nor "track end" parameters which are delivered upon reaching an edge position. I felt the "track" like interaction and the variable position for a sphere's "last stop" really needed these cues. I was less sure that the max/min mass values needed such cuing.

If we did add max mass and min mass parameters, it would sound like this:
- upon reaching max mass: "{{maximum mass}}, as mass gets bigger, force vectors get bigger, forces now 0.83426 micronewtons."

**Comment by terracoda** [comment]
oops posted early, editing previous issue...

**Comment by terracoda** [comment]
@arouinfar, I propose we go with the first examples "without a max/min" parameter in https://github.com/phetsims/gravity-force-lab/issues/155#issuecomment-514967976 . It's simpler. We may eventually have a sound that indicates hitting the max or min mass.

**Comment by terracoda** [comment]
And just for clarification both GFL abd GFLB are working exactly the same right now with beyond-edge alerts for positional edges, and both sims lack similar alerts for going beyond max/min mass. My proposal is meant to be implemented in both sims.

**Comment by terracoda** [comment]
@arouinfar, another reason I think we should go with the first examples (without max/min parameters for the mass controls) is that the "edges" of the mass controls seem much less important, less emphasized to me. The idea of "edges" for the move sphere sliders seems to have nuance that needs to be communicated.

For me, it makes sense to not design the descriptions exactly the same even if the interaction is quite similar (i.e., both interactions are sliders). In the same way that the visuals are different, the descriptions can also be different.

**Comment by terracoda** [comment]
@arouinfar, do you have any further thoughts or questions?
Do you feel more comfortable with option 1 Without max/min parameters outlined in https://github.com/phetsims/gravity-force-lab/issues/155#issuecomment-514967976 ?

Personally, I really like the state information alert/response that would be delivered if a user tries to step beyond max or min mass. The alert provides state information (with different wording) subtly signifying that there was no change in mass.

**Comment by terracoda** [comment]
@emily-phet or @arouinfar please assign to @zepumph if there are no more design questions about this issue.

**Comment by arouinfar** [comment]
@terracoda thanks for the clarification.

> @arouinfar, I propose we go with the first examples "without a max/min" parameter in #155 (comment) . It's simpler. We may eventually have a sound that indicates hitting the max or min mass.

Yes, that sounds reasonable to me! Off to @zepumph.

**Comment by zepumph** [comment]
It seems like we want to add a brand new alert, which is based on the user component, not the model. This is at least how it sounds as it pertains to the implementation. This new alert would monitor if you were at the min/max mass already, and then the component was interacted with again in the respective end-point direction, yielding no change in the Property. 

We implemented something like this in Friction also, and there too it was separate from the model, and instead looked only at the component that was being interacted with (in that case the keyboard listener attached to the book).

So with that back story in mind, my thoughts are that this alert won't be tied to the other (seemingly related) mass change alerts you were speaking about above. 

In GFL this will be implemented in the "endDrag" callback for the slider in `ISLCObjectControlPanel`, and in GFLB this will be similarly added to the "endDrag" callback for the number picker in `GFLBMassControl`. I'll investigate further and report back.

**Comment by zepumph** [comment]
In the below patch I have this working with a hard coded string that alerts at the correct time. I took some notes about how I can formulate the dynamic string but first I want to discuss this with @terracoda. To add in the dynamic string will take a bit more work and refactoring, so I want to make sure that what I am thinking for these alerts is aligned with her, this will save time I think. 

<details>

```diff
Index: sun/js/accessibility/AccessibleValueHandler.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- sun/js/accessibility/AccessibleValueHandler.js	(revision ec09fe383a09dbe8976a963d4bfb53e51624d4e3)
+++ sun/js/accessibility/AccessibleValueHandler.js	(date 1569887852048)
@@ -147,7 +147,7 @@
              * @param {number} formattedValue - mapped value fixed to the provided decimal places
              * @param {number} newValue - the new value, unformatted
              * @param {number} previousValue - just the "oldValue" from the property listener
-             * @returns {string}
+             * @returns {string|null} - if null, then no alert will be sent
              */
             a11yCreateValueChangeAlert: null,
 
@@ -399,21 +399,27 @@
             this.utterance.resetTimingVariables();
 
             const formattedValue = this.getA11yFormattedValue();
-            this.utterance.alert = this.a11yCreateValueChangeAlert( formattedValue, this._valueProperty.value, this.oldValue );
+            const onEndAlert = this.a11yCreateValueChangeAlert( formattedValue, this._valueProperty.value, this.oldValue );
+
+            // only if it returned an alert
+            if ( onEndAlert ) {
+              this.utterance.alert = onEndAlert;
 
-            if ( utteranceQueue.hasUtterance( this.utterance ) ) {
-              this.timesChangedBeforeAlerting++;
-            }
-            else {
-              this.timesChangedBeforeAlerting = 1;
-            }
+              if ( utteranceQueue.hasUtterance( this.utterance ) ) {
+                this.timesChangedBeforeAlerting++;
+              }
+              else {
+                this.timesChangedBeforeAlerting = 1;
+              }
 
-            // 700 and 2000 ms are arbitrary values but sound good with limited testing. We want to give enough time
-            // for VO to read aria-valuetext but don't want to have too much silence before the alert is spoken.
-            const delayTime = Math.min( this.timesChangedBeforeAlerting * 700, 2000 );
-            this.utterance.alertStableDelay = delayTime;
+              // 700 and 2000 ms are arbitrary values but sound good with limited testing. We want to give enough time
+              // for VO to read aria-valuetext but don't want to have too much silence before the alert is spoken.
+              const delayTime = Math.min( this.timesChangedBeforeAlerting * 700, 2000 );
+              this.utterance.alertStableDelay = delayTime;
 
-            utteranceQueue.addToBack( this.utterance );
+              utteranceQueue.addToBack( this.utterance );
+            }
+
           }
         },
 
Index: sun/js/accessibility/AccessibleSlider.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- sun/js/accessibility/AccessibleSlider.js	(revision ec09fe383a09dbe8976a963d4bfb53e51624d4e3)
+++ sun/js/accessibility/AccessibleSlider.js	(date 1569888429879)
@@ -55,13 +55,11 @@
         initializeAccessibleSlider: function( valueProperty, enabledRangeProperty, enabledProperty, options ) {
           const self = this;
 
-          const defaults = {
+          options = _.extend( {
             startDrag: _.noop, // called when a drag sequence starts
             endDrag: _.noop, // called when a drag sequence ends
             constrainValue: _.identity // called before valueProperty is set
-          };
-
-          options = _.extend( {}, defaults, options );
+          }, options );
 
           // AccessibleSlider uses 'drag' terminology rather than 'change' for consistency with Slider
           assert && assert( options.startChange === undefined, 'AccessibleSlider sets startChange through options.startDrag' );
Index: gravity-force-lab-basics/js/gravity-force-lab-basics/view/GFLBScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- gravity-force-lab-basics/js/gravity-force-lab-basics/view/GFLBScreenView.js	(revision d815793bfc529c51951cf86d6060a9ed6f3977c0)
+++ gravity-force-lab-basics/js/gravity-force-lab-basics/view/GFLBScreenView.js	(date 1569888429875)
@@ -171,10 +171,10 @@
 
       // mass controls
       const massControl1 = new GFLBMassControl( mass1String, model.object1.valueProperty,
-        GFLBConstants.MASS_RANGE, mass1ControlLabelString, OBJECT_ONE,
+        GFLBConstants.MASS_RANGE, mass1ControlLabelString, OBJECT_ONE, alertManager,
         massDescriber, tandem.createTandem( 'massControl1' ) );
       const massControl2 = new GFLBMassControl( mass2String, model.object2.valueProperty,
-        GFLBConstants.MASS_RANGE, mass2ControlLabelString, OBJECT_TWO,
+        GFLBConstants.MASS_RANGE, mass2ControlLabelString, OBJECT_TWO, alertManager,
         massDescriber, tandem.createTandem( 'massControl2' ), {
           color: new Color( 255, 0, 0 )
         } );
Index: gravity-force-lab-basics/js/gravity-force-lab-basics/view/GFLBMassControl.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- gravity-force-lab-basics/js/gravity-force-lab-basics/view/GFLBMassControl.js	(revision d815793bfc529c51951cf86d6060a9ed6f3977c0)
+++ gravity-force-lab-basics/js/gravity-force-lab-basics/view/GFLBMassControl.js	(date 1569888458853)
@@ -37,11 +37,12 @@
      * @param {Range} massRange
      * @param {String} labelContent - a11y, the content of the label for the mass control
      * @param {ISLCObjectEnum} thisObjectEnum
+     * @param {GFLBAlertManager} alertManager
      * @param {GFLBMassDescriber} massDescriber
      * @param {Tandem} tandem
      * @param {Object} [options]
      */
-    constructor( titleString, valueProperty, massRange, labelContent, thisObjectEnum,
+    constructor( titleString, valueProperty, massRange, labelContent, thisObjectEnum, alertManager,
                  massDescriber, tandem, options ) {
 
       options = _.extend( {
@@ -54,6 +55,9 @@
         tandem: tandem.createTandem( 'titleText' )
       } );
 
+      // Keep track of the current mass between the start and end of an interaction to see if we should alert.
+      let currentMass = valueProperty.value;
+
       const numberPicker = new NumberPicker( valueProperty, new Property( massRange ), {
         font: new PhetFont( 20 ),
         scale: 1.5,
@@ -70,7 +74,22 @@
         // a11y
         pageKeyboardStep: BILLION_MULTIPLIER * 2,
         accessibleName: labelContent,
-        a11yCreateValueChangeAriaValueText: () => massDescriber.getMassAndUnit( thisObjectEnum )
+
+        a11yCreateValueChangeAriaValueText: () => massDescriber.getMassAndUnit( thisObjectEnum ),
+
+        // on end interaction, if alert a special alert if the mass started at the min/max and didnt' change.
+        a11yCreateValueChangeAlert: () => {
+
+          // no change and at max or min
+          if ( currentMass === valueProperty.value && ( currentMass === massRange.max || currentMass === massRange.min ) ) {
+            return alertManager.alertMassMinMaxEdge();
+          }
+          return null;
+        },
+        startChange: () => {
+          currentMass = valueProperty.value;
+        }
+
       } );
       const numberPickerLabel = new Text( billionKgString, {
         font: new PhetFont( { size: 14 } ),
Index: gravity-force-lab/js/gravity-force-lab/view/MassPDOMNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- gravity-force-lab/js/gravity-force-lab/view/MassPDOMNode.js	(revision ea4bdbfda93bc626bfe64fcb98c28ca92e274d08)
+++ gravity-force-lab/js/gravity-force-lab/view/MassPDOMNode.js	(date 1569888807073)
@@ -99,8 +99,7 @@
     updateMassAndPositionElement() {
       const sizeText = StringUtils.fillIn( sizePatternString, {
         thisObjectLabel: this.massLabel,
-        massValue: this.getMassValue(),
-        units: this.massDescriber.unit
+        massValue: this.getMassValue()
       } );
 
       this.massAndPositionNode.innerContent = StringUtils.fillIn( sizeAndDistancePatternString, {
Index: gravity-force-lab/js/gravity-force-lab/view/GravityForceLabAlertManager.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- gravity-force-lab/js/gravity-force-lab/view/GravityForceLabAlertManager.js	(revision ea4bdbfda93bc626bfe64fcb98c28ca92e274d08)
+++ gravity-force-lab/js/gravity-force-lab/view/GravityForceLabAlertManager.js	(date 1569887928744)
@@ -139,6 +139,11 @@
       utteranceQueue.addToBack( this.massChangedUtterance );
     }
 
+    alertMassMinMaxEdge() {
+      this.massChangedUtterance.alert = this.massDescriber.getMassMaxMinText();
+      utteranceQueue.addToBack( this.massChangedUtterance );
+    }
+
     /**
      * @private
      */
Index: gravity-force-lab/js/gravity-force-lab/view/describers/MassDescriber.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- gravity-force-lab/js/gravity-force-lab/view/describers/MassDescriber.js	(revision ea4bdbfda93bc626bfe64fcb98c28ca92e274d08)
+++ gravity-force-lab/js/gravity-force-lab/view/describers/MassDescriber.js	(date 1569889021482)
@@ -291,6 +291,27 @@
       // use size or density depending on if constant checkbox is checked.
       return this.constantRadiusProperty.get() ? getRelativeDensityFromIndex( index ) : getRelativeSizeFromIndex( index );
     }
+
+
+    /**
+     * "Much much larger than ‪m2, force vectors large, forces 0.83426 micronewtons.""
+     *
+     *         relativeSize: this.massDescriber.getRelativeSizeOrDensity( this.objectEnum ),
+     *
+     *         forceAndVectorPattern, "first part of"
+     *
+     *         ForceDescriber:
+     *          const forceValue = this.getFormattedForce();
+     *          const units = this.units;
+     *
+
+
+     * @public
+     * @returns {string}
+     */
+    getMassMaxMinText() {
+      return 'Much much larger than ‪m2, force vectors huge, forces 0.83426 micronewtons.';
+    }
   }
 
   /**
Index: gravity-force-lab/js/gravity-force-lab/view/MassControl.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- gravity-force-lab/js/gravity-force-lab/view/MassControl.js	(revision ea4bdbfda93bc626bfe64fcb98c28ca92e274d08)
+++ gravity-force-lab/js/gravity-force-lab/view/MassControl.js	(date 1569888429895)
@@ -28,7 +28,7 @@
 
     /**
      * @param {string} titleString
-     * @param {Property.<number>} valueProperty
+     * @param {NumberProperty} valueProperty
      * @param {Range} massRange
      * @param {Color} thumbColor
      * @param {ISLCObjectEnum} massEnum
@@ -40,6 +40,8 @@
     constructor( titleString, valueProperty, massRange, thumbColor, massEnum, updateDescriptionProperties,
                  alertManager, massDescriber, tandem ) {
 
+      let currentMass = valueProperty.value;
+
       super( titleString, unitsKgString, valueProperty, massRange, {
         // panel options
         fill: '#FDF498',
@@ -55,11 +57,24 @@
             thumbFill: thumbColor.colorUtilsBrighter( 0.15 ),
             thumbFillHighlighted: thumbColor.colorUtilsBrighter( 0.35 ),
             constrainValue: v => Util.roundToInterval( v, 10 ),
+            startDrag() {
+              currentMass = valueProperty.value;
+            },
 
             // a11y
             keyboardStep: 50,
             pageKeyboardStep: 100,
             accessibleName: titleString,
+
+            // on end interaction, if alert a special alert if the mass started at the min/max and didnt' change.
+            a11yCreateValueChangeAlert: () => {
+
+              // no change and at max or min
+              if ( currentMass === valueProperty.value && ( currentMass === massRange.max || currentMass === massRange.min ) ) {
+                return alertManager.alertMassMinMaxEdge();
+              }
+              return null;
+            },
             a11yCreateValueChangeAriaValueText: () => massDescriber.getMassAndUnit( massEnum )
           },
           titleNodeOptions: { font: new PhetFont( 24 ) },

**Comment by terracoda** [comment]
@zepumph, in https://github.com/phetsims/gravity-force-lab/issues/155#issuecomment-536795360 you said, 
> We implemented something like this in Friction also, and there too it was separate from the model, and instead looked only at the component that was being interacted with (in that case the keyboard listener attached to the book).

But, how do we do it for the edges of the Position sliders in this sim and in GFL:Basics? For example:
- **Reaching edge:**
  - Track end left, force vectors get smaller, forces now 0.057734 micronewtons.
- **Then 1st key press beyond edge:** 
  - Far from ‪m2‬, force vectors very small, forces 0.057734 micronewtons.

**Comment by terracoda** [comment]
@zepumph, warning that some of the example values might be wonky in the examples above. Technically there is no state change between the last alert when the user reaches the maximum or minimum and when they try to go beyond that maximum/minimum. We just deliver "state information" instead of "what's happening" information.

**Comment by zepumph** [comment]
We wonder if this type of alert isn't worth adding as an option to AccessibleValueHandler, something like `beyondMinMaxAlert`, or `beyondEdgeAlert`.

**Comment by zepumph** [comment]
@terracoda and I discussed this today, and I will basically implement the patch, and she will review from there.

**Comment by zepumph** [comment]
This should be implemented now. @terracoda, besides some of the strange capitalization, how does this look? We can update the capitalization, but it will take a bit of effort, and I wanted to get the content reviewed to make sure it was worth the change.

This should be implemented in GFLB and GFL.

**Comment by terracoda** [comment]
@zepumph, the content for the beyond-edge alerts are great. 
Can you adjust the capitalization, so it is sentence case? A capital on the first word, and then no capital on "Force"
**Change:**
> much much smaller than ‪m2‬, Force vector is tiny, forces 0.016685 micronewtons.
**To:**
> **M**uch much smaller than ‪m2‬, **f**orce vector is tiny, forces 0.016685 micronewtons.

More importantly, there is some strange behaviour on the slider. I'll open a new issue for that.

**Comment by zepumph** [comment]
Above is the "force vector" capitalization fix. To get the other fix, we will need to implement a completely different set of regions, all capitalized instead of lower case. I think this may take about an hour or so. Does that sound reasonable to you @terracoda?

**Comment by terracoda** [comment]
@zepumph, I think you should leave the lower case at the start of the alert for now. It is much better without a capital "F" in the middle of the sentence ;-)

It is likely time much better spent to create a common-code regex function that is capable of checking for case on the first word of a context response.

**Comment by terracoda** [comment]
This is an issue that keeps popping up, so best to create a general solution. I don't like the hard-coded solution of a set of regions that are uppercase and a set of regions that are lowercase.

**Comment by terracoda** [comment]
Go ahead and mark ready to review, if that's where you are with this one ;-)

**Comment by zepumph** [comment]
>so best to create a general solution. I don't like the hard-coded solution of a set of regions that are uppercase and a set of regions that are lowercase.

I don't like them either, but I also don't know a translatable and more general solution. We could do a bit more work investigating, but, like in https://github.com/phetsims/molarity/issues/107, I'm unsure what will come from it. If we want to support i18n, we can't assume that capitalization strategies for English will work for all languages, and we likely will unfortunately need a separate copy for each. Do you want to make an issue for further investigation about this?

>Go ahead and mark ready to review, if that's where you are with this one ;-)

I think we are ready close this issue right? What else is ready for review? We should also leave open until necessary side issues have been created. 

>It is likely time much better spent to create a common-code regex function that is capable of checking for case on the first word of a context response.

Does that mean you would like to make sure every aria-live alert starts with a capital letter? We should make an issue if so.

**Comment by terracoda** [comment]
@zepumph, I didn't realize you needed duplicate regions for internationalization.

Based on recent work, I feel it's only context responses that need sentence case, so yes, let's go ahead and open an issue for that, so we can discuss this further, and potentially find a general solution.

@zepumph, I just noticed an "is" in the response. Please remove need for the "**is**". Sorry, I missed that.
- "much much larger than ‪m2‬, force vector **is** very small, forces 1.66852 micronewtons."

**Comment by terracoda** [comment]
Back over to you to remove the "is", and then we can close :-)

**Comment by terracoda** [comment]
@zepumph, is going to capitalize the regions the beyond-edge context response (comparative mass regions)

**Comment by zepumph** [comment]
>@zepumph, I just noticed an "is" in the response. Please remove the "is". Sorry, I missed that.

How important is this to you? Currently the phrase "force vector is {{size}}" is used in multiple places, including this alert for beyond min/max mass. The "is" could be factored out, but unless it is vital, the code will look better having a single function to get this phrase for its various uses. Is that alright?

**Comment by zepumph** [comment]
Added capitalization above. I'll use the above commit to describe the duplicated string issue to other developers. Over to @terracoda to answer https://github.com/phetsims/gravity-force-lab/issues/155#issuecomment-553031135.

**Comment by terracoda** [comment]
The capitalization is great. The force vector size string is incorrect. It should be the same as the one used for the position sliders... Sorry, I missed this... I wasn't reading carefully. I only initially saw the "is".

**It should say** 
comparattiveSizeOfMasses + **"force vectors {{sizeOfVectors}}"** + forcesValueInMicronewtons.

**For example**
- "Much much bigger than m1, **force vectors {{sizeOfVecrtors}}**, forces {{forceValue}} micronewtons."

**Comment by zepumph** [comment]
Sounds good; implemented above. Anything else here @terracoda?

**Comment by terracoda** [comment]
Looks good, closing.
