### ISSUE TITLE
Should MassPDOMNode be disposable?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-force-lab#157]
It is likely not necessary, but since gravity-force-lab is a dependency for gravity-force-lab-basics, I am wondering if disposal should be supported.

My instinct is that it isn't necessary and we can assume that masses are persistent for the life of the sim. @zepumph what do you think?

For https://github.com/phetsims/gravity-force-lab-basics/issues/156

**Comment by zepumph** [comment]
Good question. I do not think that anything in ISLC needs disposal.
