### ISSUE TITLE
Change to PDOM Order: Move Grab Ruler (ruler) to just before Rest All button.

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#158]
@zepumph, this change refers only to the PDOM order. There is no change the visual simulation.

**Reasoning:**
- Non-visual users get distance information directly from the position sliders (move m1, move m2).
- The ruler interaction is not important for non-visual access. We are placing it last in the Control Area to discourage its use by non-visual users.

If needed see [Heading Outline & Focus Order](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.gamh8gxjx7g5) in design doc.

**Comment by terracoda** [comment]
@zepumph this issue is dependent on decision in #156.

**Comment by terracoda** [comment]
@zepumph, in #156, @arouinfar and I agreed that providing quantitative distance was the best way to provide the distance value to non-visual users.

This means we should indeed change the focus order of the grab ruler button, so that it comes just before the Reset All button. The visual placement of the ruler does not move, just when the grab ruler/ruler receive focus.

This will means there is a smooth transition between interacting with the move sphere sliders and the mass changing sliders.

**Comment by zepumph** [comment]
This has been done above. The change pulled the visual scene graph order from the PDOM order, instead using accessibleOrder to set the PDOM order. This was important because the RulerNode is carefully layered in the sim to visually go  on top of the masses, but below all the controls. @terracoda please review.

**Comment by terracoda** [comment]
@zepumph, looks good. And I think it sounds good at the end because, it's almost like a reminder to go back and play with distance.

Closing.
