### ISSUE TITLE
Remove list structures around mass controls

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#161]
As we learned in Gravity Force Lab Basics, and possible also in Ohm's Law, the list structure seems to interfere with the slider role in some screen readers.

As a result we need to remove the list structure in GFL Regular as was done in Basics issue:
https://github.com/phetsims/gravity-force-lab-basics/issues/138

**Comment by zepumph** [comment]
This was done @terracoda. It was done generally so we shouldn't need to for Coulombs Law now. Closing
