### ISSUE TITLE
Consider an "a lot" parameter for when big changes occur

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#162]
For Gravity Force Lab Basics (GFLB) there was no indication from users that we needed to describe big changes like we do in Resistance in a Wire and Ohm's Law with the word "a lot".

I had a note in GFL's design doc that we might want to consider adding in "a lot" as a parameter, so I am creating an issue to record this thought and make a decision.

Here are a few cases where it might be helpful for users:
- Using Pg Up and Pg Dwn keys to make bigger distance steps (if force size changes are significant enough)
- Jumping to min and max position (if this jump results in a significant change to force)
- Jumping to min and max mass (this might always provide a significant change, except maybe if the spheres are really far apart?)
- Using Pg Up and Pg Dwn keys to make bigger changes to mass (if force size changes are significant enough)
- making fast changes with the keyboard, where the last alert might register a significant change to force.

**Comment by terracoda** [comment]
For this sim, if we consider "a lot", I think we also have to consider "a little".
I will be adding a few edge cases to this issue asap.

**Comment by terracoda** [comment]
**Example of a big change in distance with a very small change in force:**
<img width="907" alt="Screen Shot 2019-07-22 at 5 56 50 PM" src="https://user-images.githubusercontent.com/1902116/61646474-3f6c7100-acaa-11e9-80e7-68a06bde499c.png">
<img width="901" alt="Screen Shot 2019-07-22 at 5 57 23 PM" src="https://user-images.githubusercontent.com/1902116/61646486-48f5d900-acaa-11e9-80d9-eb0195d46b80.png">

**Example of a big change in mass with a very big change in force:**
<img width="841" alt="Screen Shot 2019-07-22 at 6 02 47 PM" src="https://user-images.githubusercontent.com/1902116/61646627-0b458000-acab-11e9-88f2-b7ef1f35b93a.png">
<img width="842" alt="Screen Shot 2019-07-22 at 6 03 12 PM" src="https://user-images.githubusercontent.com/1902116/61646630-0da7da00-acab-11e9-9a52-3cdfa99b5d71.png">

**Design Question:**
Do cases like this require special phrasing in the alert, for example:
- “Force vectors get {{a lot}} bigger, forces now {{force-value}} micronewtons.”
- “Force vectors get {{a little bit}} bigger, forces now {{force-value}} micronewtons.”
- “Force vectors get {{a lot}} smaller, forces now {{force-value}} micronewtons.”
- “Force vectors get {{a little bit}} smaller, forces now {{force-value}} micronewtons.”

**Comment by terracoda** [comment]
We did something similar in Resistance in Wire, but maybe it is not needed in this sim and maybe it is too complicated. 

It is a question I had from the beginning, but put it in hold, so just asking now because everything else is pretty much done and working well.

**Comment by terracoda** [comment]
I am going to rephrase the question...
@arouinfar or @emily-phet, do you have any concerns if we do not describe very big or very small changes such as the once above for this sim?

**Comment by arouinfar** [comment]
> @arouinfar or @emily-phet, do you have any concerns if we do not describe very big or very small changes such as the once above for this sim?

No, I don't think we necessarily need the {{a lot}}/{{a little}} descriptions, as there's quite a lot going on in the simulation. I'll defer to your judgement on this one @terracoda. If you'd like to try it out in interviews, that's also fine with me.

**Comment by terracoda** [comment]
@arouinfar, if understanding what makes really big and really small changes to the force is not a primary learning goal for the sim, I would avoid adding more length to the already verbose alerts.

If the most important learning goals are discovering that changes to mass and distance make the force bigger or smaller, I think we have a solid design as-is.

I am a little concerned about possible larger ranges which may be needed due to https://github.com/phetsims/inverse-square-law-common/issues/76, but I am happy with the way things are with the force context responses (i.e., changing force alerts).

I will close this issue and we can re-open if needed after  https://github.com/phetsims/inverse-square-law-common/issues/76 is addressed.
