### ISSUE TITLE
State of RegionMapper?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-force-lab#164]
I don't see any usages of RegionMapper and from documentation it looks like it may have been a prototype for creating a "map" for region to description. I am wondering if we should move this somewhere to investigate further or if this should be removed. But I don't know that we will be able to invest in this in the near future so I am not sure if an issue is worthwhile. @zepumph what do you think?

**Comment by jessegreenberg** [comment]
Found during https://github.com/phetsims/gravity-force-lab-basics/issues/156

**Comment by zepumph** [comment]
Thanks. I think this was some prototype that never took flight. Perhaps we will bring it back for the ruler, but for now I'll delete it for clarity.
