### ISSUE TITLE
Translations will lose some strings the next time this is published off of master

### ISSUE THREAD

**Issue by jbphet** [phetsims/gravity-force-lab#166]
In https://github.com/phetsims/inverse-square-law-common/issues/26, a number of strings were moved around between the Gravity Force Lab sims and the shared inverse-square-law repo.  While we had originally considered trying to move the translated strings too, it turned out to be too complex to make it worthwhile.  The consequence will be that the next time the Gravity Force Labs simulation is published off of master, some of the strings that were previously translated by the trusted translators will revert to English in the translated versions.  Therefore, **The next time this sim is published off of master, we need to notify translators that their translation needs to be updated.**

**Comment by zepumph** [comment]
This sim was just published off of master. @oliver-phet please notify translators that GFL 2.2.0 will have some strings that aren't translated that were translated in the previous version.

**Comment by oliver-phet** [comment]
Email to translator sent!
