### ISSUE TITLE
Adjusted wording for m1 and m2 dynamic states

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#168]
@arouinfar, based on some changes to descriptions that we made in GFL Basics, I have adjusted the phrasing in GFL Regular.

I made a table with a few examples of the two mass spheres (m1 and m2). These changes have not yet been implemented. The table is
[Table: Examples - Dynamic state descriptions m1 & m2](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.a317yjxc2ver)

**Could you review the table in the design document, and let me know if you have any concerns about the wording. My main concerns are:**
- Whether to use "force vector" or "force vector arrows" in first bullet, and
- Whether to use "force magnitude" or "force vector magnitude" in second bullet.

The cells that have a blue background are what is currently implemented, but keep in mind that the main changes are coming to bullet 3. Based on work in GFLB we dropped the idea of having a meter mark (position value) all together, and we found that comparative descriptions for mass were more helpful than actual size descriptions.

Let me know if you need more explanation of the provided examples.

**Comment by arouinfar** [comment]
>Force vector arrow is {{very small}}, and points directly at ‪{{m2}}‬.

I would say that "vector arrow" is redundant. GFL is designed for an older population than GFLB, and they are likely familiar with the concept of a vector. I would remove "arrow", and leave it at "Force vector".

> Force vector magnitude on m2 by m1 is {{0.041713}} micronewtons.

I think "Force magnitude" would be descriptive enough here, though I don't see any pedagogical issues with "Force vector magnitude" and wouldn't object to describing it this way. "Force magnitude" has the benefit of being a bit more succinct.

**Comment by terracoda** [comment]
@arouinfar, thanks, I have updated the design doc and will open a new issue for implementation.
