### ISSUE TITLE
Remove meter mark and adjust phrasing in Sphere descriptions

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#169]
Based on changes made in GFL Basics and decision in https://github.com/phetsims/gravity-force-lab/issues/168, I have some adjustments to the dynmaic state descriptions for the mass spheres in the Play Area.

Please see [Table: Examples - Dynamic state descriptions m1 & m2](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.a317yjxc2ver)

Here's the old and new example for **m1, Blue Sphere** with Force Values checked:
**m1, Blue Sphere (old)**
- Force on ‪m1‬ by ‪m2‬ is small, and vector points directly at ‪m2‬.
- Force vector magnitude is 0.166852  micronewtons.
- ‪m1‬ is very small at 100 kilograms and at 2.8 ‪meter‬ mark.

**m1, Blue Sphere (new)**
- Force vector is {{small}}, and points directly at ‪{{m2}}‬.
- Force magnitude on m2 by m1 is {{0.166852 }} micronewtons.
- ‪m1‬ is {{100}} kilograms, {{much much smaller than}} m2, and also {{4}} meters from ‪m2.

All other examples showing the different states depending on which checkboxes are checked are in the design doc in [Table: Examples - Dynamic state descriptions m1 & m2](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.a317yjxc2ver).

**Edits**
- Sept 24, 2019 - Changed values to reflect new values on page load!

**Comment by terracoda** [comment]
@zepumph, this might be a repeat issue of https://github.com/phetsims/gravity-force-lab/issues/160#issue-461989393 (apologies)

**Comment by zepumph** [comment]
Before I start this work, here is a snippet of GFLB, so I can regression test:

![Uploading image.png…]()

**Comment by zepumph** [comment]
This has been implemented. @terracoda please review. Specifically please focus on the following items

* Please check that the two object labels (like on m1 by m2) is correct and not backwards
* Make sure that they update to changes in the sim as expected (especially the control panel checkboxes)


Thanks!

**Comment by terracoda** [comment]
Looks good @zepumph! Closing!
