### ISSUE TITLE
No accessibleName for mass controls

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab#171]
Discovered while working on #161. We are passing an accessibleName into the NumberControl's slider, but for some reason it isn't working.

**Comment by zepumph** [comment]
The reason is that `accessibleName` when passed to `sliderOptions` isn't currently doing anything. I created https://github.com/phetsims/scenery-phet/issues/519 and will get back to this after a decision is made over there.

**Comment by zepumph** [comment]
https://github.com/phetsims/scenery-phet/issues/452 has solved this issue. We now have an accessible name. Closing.

**Comment by terracoda** [comment]
I hear the name for the each mass control and the group. The group is only announced once upon entering the group. It sounds great to me.
