### ISSUE TITLE
Should there be boundary sounds for spin buttons, similar to mass location sliders?

### ISSUE THREAD

**Issue by emily-phet** [phetsims/gravity-force-lab#177]
@terracoda brought up (from consultant discussion) that the spin buttons don't have a boundary sound, but the mass location sliders do. 

@Ashton-Morris suggested a solution (having a gentle 'error' sound if spin  buttons are pressed while inactive).

I think there is a deeper issue at play here - where visually the grab/drag of the mass objects and the press of the number spinner feel very different, but are actually very similar from the perspective of alternative input. This issue will come up across other sims...so I would prefer to hold off on digging deeply on this issue for this sim, and instead tackle it the next time we encounter it.

**Comment by zepumph** [comment]
I moved it over to GFL.

**Comment by zepumph** [comment]
@emily-phet now that we are working more on this sim. How would you like to proceed with this issue?

**Comment by emily-phet** [comment]
@zepumph I think we've missed the moment for thoughtful exploration here - momentum is building towards wrapping up on the sound side. Pick up/Drop sounds are being added to the ruler, and I think (with the holiday's fast approaching) there isn't time to implement/iterate on this before end of quarter. I think we'll need to punt on this one, and take up the issue of consistent boundary sounds across 'slider' and 'slider-like' interactions in a future sim.

**Comment by zepumph** [comment]
Alright, sounds good. I'm going to close this issue then, please reopen if you disagree.
