### ISSUE TITLE
No "closest" region name when spheres are the closest they can be.

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#178]
As mentioned in https://github.com/phetsims/gravity-force-lab-basics/issues/173#issuecomment-534320591, let's look at re-implementing the region names to make sure the described position ranges are correct in this sim, too. "Closest" is a single-value region like "Farthest from".

I'll check the design doc for GFL regular, too, to see what's there.

**Comment by zepumph** [comment]
@terracoda and I noticed this too. I think we can try to figure that out now. It may be because #173 where we increased the min mass value on the NumberControls. I'll take a look

**Comment by zepumph** [comment]
I'll take a look at the table regions in the design doc too to see how things have changed.

**Comment by zepumph** [comment]
The current values in the design doc are what are in the sim. The issue is that when we increased the min mass to 10kg from 1, we changed the min distance, and left the position regions stale. Now the min distance for the sim is 

Note that this directly relates to https://github.com/phetsims/a11y-research/issues/146, since changing the range in https://github.com/phetsims/gravity-force-lab/issues/173 left the hard coded regions in the position describers in the dust. That said, this doesn't need to be fixed in GFLB. 


For this issue, @terracoda please update the design document with a min of .6, and we will meet up over in https://github.com/phetsims/a11y-research/issues/146 to decide on a general solution for this issue.

**Comment by terracoda** [comment]
@zepumph, I updated the [Table for the size of the force vectors and the effort of the robots](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.dd0bg8o9mrz8)

Size Force Vectors (force) | New Ranges (micronewtons) | Effort of Robots(counter force)
-- | -- | --
tiny | 0.000 072 - 0.166851 | pull very little
very small | 0.166852 - 2.206306 | pull a little
small | 2.206307 - 4.412614 | pull lightly
medium size | 4.412615 - 8.687336 | pull gently
large | 8.687337 - 19.856767 | pull moderately
very large | 19.856768 - 35.300919 | pull hard
huge | 35.300920 - 55.157686 | pull very hard

I think I may still need to look at the regions table describing the actual distances.

**Comment by terracoda** [comment]
@zepumph here's the adjusted regions, but keep in mind in this sims  we don't rely on the region ranges for delivery a qualitatively described experience. We only use the quantitative distance value in this sim. The region names are only needed in some context responses.

Farthest from | Extremely from  | Very far from  | Far from | Not so close to  | Close to  | Very close to | Extremely close to  | Closest to 
-- | -- | -- | -- | -- | -- | -- | -- | --
9.6 | 9.5 - 8.6 (0.9 m) | 8.5 - 7.6 (0.9 m) | 7.5 - 5.6 (0.9 m) | 4.5 - 3.6 (0.9 m) | 3.5 - 2.6 (0.9 m) | 2.5 - 1.6 (0.9 m) | 1.5 - 0.7 (0.8 m) | 0.6

Please see design doc for more details on how the region names are not used as much in this sim. This is because there is no Distance checkbox. We use the quantitative values as the default object responses for this sim. In the BASICS sims there are 2 distinct experiences: one qualitative and the other quantitative.

**Comment by zepumph** [comment]
I updated the tables. I'm going to go ahead and close this issue, and keep going in https://github.com/phetsims/a11y-research/issues/146 for a general solution to hard coded tables.

**Comment by zepumph** [comment]
@terracoda said over in https://github.com/phetsims/a11y-research/issues/146#issuecomment-559805532:

>@zepumph, just a note that I still don't hear "closest" when the mass spheres are closest see closed issue phetsims/gravity-force-lab#178

Reopening :)

**Comment by zepumph** [comment]
@terracoda can you please state the platform device screen reader that you are not hearing the "closest" alert for.

**Comment by terracoda** [comment]
Apoloigies @zepumph, this is indeed fixed. It's possible, I only checked with Constant Size checked and not with the m1 and m2 2 set to their smallest size and closest.

I hear "closest" when the masses are 0.6 meters apart.

Closing.
