### ISSUE TITLE
QA Credits

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab#180]
When the time comes, it is here.

**Comment by terracoda** [comment]
@zepumph , and A11y Team credits are mentioned in the issue #109

**Comment by zepumph** [comment]
@terracoda those were implemented above, now all that is left is QA credits.

**Comment by terracoda** [comment]
@zepumph, in the Team list, I think the names are supposed to alphabetical, which would put Amy Rouinfar before my name. 

When you change, please make sure my name doesn't get split on a wrapped line (thanks).

**Comment by terracoda** [comment]
Not sure if we have any general preferences for not splitting names, I see Amy's and Brian's names are split.

**Comment by zepumph** [comment]
In general it just splits on any space. Do you want me to make an issue to discuss only splitting on full names?

**Comment by terracoda** [comment]
Yes, I think it would be nice to not split the names, if it is straightforward.

**Comment by zepumph** [comment]
> if it is straightforward.

I poked around in RichText, and I'm sorry to say it didn't look easy or straightforward at all. I created https://github.com/phetsims/joist/issues/598 to make sure, but I don't think that we will end up changing anything (sorry!). 

Over to @KatieWoe since the sim is now in RC.

**Comment by KatieWoe** [comment]
New credits for rc.1:
Jaspe Arias, Logan Bray, Liam Mulhall, Kathryn Woessner

**Comment by zepumph** [comment]
I didn't get any updates through rc.2-4 so I'm going to assume that these are good to go. Thanks! Closing!
