### ISSUE TITLE
Fix vertical ruler regions

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab#185]
The first pass at implementation was done in https://github.com/phetsims/gravity-force-lab/issues/141, but they still need to be tweaked. First I will create a visual way to display them.

**Comment by zepumph** [comment]
@terracoda, these vertical regions for the ruler are ready for review now. The best way to test is by adding the `showRulerRegions` query parameter. This will do a few things:

* Add horizontal lines at the boundaries
* add crosshairs on the ruler so you can see the point that is being tested
* prints the region names to the console, so you can see them in the developer tools.

Let me know what you think!

**Comment by terracoda** [comment]
The vertical ruler regions look great @zepumph!

**Comment by terracoda** [comment]
Can we close this issue?
