### ISSUE TITLE
Two hotkey presses needed after J+H hotkey

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab#186]
From https://github.com/phetsims/gravity-force-lab/issues/141, and https://github.com/phetsims/gravity-force-lab/issues/138.

The bug is outlined in https://github.com/phetsims/gravity-force-lab/issues/138#issuecomment-549501889:

>@terracoda noticed that sometimes you have to press the hot keys more than once to get them to fire. For example in the following sequence, I reliably needed to press "J + C" twice, only the second time did it move:

>J+C
J+C
J+H
Enter (to grab again)

**Comment by zepumph** [comment]
After investigation with @jessegreenberg, we found that this had to do with how the J+H hotkey was calling "releaseDraggable" but needed to interrupt the `KeyboardDragListener` as a part of that. Furthermore, we were resetting the timer after the hotkey callback, so even though the interrupt was working as expecting and resetting the timer back to the threshold value (to fire immediately after next hotkey press), the timer/counter was then put back to zero afterwards. 

On top of this, I added to this issue a few documentation, refactors, and renames. @jessegreenberg, though we worked on most of these, will you look through and see what you think?

**Comment by terracoda** [comment]
Seems like it is fixed to me. Thanks @zepumph.

**Comment by jessegreenberg** [comment]
Reviewed the above commits and everything looks like a nice improvement, thanks @zepumph.

**Comment by zepumph** [comment]
Thanks!
