### ISSUE TITLE
Possible to grab two things with one finger

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab#191]
**Test device**
Dell or iPad
**Operating System**
Win 10 or iOS 12
**Browser**
Chrome or Safari
**Problem description**
For https://github.com/phetsims/QA/issues/455. Not in published version.
When dragging around the ruler using touch, passing over a robot will pick it up as well. This can be disruptive to user experience.
**Steps to reproduce**
1. Use touch to grab the ruler (twice to avoid https://github.com/phetsims/gravity-force-lab/issues/189)
2. Drag it over the robots a few times

**Visuals**
![multigrab](https://user-images.githubusercontent.com/41024075/68436721-046c4b80-017c-11ea-8d22-bad86d7096f7.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity Force Lab‬
URL: https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-dev.16/phet/gravity-force-lab_all_phet.html
Version: 2.2.0-dev.16 2019-11-06 21:45:42 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by zepumph** [comment]
Tagging @arouinfar, the ISLCObjectNode has a DragListener on it that is set to allow touch snag. This is a byproduct of this. I am not familiar with why `allowTouchSnag: true` was set for the pullers/masses. Is this desired behavior? Please note that this will effect GFL(B) and coulombs law.

**Comment by zepumph** [comment]
Oh wait, perhaps this isn't right. It may be possible for a listener to "box out" any other listeners from accessing the current pointer. If so, is that what you want?

**Comment by zepumph** [comment]
Please ignore the above commits, they were meant for https://github.com/phetsims/gravity-force-lab/issues/172

**Comment by arouinfar** [comment]
@zepumph I don't think touchSnag is necessary in this sim or GFLB because the masses are quite large. However, it would be nice to keep in Coulomb's Law because the charges are quite small on the Atomic Scale screen.

> It may be possible for a listener to "box out" any other listeners from accessing the current pointer. If so, is that what you want?

It sounds like this would effectively disable touchSnag on the masses while the ruler is being dragged. If so, I think it'd be worth trying out @zepumph.

**Comment by zepumph** [comment]
This issue could be solved by just adding the "attach: true" flag to the `MovableDragHandler`, but I figured that this was a good reason to convert to the more modern `DragListener`, which attaches to the pointer by default.

The only issue about the current strategy is that this conversion suffers from https://github.com/phetsims/scenery/issues/1014, and as a result, I had to turn off the "applyOffset" option. So currently the ruler center jumps to the pointer location. This should only be temporary though. @KatieWoe can you confirm that this is issue is fixed on master?

**Comment by zepumph** [comment]
I'm going to add "blocks-sim-publication here until https://github.com/phetsims/scenery/issues/1014 is fixed, if it will take a while, then perhaps I will create another issue to solve it.

**Comment by KatieWoe** [comment]
Looks good on master.

**Comment by zepumph** [comment]
This has been fixed by https://github.com/phetsims/scenery/issues/1014. The offset is being recognized now. Closing.
