### ISSUE TITLE
Publish a PhET-iO version

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab#193]
We have heard back from a client, and are ready to publish this sim for PhET-iO. @kathy-phet, could this be wrapped into the accessibility publication coming up? The goal is to have that published by December 14th. Does that seem acceptable for this?

**Comment by kathy-phet** [comment]
That seems fine. I don't think the client needs it any earlier.

**Comment by zepumph** [comment]
Sounds good. The plan will be to publish the next GFL with phet and phet-io brands. Closing
