### ISSUE TITLE
Gesture support: ruler can get stuck behind mass controls

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab#195]
Since the way we setup the mobile gesture VO interaction forwards the PDOM activation to a touch event directly to the scenery Node, it is possible that, when the ruler is behind the mass controls, that that touch event get's blocked by a mass control. I am not sure of an easy solution here, as I don't think we are going to change the underlying interaction (forwarding to a touch event at the center of the ruler). Here are a list of possible things to think about:

* Having the ruler go on top of the controls
* changing the bounds of the ruler so that it can't get hidden behind the mass controls (see https://github.com/phetsims/gravity-force-lab/issues/104)
* Maybe some sort of shortcut to "return" the ruler when it get's stuck (I don't like this one).

**Comment by zepumph** [comment]
I think that my preferred solution would  be to change the available drag bounds, see  https://github.com/phetsims/gravity-force-lab/issues/104#issuecomment-552594729 for comment and I'll see over there for further discussion.

**Comment by terracoda** [comment]
@zepumph, I agree, just limiting how far down the ruler can go seems simple. It is not useful for it to go behind the mass controls.

I think we already tried the ruler (visually anyways) on top of the controls. It can actually get in the way of the more primary interactive elements there, so I agree, I think it's better to limits range so it does go under the mass controls.

**Comment by zepumph** [comment]
Because of commits over in https://github.com/phetsims/gravity-force-lab/issues/104, this should be fixed now. It is out for review, but it would be good to confirm that this is fixed. Assigning to @terracoda to see if she can report this as fixed.

**Comment by zepumph** [comment]
This has been fixed by https://github.com/phetsims/gravity-force-lab/issues/104, as soon as @terracoda confirms, this issue can be closed.

**Comment by terracoda** [comment]
@zepumph, yes, the dragging movement no longer allows moving the ruler deep under the mass controls.

Still having other issues, but the dragging bounds seem to be nice.

**Comment by terracoda** [comment]
Closing.
