### ISSUE TITLE
Gesture support: Pink highlight appears often and is hard to remove

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab#197]
From https://github.com/phetsims/gravity-force-lab/issues/140#issuecomment-552534326. Since mobile devices and iOS Voice Over don't rely on focus, it seems a bit buggy to get focus highlights in these cases. Especially since for the grab/drag interaction, the focus highlight include the "space to grab" panel.

I wonder if there are any spots in GrabDragInteraction where we are accidentally focusing something, and we need to guard around that if we are supporting gesture a11y. I'll take a look. Also tagging @jessegreenberg because I don't have an iOS device.

**Comment by terracoda** [comment]
Just an FYI, when I move VO's focus to a slider and then double tap, I activate the pink focus highlight. This does not happen if VO is turned off and I double tap with regular touch.

**Comment by zepumph** [comment]
I can also reproduce this. It is less than ideal. I can also tell that in some cases it seems like it is demonstrating some buggy cases, like when trying to move the ruler, focus highlight has appeared on other controls. I will try to reproduce and report back.

**Comment by zepumph** [comment]
This seems to be because navigating with the virtual cursor does not change focus, and iPad safari VO doesn't give focus events, but _activation_ does, so activating an item will cause the focus highlight to show up. There isn't an obvious way to remove that highlight. 

>I wonder if there are any spots in GrabDragInteraction where we are accidentally focusing something, and we need to guard around that if we are supporting gesture a11y. I'll take a look. 

I looked in GrabDragInteraction, and the only call to `Node.focus()` was already guarded. Again I think it is just the activation of the item (like the ruler).

I see three ways to proceed.

1. We could just ignore it, and perhaps convince ourselves that visual mobile VO users are few and far between. In my experience it doesn't effect the way that non visual users interface with interactive descriptions.
2. I could try to investigate and prototype more places to guard the code (not sure what this would yield.
3. We determine that this is unacceptable, and in this case I think we should have a brainstorming meeting to try to come up with potential solutions for it. 

I think that I prefer option (1), @terracoda what do you think?

**Comment by terracoda** [comment]
@zepumph, I am inclined to go with option 1, too. The sim is working really well on mobile now. The pink highlight is not showing up as often as before. It is indeed, disappearing when focus moves.

The pink highlights do not interfere with interaction currently, and they certainly won't get in the way of the majority of VO users who likely will not notice them at all.

**Comment by terracoda** [comment]
I think until know more from collaborative situations in diverse classrooms we might not want to worry about this issue, and just know we might to address in the future.

**Comment by terracoda** [comment]
Is this safe to close @zepumph?
