### ISSUE TITLE
ChromeOS unable to record phet-io

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab#199]
For https://github.com/phetsims/QA/issues/455
For ChromeOS, when using the record wrapper, typing window.saveLogToFile gives the error
```
Uncaught TypeError: window.saveLogToFile is not a function
at <anonymous> 1:8
```

**Comment by KatieWoe** [comment]
Same seems to happen on Safari on MacOS 10.15

**Comment by KatieWoe** [comment]
Wait

**Comment by KatieWoe** [comment]
The cause for this problem was that the console must be open before the page loads for the recording session to work.  Feel free to close.

**Comment by lmulhall-phet** [comment]
Added to QA Book. See https://github.com/phetsims/QA/blob/master/doc/qa-book.md#events-recording-wrapper-test.
