### ISSUE TITLE
PDOM order change: Considering putting Measure Distance Ruler in Play Area 

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#204]
@zepumph, how difficult is it to change the focus order of the Ruler and it's help text?

Once we changed the "Grab Ruler" to a "Measure Distance Ruler" button,  it seemed it might be safe to have it back in the Play Area in its original position.

@zepumph, is something that is not so difficult to do, or is it quite involved?
I am a little worried about moving it since things are not yet working for gesture yet, and also a little curious if moving it would make the moving through the PDOM with gestures easier.

Please let me know the scope of changing the PDOM order of the Ruler.

**Comment by zepumph** [comment]
This would be an easy change, just involving some rearranging in the screen view file. Let me know if you would like me to implement this.

**Comment by terracoda** [comment]
Ok, good to know. No action required yet. I want to be sure before we move it up higher in the Tab order.

**Comment by terracoda** [comment]
@zepumph, I am just commenting that if all goes well in #215 and #216, I think it would be nice to move the Measure Distance Ruler into the Play Area.

**Comment by terracoda** [comment]
@zepumph, once #215 and #216 are implemented, I think it is safe to move the Measure Distance Ruler to come after the Mass Controls, ensuring it is not inside any grouping related to the Mass Controls, and before the Control Area.

Once it is moved, I we will need to update the screen summary. I'll make a new issue for that.

**Comment by zepumph** [comment]
@terracoda, this was implemented above, please review.

**Comment by terracoda** [comment]
Verified. Thanks!
