### ISSUE TITLE
Keyboard Interaction: Measure Distance Ruler - Combining Release and Grab strings

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#205]
In https://github.com/phetsims/gravity-force-lab/issues/141 the Grab alert was corrected.

However, recent changes seem to have combined "Released" and "Grabbed" strings into the grab response.

![Screen Shot 2019-11-19 at 9 18 51 PM](https://user-images.githubusercontent.com/1902116/69201693-c0812b00-0b19-11ea-9675-6828a619e380.png)

@zepumph, could you have a look. It might just be a copy/paste error.

**Comment by terracoda** [comment]
And "Released" is said twice on an actual release, so maybe these extra "Release" strings are creeping in from the gesture implementation?

![Screen Shot 2019-11-19 at 10 17 56 PM](https://user-images.githubusercontent.com/1902116/69201957-a3009100-0b1a-11ea-956b-aa63bdea1533.png)

**Comment by terracoda** [comment]
@zepumph, actually, I think the double "Release" was just a timing glitch. I think only one "Release" is being spoken on the actual release interaction, and there is an erroneous "Release" string being added to the grab interaction response.

**Comment by zepumph** [comment]
I think that https://github.com/phetsims/gravity-force-lab/issues/203#issuecomment-556127803 actually applies to this issue:

>@jessegreenberg I think this is because we added the down/up listeners, but we are also handling the gesture case on the PDOM side. Likely we want to just have this handled by the general presslistener that we added recently. I'll implement

**Comment by zepumph** [comment]
Yes I get this sometimes. It is not because of any of the alerts. I think it has to do with the kinks we are still working out in successfully grabbing/releasing the ruler each time the user intends to. (like #201 and #210). I would like to try to sort out at least #210 and then see if this sounds any better.

I was having trouble when it felt like I wasn't able to grab it successfully each time, and then after trying a few times I was then able to grab it (if that sounds confusing it is because I'm confused). I'll look in on this after #210.

**Comment by terracoda** [comment]
@zepumph, I seem to get "Release." on grab, and "Grabbed." on release in addition to the correct strings. 

It seems it could be related to yours and @jessegreenberg comment in https://github.com/phetsims/gravity-force-lab/issues/205#issuecomment-556147062

Goof luck.
K+Just an FYI, still happening on [2.2.0-dev.21](https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-dev.21/phet/gravity-force-lab_all_phet.html)

**Comment by zepumph** [comment]
@terracoda are you still getting this bug? I know @jessegreenberg has done a lot of work on the grab/drag interaction in the last month.

**Comment by terracoda** [comment]
Good question, I'll check.
In latest dev version 2.2.0-dev.23[2.2.0-dev.23](https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-dev.23/phet/gravity-force-lab_all_phet.html)

I am getting correct "Grabbed" and "Released." and the right correct times!
I checked Mac OS High Sierra and iOS 13.3

I am closing this issues.
Thanks for checking @zepumph !
