### ISSUE TITLE
Scientific Notation checkable when Forces Values is not checked

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#207]
I thought we solved this issue already, however, I can't find the original issue.
**Issue:** I can check Scientific Notation checkbox when Force Values is not checked. This should not be possible because no force values are showing.

I am pretty sure there is artwork demonstrating these the greyed-out sates.
- Scientific Notation checkbox should be greyed-out AND disabled in the PDOM when Force Values is not checked. 
- And, if Scientific Notation is checked when Force Values gets unchecked, the Scientific Notation checkbox should get greyed-out and disabled in its checked state. 

![Screen Shot 2019-11-20 at 10 38 08 AM](https://user-images.githubusercontent.com/1902116/69246111-a9c2ee80-0b82-11ea-8ba0-39f94a3f9ae9.png)

**Comment by zepumph** [comment]
@terracoda this was actually a purposeful design decision implemented for PhET-iO. The reasoning is because it makes for an easier api for customization. Can you outline the reasoning for wanting this for Interactive Descriptions. Perhaps we will need to rope in @arouinfar and @kathy-phet to this issue too for comment.

**Comment by terracoda** [comment]
@zepumph, interesting about changing to simplify for PhET-iO. I understand the challenge.

However, @arouinfar and I had already discussed this at the beginning of the design process, and thougtht that we came up with a nice solution. I wish I had been looped in for the PhET-iO meeting ;-)

Our reasoning (from memory), essentially, it makes no sense to be able to turn on Scientific Notation if the Forces Values checkbox is not already checked. Scientific Notation is a second numerical representation of the Force Values. If Force Values are not shown (or described) then what does it mean to be able to turn on Scientific Notation - nothing. There is no numerical representation to convert to scientific notation - nothing happens visually when I check the Scientific Notation checkbox when Force Values is not checked.

The only thing that happens is that a context response fires saying "Forces now shown in newtons with Scientific Notation" - but that's not true!

@arouinfar, are you aware of this change?

**Comment by terracoda** [comment]
@arouinfar, when you get a chance please share your thoughts. Let me know if think this warrants some time in a design meeting soon.

**Comment by arouinfar** [comment]
Unfortunately, I think I was the only one present for both the PhET-iO and a11y conversations around this particular issue, and they were separated enough in time that I wasn't thinking about both. My apologies.

In general, I think disabling the checkbox is the cleaner option. However, we were willing to accept the slightly odd UX of not disabling the checkbox for the simplification of the api for PhET-iO, but this seems extremely problematic for the PDOM. I cannot remember if disabling the checkbox was slightly inconvenient/messy for PhET-iO or truly problematic in the same way the reverse is true for the PDOM. @zepumph can you comment on this (or point us to the appropriate issue)?

**Comment by kathy-phet** [comment]
I think it was problematic for PhET-iO - at least given the structure of the code at the time. I think it would be best to just schedule a short design meeting with @terracoda and @zepumph to see what options we can come up with for solving the puzzle.

**Comment by terracoda** [comment]
It is also a relatively awkward and tricky issue for the PDOM, so thankful for the design time.

**Comment by zepumph** [comment]
I too will be happy for design time. 

To try to summarize, it seems challenging for the PDOM because we have an alert when the scientific checkbox is toggled that states that the force vectors are now displayed in a different way. This is confusing if there aren't even any force vectors displayed.

It was problematic for PhET-iO because the "enabledProperty" for the scientific notation checkbox was the Property that controlled the force values checkbox. Because of the way this was set up. There was no way to set the scientific notation checkbox to enabled:false through the PhET-iO api without the user just able to toggle it back to enabled by clicking on the force values checkbox again.

---------------------

I think that the solution is to revert to the previous solution, where the scientific notation box toggles enabled, and add a Property only accessible via PhET-iO called `scientificNotationCheckboxEnabledOverrideProperty` or something like that, which can override the current enabled of the checkbox and will always be correct when set through the PhET-iO api. The reason why we didn't do this before was that it was added complexity that didn't seem warranted. It now definitely seems warranted to me. If I have time I can hack our a prototype to play around with before the design meeting.

**Comment by zepumph** [comment]
Today in design meeting we thought about how these two checkboxes are actual representing 3 states. What if we used a radio button group instead?

* "Show Values"
* "Scientific Notation"
* "Hidden"

This will solve PhET-iO because then we won't have dependent Property values. For

@arouinfar will do a mockup and get back to me for implementation.

**Comment by terracoda** [comment]
I drafted some descriptions changes in a table here:
https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.m011037v6ep4

**Comment by zepumph** [comment]
Oops. I assigned @terracoda without seeing the above comment because the descriptions will also need work. Please unassign if you feel like they are ready.

**Comment by arouinfar** [comment]
Post-meeting slack conversation:

> Taliesin Smith 3:10 PM
Sadly, in the design meeting I did not mention the help text that accompanies each checkbox. The help text is what creates the context for the checkboxes before interaction takes place and thent eh responses confirm the change in context. So ultimately, there is a shared responsibility of the words in the label, the checked/not checked state, the words in help text, and the words in the response (alert) once the control is toggled. I am sorry I did not communicate that fully in the meeting. I was unprepared for discussing a entirely new design - my fault. (edited) 
>
>That said, the radiobuttons are an interesting solution, but the overall experience is quite different. The radiobutton group will have one help text for the group. And again, I apologize for not making the differences more clear during the meeting - the differences in the interaction and the associated descriptions they entail.
>
>Michael Kauzmann 3:16 PM
Could a single new help text for the radio button group be something like "Explore the force with different values."
>
>Taliesin Smith 3:16 PM
The values are the same, the representations are different.
>
>I mocked up a table in the design doc. There are 2 tables people can look at to compare here https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.m011037v6ep4
>
>The tables have all the descriptions so people may be able to see the full context which I did not explain. The radiobuttons could be a good solution, but I was just having a feeling like, "If it ain't broke, why fix it with radiobuttons?" And it is broken for phet-io, so maybe we do need to fix it with radiobuttons :slightly_smiling_face: No users had any trouble with the GFL checkboxes as they were designed.
>
>Looking forward to comments.
>
>Kathy Perkins 3:39 PM
It has an alternative "fix" for PhET-iO - so alternatively we could do that instead for this sim - and then avoid this type of design in the future.

**Comment by terracoda** [comment]
Thanks @arouinfar for bring the slack comments here. I'll add that I am not opposed to trying out the radio button group. I was just concerned that I had not fully communicated how different these 2 intersections are from the non-visual perspective.

Onward and upward. Looking forward to seeing @arouinfar 's visual mock-up.

**Comment by terracoda** [comment]
Changing the interaction to radiobuttons will require a change to the screen summary in #218.

**Comment by arouinfar** [comment]
I've mocked up a few options with the radio button group. It seems that "decimal notation" or "decimal form" is the proper term for non-scientific notation (e.g. http://www.corestandards.org/Math/Content/8/EE/A/4/). In the meeting we had mentioned "standard" as an option, but in UK English "standard form" means scientific notation.

![Screen Shot 2019-12-10 at 4 25 22 PM](https://user-images.githubusercontent.com/8419308/70578029-cfcc2500-1b69-11ea-9513-5920383e6eb3.png)
![Screen Shot 2019-12-10 at 4 25 37 PM](https://user-images.githubusercontent.com/8419308/70578028-cfcc2500-1b69-11ea-8dbe-9633594bbf94.png)

@ariel-phet had mentioned moving the Constant Size checkbox outside of the panels somewhere. I mocked up a few options, but I'm not particularly keen on these layouts. Depending on where the checkbox is moved, we might also need to adjust the focus order/PDOM.
![Screen Shot 2019-12-10 at 4 26 04 PM](https://user-images.githubusercontent.com/8419308/70578026-cfcc2500-1b69-11ea-84d0-97dd6633f09f.png)
![Screen Shot 2019-12-10 at 4 25 49 PM](https://user-images.githubusercontent.com/8419308/70578027-cfcc2500-1b69-11ea-9fdf-836a51a18c37.png)

Thoughts @ariel-phet @kathy-phet @terracoda?

**Comment by zepumph** [comment]
I really like the first mockup myself, and I definitely think we have the horizontal real estate to move the panel to the left of the reset all button.

**Comment by terracoda** [comment]
I agree with @zepumph, I like the first one. They are all part of the Control Area under the hood.

**Comment by kathy-phet** [comment]
I'm hesitant to use "None" because it has the slight tendency to be interpreted as I'm setting forces to None - no forces. I prefer Hidden I think, although I would like a better word.

**Comment by terracoda** [comment]
@kathy-phet, do you like any of:
 -   "Notation hidden"
 -   "No Notation"
 -   "No Force Values"

Instead of "None" or "Hidden" alone?

**Comment by arouinfar** [comment]
Thanks for the feedback everyone! It looks like we generally prefer the first mockup, which is most similar to the current layout.

@terracoda thanks for all of the suggestions. Like @kathy-phet, I think "Hidden" could work well here. It's succinct but still descriptive especially when considered with the radio group title -- force values hidden. If we want to re-word things slightly in the context response, "no force values shown" or "force values not shown" could work well.

I don't think "notation" fits in with the hidden option. What we're doing here is suppressing the force value, while "notation" is really just a way of displaying the value.

**Comment by terracoda** [comment]
@arouinfar and @kathy-phet I am happy to go with "Hidden" alone as the label for the third radiobutton.

Having the words "force values" in the context responses should make things clear to non-visual learners even if they do not hear "Force Values" automatically upon entering the group.

Depending on screen reader software and exact implementation "Force Values" may not be read out automatically. It is, however, always readily available and easily accessed on-demand by the learner should they need clarification of what the list of radiobuttons is for. 

So I think this is the final accessible content for the new interaction:

**H3: Force Values**
Help text: Choose force value representation.
-   Decimal Notation => Force values in micronewtons.
-   Scientific Notation => Force values in newtons with scientific notation.
-   Hidden => No force values shown.

@arouinfar, do you need to do a final visual mock-up?

**Comment by arouinfar** [comment]
That all sounds reasonable to me @terracoda. Here's an updated mockup.

![image](https://user-images.githubusercontent.com/8419308/70642764-0c952c00-1bfd-11ea-8038-7ef91f7d940a.png)

**Comment by terracoda** [comment]
@zepumph, I have updated the design document in two paces:
- See [Control Area](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit?ts=5df02ff8#heading=h.c2xdgysm2bnw) in State Descriptions section
- The context responses for the radiobuttons are in [Table: Radio Button Group for Force Values](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit?ts=5df02ff8#heading=h.vud7dkr0440x)

Everything should also be here in this issue as well when you are ready to implement.

**Comment by ariel-phet** [comment]
This all seems lice a nice direction to me, and I like the layout of the panel

My only suggestions is we might want to tweak the default state of the sim so that the masses are initially reasonably over their respective slider controls, but I am not sure if that is necessary or not (since there are not many controls in the sim).

**Comment by zepumph** [comment]
I did much of this today, though there is still a fair bit of work to be done. The visual and accessibility logic should be correct, and can be tested. I would love to hear what @terracoda and @arouinfar think. 

There is still refactoring to be done.  Here is some of the improvements I should still do (mostly notes to myself save the first bullet).

* The control panel for Coulombs law is basically the same thing. We should factor out the radio buttons to be used to that sim too.
* I converted scientific notation logic to be based on the new enumeration Property in gravity-force-lab, but there is still a lot of logic based on the more common "showValuesProperty" (used in all three sims), and I'm unsure how much to refactor that. For now I am just keeping that boolean Property in sync based on the forceValuesDisplayProperty.
* fix `getCheckboxTextOptions`, as this is not a great way of refactoring the font/style of the UI text.
* Is ISLCPanel needed?

I'll keep myself assigned, and add @terracoda and @arouinfar

**Comment by terracoda** [comment]
@terracoda reviewed. 
@terracoda asked @zepumph to add "Force" to the beginning of the "Notation" radiobutton responses. Now all the responses say "Force values" like this:
- Force values in micronewtons.
- Force values in newtons with scientific notation.
- Force values hidden.

@terracoda will open or re-open an issue in a11y-research to explore design options for accessible radio group code. For example, named groups of radio buttons with or without an un-ordered list might be more desirable in some sims.

For this sim (GFL) we went with an adjustment to the response strings rather than a change to the parent structure housing the radio buttons.

**Comment by terracoda** [comment]
@arouinfar, over to you for review.

**Comment by arouinfar** [comment]
@zepumph this all seems to be in working order, though I do have a few pixelpolishing requests.
- [ ] The stroke around the Force Values panels looks a bit heavy, can you match the stroke weight used on the Mass panels?
- [ ] The checkbox next to Constant Size is huge. Can you reduce its dimensions so the height is similar to the leading character of the string?
- [ ] The panel (or strings?) need an appropriate maxWidth, the sim currently fails `stringTest=long`. Let's allow the panel to expand up to 50px before scaling down the strings.
- [ ] In https://github.com/phetsims/gravity-force-lab/issues/207#issuecomment-566349000 @ariel-phet suggested shifting the starting locations of the masses. Currently they are aligned to the 3 m & 7 m marks on the ruler. For better alignment with the Mass panels, let's shift everything left 1 m, with the starting positions at 2 m and 6 m.

**Comment by zepumph** [comment]
>The stroke around the Force Values panels looks a bit heavy, can you match the stroke weight used on the Mass panels?

What was happening here is that actually the mass controls are being scaled down. I changed it so none of the panel strokes were scaled, ergo I made them all heavy but consistent. This felt like a better change than trying to map it the other way. If you think it is too heavy, then we can change all of the line widths. 

>@ariel-phet suggested shifting the starting locations of the masses. Currently they are aligned to the 3 m & 7 m marks on the ruler. For better alignment with the Mass panels, let's shift everything left 1 m, with the starting positions at 2 m and 6 m.

@terracoda does this sound like an appropriate change in terms of interactive description content? I can't think of any issues with it.

**Comment by terracoda** [comment]
@zepumph, thanks for asking. 
I do not see any issues with it. 

- Force arrows and distance are still the same. 
- m1 will have a  little less initial wiggle room, but that is the same for both visual and non-visual experiences.
- m2 will be 2 steps closer to crossing to the left side of the track and m1 will be two steps farther from crossing to the right side of the track.

I don't think any of this has any pedagogical ramifications.

**Comment by zepumph** [comment]
I did a bunch more work here. Please review the following changes:
* I implemented all of the checkboxes @arouinfar recommended
* I made this same change to Coulombs Law, since it has the same issue.
* I refactored the checkbox group into GFLB since BASICS is the only sim that uses it now
* I cleaned up a lot of TODOs from yesterday.
* I PhET-iO instrumented the new radio buttons much better, and they are ready for review now.
* As part of the PhET-iO step, I removed the phetioFeatured overrides for the `scientificNotationProperty` (as it no longer exists), and the `showForceValuesProperty`, and added phetioFeatured for the new `forceValuesDisplayProperty`. Let me know what you think.
* I DID NOT end up diving into the base logic for `showValuesProperty`, instead I think it is easiest to just keep it, since all three sims use that, and only two of the three sims have a `forceValuesDisplayProperty`. The result of this is simpler common code logic, and a duplicated link in CL and GFL to make sure that `showForceValuesProperty` is kept in sync as `forceValuesDisplayProperty` is changed via the UI.

Assigning to @kathy-phet and @arouinfar for review.

**Comment by arouinfar** [comment]
@zepumph Coulomb's Law is looking good, but the gap between the checkbox and "Constant Size" looks a bit large in GFL. Can you left-align "Constant Size" with the strings above it?

<img src="https://user-images.githubusercontent.com/8419308/71698096-71b0ed00-2d77-11ea-8c40-68f63cd9fcc2.png" width=200>

Things also look good in studio. The only thing that looks a bit odd to me is the `constantRadiusCheckbox` and `constantRadiusProperty`. Both GFL and GFLB use "Constant Size" for the string, so it's a bit strange to call it "Constant Radius".

**Comment by zepumph** [comment]
I decreased the spacing from 10 to 4, and I feel like things are even now

![image](https://user-images.githubusercontent.com/6856943/71860467-7b03c780-309f-11ea-8912-acf2adb7bcad.png)

See https://github.com/phetsims/gravity-force-lab/issues/230 for tandem naming. @arouinfar are we ready to close here?

**Comment by arouinfar** [comment]
Looks great @zepumph!
