### ISSUE TITLE
Ruler and sonification - add click sound (if possible)

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#208]
@jbphet is implementing sound for this sim over in #181.
He will be implementing the same grab and drop sounds for the ruler interaction (i.e., Measure Distance Ruler) that we used in Friction.

Related to my comment https://github.com/phetsims/gravity-force-lab/issues/181#issuecomment-556013184, I discussed a very simple sound idea for the ruler with @emily-phet yesterday.

@jbphet, we would like it if you could - in addition to the pick-up and drop sounds - add the Ohm's Law slider-click sound to the ruler, so that when the ruler is moved it makes a very light clicking sound.

The purpose of the sound is to just indicate movement, basically ensuring there are no silent steps. Blind screen reader users really get uncomfortable with silent steps. The click should reassure them that they are successfully moving the ruler. It is not supposed to be fun or interesting, just reassuring.

I am working a simple set of context responses to indicate what the Measure Distance Ruler is for, and that there are more productive things to do than move the ruler around.

**Comment by jbphet** [comment]
@terracoda - I have a question about this.  You said above:

> The purpose of the sound is to just indicate movement, basically ensuring there are no silent steps.

Should this sound only be active when the ruler is being moved via keyboard interaction?  It doesn't seem to me like it would be very useful in other contexts, such as mouse and touch drag operations, and may even be a bit distracting, so making it active only during keyboard movements would be my initial inclination.

**Comment by terracoda** [comment]
@jbphet, that's a good question, but how would we distinguish between touch gestures with or without a screen reader enabled? I don't think we can distinguish this.

I think we can potentially play with the volume to reduce potential distraction.

Honestly, though, I'd like to be able to try it out in all interaction modes. If we think it would work fro some users, we could potentially decide to make it an enhanced sound.

Again, apologies for this late request. Are there any implementation issues? I am naively hoping it is a relatively simple thing to do - emphasis on naivety ;-)

**Comment by jbphet** [comment]
@terracoda just spoke over zoom, and we decided that for the first round of this, I'll implement clicks on every movement of the ruler from the keyboard, and for mouse and touch I will set a motion threshold (we said to try something like 0.2 meters) where a click will occur after the ruler has been moved by that amount (basically a 2D version of what was done for slider dragging).

**Comment by jbphet** [comment]
Notes from the 11/26/2019 review meeting:
+ The pickup and release sounds are a bit "squishy" sounding, and we'd like to try something a little more "crisp" and/or "sharper".
+ The distinction between the pickup and release is a little too subtle at this point, so the new sounds should be slightly more distinct from one another.
+ The motion sound is okay, but the group wasn't loving it.  Descriptions like "crickets" and "Geiger counter" were used.  @Ashton-Morris is going to take a shot at something more pleasing.
+ Regardless of the sound used, the motion sounds should be "Enhanced".
+ The motion sounds that are played during dragging via keyboard should play less frequently (i.e. not on every move event)

Assigning to @Ashton-Morris and me for followup.

**Comment by jbphet** [comment]
Notes from the 12/3/2019 review meeting:

+ We compared several versions and decided to go with something pretty simple and not very physical, so Ashton is going to provide some new versions with a fixed interval between them.
+ Ashton will also provide at least one alternative sound for the motion to integrate
+ For next week, JB will 
  + integrate the new sounds mentioned above
  + set the ruler motion sound as “enhanced”
  + set the ruler pickup/dropoff as sets in the options (instead of being individually selectable)
  + make the amount of plays when keyboard drag occurs less frequent

**Comment by jbphet** [comment]
This was reviewed in the 12/10/2019 sound design meeting, and we decided to use option 1 for the grab/release sounds and also option 1 for the ruler motion sounds.  The other changes listed above in https://github.com/phetsims/gravity-force-lab/issues/208#issuecomment-561398763 were also completed and the team generally liked what they saw and heard.

The next steps are:
- [ ] remove the option dialog and unused sounds and just have the agreed-upon sounds in place
- [ ] add mix markers to the code and do a mix
- [ ] publish a version for the next round of review

One outstanding question that we will address at the next round is whether the amount of clicking that occurs during mouse, touch, and keyboard drag is to our liking or should be adjusted.

**Comment by terracoda** [comment]
@jbphet, next review is schedule for Dec 18.

**Comment by terracoda** [comment]
I should add if there is time.

**Comment by terracoda** [comment]
@jbphet and @Ashton-Morris and @emily-phet, the latest version of GFL
https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-dev.22/phet/gravity-force-lab_en_phet.html?a11y&supportsSound&supportsEnhancedSound

has the ruler sounds, I hope to get some feedback on this this coming week. I won't plan to explore the options unless there are serious questions about the Options 1&1.

It sounds great on computer and phone in my opinion.

**Comment by terracoda** [comment]
From my perspective, this issue is ready to close.

**Comment by terracoda** [comment]
@jbphet and @Ashton-Morris, if there is no work to do in this issue, please close. We are really close to RC, and I think the final sound check is going over in #181
