### ISSUE TITLE
Remove ruler aria-describedby after 2 successful grabs

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab#211]
After meeting with @terracoda today, we think that this is a good way forward, because the help text is too much each time you select the ruler.

**Comment by zepumph** [comment]
@jessegreenberg will you please review this change. I ended up applying this completely in common code, because I felt like this is likely a sentiment that will be shared for most cases. I also added doc that made clear that this describedby association only applies when grabbable.

**Comment by terracoda** [comment]
Is there a dev release?

**Comment by terracoda** [comment]
@zepumph, sorry, it is assigned to @jessegreenberg. If you want me to review it, I need a dev release ;-)

**Comment by terracoda** [comment]
I tested [dev version 2.2.0-dev.21](https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-dev.21/phet/gravity-force-lab_all_phet.html) and it works nicely from my perspective.

**Comment by jessegreenberg** [comment]
Commits look great. I agree this will be useful to have as a general pattern. Just one thought about `numberOfGrabs`.

Can the default predicate use `this.numberOfGrabs` instead of taking `numberOfGrabs` as an arg? Then should `numberOfGrabs` be made public in case someone wants to use it in their own predicate function?

**Comment by zepumph** [comment]
That sounds like a perfectly good way of doing it. But it also feels like apples and oranges to me. Is there a particular reason for the refactor? Does it just feel better to you? 

I don't really see a value in making numberOfGrabs public.

Again I have no strong preference either way.

**Comment by jessegreenberg** [comment]
Sorry, I added reasoning in an edit and it ended up confusing things.

> The only reason I am thinking about it is because I am imagining that one will have to count numberOfGrabs themselves every time they use an addAriaDescribedbyPredicate other than the default.

**Comment by zepumph** [comment]
Sorry I don't understand. 

>I am imagining that one will have to count numberOfGrabs themselves every time they use an addAriaDescribedbyPredicate other than the default.

the numberOfGrabs that is passed through the function is the current number of grabs, so you don't have to count.

Furthermore, looking more closely, passing `this.numberOfGrabs` to the default predicate looks annoying. It would require binding, and accessing `this` before the `super` call has been called. Now that I have looked at bit closer, I think I like it more the way it is. What do you think?

**Comment by jessegreenberg** [comment]
> the numberOfGrabs that is passed through the function is the current number of grabs

You are totally right. Sorry, I don't know why I got confused about this. OK in that case review is complete.
