### ISSUE TITLE
rename PDOMNode -> DescriptionNode

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab#212]

**Comment by zepumph** [comment]
@jessegreenberg if you have time to tackle this, that would be awesome, otherwise I'll get to it a bit later.

**Comment by jessegreenberg** [comment]
We also agreed that this should apply to all sims (not just GFL/GFLB) Ill rename others as part of this issue.

**Comment by jessegreenberg** [comment]
Renamed above, no more PDOMNodes.
