### ISSUE TITLE
Ruler Movement Repsonses ready for implementation

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#215]
@zepumph, I made new tables to lay out all the common strings and to provide examples of all the context responses need for grabbing, moving and releasing.

I think things are much more general now and I have provided some fuzzy pseudo logic to help with implementation. Please see this section and these tables in the design document

[Context Responses for Measure Distance Ruler (done Nov 28)](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.w72xr0t7fomr)
- (New) [Table: Phrases needed for ruler context responses (grab, move, release)](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.il2wpm7us4ai)
- (New) [Table: Combining Phrase Patterns for Grab & Release Responses](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.oucyum20qox3)
- (New) [Table: Combining Phrase Patterns for Jump Responses (Keyboard Only)](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.xxte1uir6uit)
- (New) [Table: Pseudo Logic & Combined Phrases for Movement Responses (several examples)](https://docs.google.com/document/d/1-37qAgde2XrlXBQae2SgjartM35_EnzDD9pdtd3nXAM/edit#heading=h.2x1ofybk8azg)

I hope you like it and I hope it is logical!
These are the goals I am going for:
- generalize the hints.
  - I tried to generalize everything but the first initial grab.
  - Initial grabs for both keyboard and gesture have custom content to provide device specific instructions. 
  - Except for responses to J+C and J+H, I think I generalized move responses so they are the same for both gesture and keyboard. 
  - I provide some pseudo-logic for when the responses should fire.

**Comment by terracoda** [comment]
If you have questions just change the label to meeting, and we can discuss in our next meeting.

**Comment by zepumph** [comment]
I think that everything in the google doc has been implemented for the ruler. I have not tested gesture at all, but keyboard alerts were sounding good. @terracoda please review.

**Comment by terracoda** [comment]
@zepumph, I noticed the old hint for moving left and right...
- "Move ruler left and right with letter keys A and D."

Please remove that one. I decided to drop it as it was too Keyboard centric.
- It appeared on regrab after a successful J+C and release that left the ruler "just below centers"

![Screen Shot 2019-12-31 at 9 55 47 PM](https://user-images.githubusercontent.com/1902116/71637542-0e607700-2c20-11ea-97d5-7da92c254d1c.png)

**Comment by terracoda** [comment]
Starting a new issue for the above comment.

**Comment by terracoda** [comment]
I found 4 other things which I will make issues for:
1. Not hearing "Released." when using J+H. I think this is a timing issue as I see it in the A11y View.
2. After a reset with the Reset All button, I get a vertical region change early - on the first step which triggers an early region change combinedReleaseAndExploreHint on the second step. This only seems to happen after a reset.
3. Found an "s" on meters when centers were 1 meter apart. Can you add logic to remove the "s" in that case?
4. I'm thinking, "Centers {{4}} meters apart." sounds a bit strange. Considering returning to "Centers of spheres {{4}} meters apart." I'll ask Amy if she has a preference.

**Comment by terracoda** [comment]
@zepumph, I reviewed everything you implemented, and it all seems to be working nicely for the keyboard experience (except noted issues).

Please post a dev version when it is ready to test on mobile. Assigning back to you and removing ready to review label.

Nice work!

**Comment by zepumph** [comment]
Alright, I have noted all of the separate issues created in response to this review. Thank you so much for having them separate; it made my work today much easier and I appreciate it. Is there anything else for this issue?

**Comment by terracoda** [comment]
Everything in this issue is good. Remaining bits and pieces (if any) can be followed in other issues.
