### ISSUE TITLE
Change help text for Measure Distance Ruler (keyboard only)

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#216]
Related to design changes outlined in #215, I have decided to remove the lengthy and not very helpful reference to the WASD keys in the Measure Distance Ruler's help text that is always available on-demand in the State Descriptions in the PDOM. 

Please change the **bolded platform specific help text** in the curly braces from:
- If needed, grab ruler to measure distance between centers of spheres. {{**Once grabbed, use keyboard shortcuts or letter keys W, A, S, or D to move ruler up, left, down, or right.**}}

**TO:**
- If needed, grab ruler to measure distance between centers of spheres. {{**Once grabbed, use keyboard shortcuts to move ruler.**}}

**Comment by terracoda** [comment]
@zepumph, while you are working on #215 it makes sens to do this related issue as well.

**Comment by zepumph** [comment]
This is done in GFL, and while I was there I changed the two other usages in Friction and BASE as they seemed the same. Can you please review.

**Comment by terracoda** [comment]
@zepumph, thanks for pointing out the changes in BASE and Friction.
This simplified help text in the actual PDOM is good as it is platform/device independent.

The initial grab response in all cases (GFL, BASE, and Friction) contains device-dependent essential information about moving with the WASD keys or dragging with the finger.

This change removed duplication and makes our PDOM content more general.

I noticed the Balloon in BASE is not draggable. I'll open a separate issue for that - not sure when that happened. The ruler and the book work just fine.

**Comment by terracoda** [comment]
@zepumph, except for the issue with BASE which may or may not be related, this issue is done in my opinion.

**Comment by terracoda** [comment]
Closing, please re-open if you need to re-open.
