### ISSUE TITLE
Screen Summary updates caused by Changes in PDOM

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#218]
Changes to the PDOM will be made in issues #204 and #207. These changes will require changes to the screen summary.

**Current Screen Summary** as of Dec 9th, 2019:
> The Play Area has two mass spheres, a blue sphere labeled m1 and a red sphere labeled m2. A force vector arrow starts at the center of each sphere and points directly at the opposite sphere. Spheres can be moved closer or further from one another along a track. The mass of each sphere can be increased or decreased. Each sphere is held in place by a robot.

> In the Control Area, checkboxes change force notations and mass representations. There is a moveable ruler to take measurements, if needed, and a button to reset the sim.

**Once #204 & #207** are implemented these 2 paragraphs will read (see bolded changes):
"The Play Area has two mass spheres, a blue sphere labeled m1 and a red sphere labeled m2. A force vector arrow starts at the center of each sphere and points directly at the opposite sphere. Spheres can be moved closer or further from one another along a **measured** track. The mass of each sphere can be increased or decreased. Each sphere is held in place by a robot. **Optionally, a moveable ruler can be used to measure distance between the spheres' centers.**

In the Control Area, **there are options to change force notations and mass representations, and** a button to reset the sim. "

**Comment by terracoda** [comment]
Note, depending on the final order and content in #207  I might have to tweak the content again sligtly.

**Comment by zepumph** [comment]
On hold until https://github.com/phetsims/gravity-force-lab/issues/204

**Comment by zepumph** [comment]
@terracoda, this was implemented above, please review.

**Comment by terracoda** [comment]
Sounds great! Thanks!
