### ISSUE TITLE
Set output levels for sounds

### ISSUE THREAD

**Issue by jbphet** [phetsims/gravity-force-lab#220]
@Ashton-Morris - I've added markers for mix adjustments to `GravityForceLabScreenView` in the gravity-force-lab repo and to `ISLCRulerNode` in the inverse-square-law-common repo.  Please go through them and let me know how you think we should adjust these levels.

For reference, this is a child issue of https://github.com/phetsims/gravity-force-lab/issues/181.

**Comment by jbphet** [comment]
By the way, whatever we do mix-wise here should be reasonably consistent with what was done for Gravity Force Lab Basics, which has already been published.

**Comment by Ashton-Morris** [comment]
The only think I thought needed adjusting was levels for force when comparing to GFL:B.

Lines 344 - 351

``
    // @private - sound generation for the force sound
    this.forceSoundGenerator = new ContinuousPropertySoundGenerator(
      model.forceProperty,
      forceSound,
      new Range( model.getMinForce(), model.getMaxForce() ),
      resetAllButton.buttonModel.isFiringProperty,
      { initialOutputLevel: 0.15 }
    );

``

**Comment by zepumph** [comment]
I see no more TODOs for this issue, and it looks like @jbphet tweaked what @Ashton-Morris asked for. I'm going to close this, @Ashton-Morris please reopen if you disagree.
