### ISSUE TITLE
Remove Ruler's left-right movement hint

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#222]
Moving here from #215 
@zepumph, I noticed the old hint for moving left and right...
- "Move ruler left and right with letter keys A and D."

Please remove that one. I decided to drop it as it was too Keyboard centric.
- It appeared on re-grab after a successful J+C and release that left the ruler "just below centers"

![Screen Shot 2019-12-31 at 9 55 47 PM](https://user-images.githubusercontent.com/1902116/71637542-0e607700-2c20-11ea-97d5-7da92c254d1c.png)

**Comment by zepumph** [comment]
Removed above. Please review.

**Comment by terracoda** [comment]
Fixed! You are awesome!
