### ISSUE TITLE
After reset all I get an early vertical region change - on first step

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#226]
Item 2 from https://github.com/phetsims/gravity-force-lab/issues/215#issuecomment-570018202,

After a reset with the Reset All button, I get a vertical region change early - on the first step. This early region change triggers an early combinedReleaseAndExploreHint on the second step. This only seems to happen after a reset.

Could you fix it so the region change happens when there is an actual region change?

**Comment by zepumph** [comment]
Over in https://github.com/phetsims/gravity-force-lab/issues/215#issuecomment-570018202 I added a bunch new state, but didn't end up resetting any of it. This should now be fixed for the above explicit bug as well as likely others.

**Comment by terracoda** [comment]
Fixed!
