### ISSUE TITLE
Remove "s" on meters when only 1 meter

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#227]
Item 3 from https://github.com/phetsims/gravity-force-lab/issues/215#issuecomment-570018202

I found an "s" on meters when centers were 1 meter apart. 
Can you add logic to remove the "s" in that case?

**Comment by terracoda** [comment]
Adding screen shot with VO text
![Screen Shot 2019-12-31 at 11 22 39 PM](https://user-images.githubusercontent.com/1902116/71638068-6010fd80-2c30-11ea-8d29-5bc1aa39fe32.png)

**Comment by zepumph** [comment]
This was a small change in common code, which I like. I will apply to a few other spots too, is that alright? For example the "centers exactly {{distance}} {{unit}}" in the screen summary:

![image](https://user-images.githubusercontent.com/6856943/71839574-f47fc380-3067-11ea-9547-2d116ed61e36.png)


Does this feel good to you?

**Comment by terracoda** [comment]
Yes, that looks great! Thanks for finding and fixing these other spots.
