### ISSUE TITLE
Long or short distancePhrase in Ruler movement reposnes?

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#228]
Item 4 from https://github.com/phetsims/gravity-force-lab/issues/215#issuecomment-570018202

I'm thinking, "Centers {{4}} meters apart." sounds a bit strange. 
I am considering going back to the longer version, "Centers of spheres {{4}} meters apart." 

I'll ask @arouinfar  if she has a preference.

To see the response in context use the A11y View on master.

@arouinfar, my question is, should we be more explicit and use "Centers of spheres" in the ruler movement responses? The distancePhrase forms part of some of the responses.

**Here are 2 examples:**
![Screen Shot 2019-12-31 at 11 38 12 PM](https://user-images.githubusercontent.com/1902116/71638043-b7fb3480-2c2f-11ea-9132-6b13d5b6ef20.png)

**Comment by terracoda** [comment]
@arouinfar, let me know if you need more context. The initial responses look really long because they first 2 responses contain instructions for jumping (if using keyboard), and dragging if using touch. 

After the first couple of grabs and moves, the user will only get sonified clicks for movement then occasional responses containing ruler position and distance between centers upon a vertical or horizontal region change. I think there are 6 described Vertical ruler positions (vertical regions), and horizontal regions are defined by 1 meter of total movement. 

This results in no more than 4 or 5 key presses to get a response about position and distance, and then a gentle hint to release and go do something more fun.

My question is about the distance string which is included as part of the occasional responses. Which is better in your opinion?
1. [Ruler Position Phrase.] + [Centers {{4}} meters apart.]
2. [Ruler Position Phrase.] + [Centers of spheres {{4}} meters apart.]

Number 2 is a little longer, but "of spheres" might be a really important detail worth having in there for emphasis.

Let me know what you think.

**Comment by arouinfar** [comment]
@terracoda I think it sounds clearer with the addition of "of spheres", and the added length doesn't seem unreasonable to me.

**Comment by terracoda** [comment]
Thanks @arouinfar.

@zepumph assigning this small change to you for implementation.

**Comment by zepumph** [comment]
Implemented above
