### ISSUE TITLE
Add dynamic distance phrase back on front of Move m1/m2 help text

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab#229]
Based on recent exploration with a partially described ruler interaction, I would like to put the dynamic distance phrase back on the front of the help text that provides guidance to move the spheres.

I originally asked for this phrase to be removed in GFL regular because the distance value is provided when grabbing the Measure Distance Ruler, but we don’t actually want learners to grab the ruler.

The new help text would look like this (bolded text is new part) - similar to GFL Basics:
- **Centers of spheres, {{4}} meters apart.** Move spheres, closer or farther from each other.

**Reasoning**
- GFL Basics has the distance information in this exact same place, aligning the sim's designs more.
-  It keeps the distance information closer to the Move m1 (or Move m2) interactions which may provide implicit encouragement to move them.
- Leaving the information off the help text for the Measure Distance Ruler keeps that interaction's help text clear and simple. 

**Side Note on Reasoning**
My first thought was to put the distance information on the help text for the "Measure Distance Ruler" button, but the important words for that interaction are "If needed" which I want to be at the front. Adding in the distance information after all this cuing to ignore the ruler feels weird to me. Here was my idea for reference, but do not implement.
  -  If needed, grab ruler to measure distance between centers of spheres **, currently {{4}} meters apart**.

**Comment by terracoda** [comment]
@emily-phet and @arouinfar, your comments are welcome, but I feel confident in this placement of the distance phrase.

**Comment by zepumph** [comment]
Implemented above. I like this change because it involved getting rid of split logic between REGULAR and BASICS, and putting it in inverse square law. Please review.

**Comment by terracoda** [comment]
@zepumph, sounds great, and is nice and familiar, too. I agree, the alignment is nice. Closing.
