### ISSUE TITLE
Rename "constant radius" to "constant size"

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab#230]
From https://github.com/phetsims/gravity-force-lab/issues/207 @arouinfar said:

>Things also look good in studio. The only thing that looks a bit odd to me is the `constantRadiusCheckbox` and `constantRadiusProperty`. Both GFL and GFLB use "Constant Size" for the string, so it's a bit strange to call it "Constant Radius".

I understand this, and totally agree with checkbox, but I feel potentially a bit differently with the model because "radius" is used quite a bit in other methods, like to calculate the size of the mass, you call `calculateRadius`. I'm going to think on this one a bit.

**Comment by arouinfar** [comment]
> I feel potentially a bit differently with the model because "radius" is used quite a bit in other methods, like to calculate the size of the mass, you call `calculateRadius`.

Oh, that's also a good point @zepumph.  Should you decide to leave things as is, I think clients will understand that constantRadius is related to the Constant Size checkbox so long as the documentation is reasonable.

**Comment by zepumph** [comment]
I like calling it `constantSizeCheckbox`, but I also am tempted to keep `constantRadiusProperty`. I changed it as such, but would love @samreid's opinion, since there is a difference now between the Checkbox and the Property it runs on. Does this feel ok with you? I know it is atypical.

**Comment by zepumph** [comment]
> so long as the documentation is reasonable.

@arouinfar, this is the current documentation for the constantRadiusProperty. Note how it says "size" in it: "Use this to toggle if the masses have a constantly sized radius, even when the mass changes."

- [ ] Does that feel good to you?

**Comment by arouinfar** [comment]
Looks good to me @zepumph

**Comment by samreid** [comment]
> const constantSizeCheckbox = new Checkbox( constantSizeText, model.constantRadiusProperty,

Sounds great.  The UI component matches the UI text, and the model property is named correctly.  The mapping done here is straightforward.  Can this issue be closed?

**Comment by zepumph** [comment]
Yes thanks!
