### ISSUE TITLE
Slight string overlap with mass labels

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab#237]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Edge
**Problem description**
For https://github.com/phetsims/QA/issues/471
When strings are long or double, the m1 and m2 labels beneath the masses can overlap if they get too close to each other.

**Visuals**
![stringoverlap](https://user-images.githubusercontent.com/41024075/73382621-15ad8b80-4285-11ea-88ec-7f9ed4882839.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity Force Lab‬:‪Gravity Force Lab‬
URL: https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-rc.1/phet/gravity-force-lab_all_phet.html?stringTest=double
Version: 2.2.0-rc.1 2020-01-28 03:08:20 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 Edg/79.0.309.71
Language: en-US
Window: 1536x718
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by zepumph** [comment]
We went over this at one point (can't remember the issue), but it turns out that it is very hard to detect this because the two masses are separate objects that don't know about each other's text positioning. I believe that we decided that this was acceptable. @arouinfar do you remember this at all?

**Comment by arouinfar** [comment]
@zepumph we discussed the label overlap to some extent in https://github.com/phetsims/inverse-square-law-common/issues/79. For phet-brand, the string is never expected to exceed 2 characters (see https://github.com/phetsims/coulombs-law/issues/78). 

For PhET-iO the label overlap could be a real issue, as a client may want to change "m" to "mass" or "q" to "charge". In that case, the strings will inevitably overlap. In https://github.com/phetsims/inverse-square-law-common/issues/79 there was mention of shifting the labels away from each other to avoid overlap. I think this could be more trouble than it'd be worth, given that there are very few cases where the strings would overlap.

I'm inclined to do nothing here, closing.
