### ISSUE TITLE
Outer focus highlight has inconsistent color

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-force-lab#240]
Grouped components such as NumberControl or VerticalAquaRadioButtonGroup have two focus highlights. In Gravity Force Lab, I noticed that the color of the outer focus highlights is inconsistent for these two UI components.

<img width="286" alt="Screen Shot 2020-01-29 at 3 27 04 PM" src="https://user-images.githubusercontent.com/8419308/73408736-74412c80-42ba-11ea-9dfe-c49b2054fb5b.png">
<img width="251" alt="Screen Shot 2020-01-29 at 3 27 17 PM" src="https://user-images.githubusercontent.com/8419308/73408737-74412c80-42ba-11ea-8929-d82bb8e6303d.png">

I believe the outer focus color used in the radio button group is the color we originally chose when we came up with this focus strategy. Assigning to @zepumph for investigation.

**Comment by zepumph** [comment]
Sorry for the confusion @arouinfar, but I ended up moving this to GFL because actually it looks like this is is specifying a custom group focus highlight for the mass control when it should just be using the default. I'll see about getting rid of that.

**Comment by zepumph** [comment]
I see the custom highlight is nice to make it a bit tighter, the real issue was just coloring, how does that look now? 

![image](https://user-images.githubusercontent.com/6856943/73509878-1af5fd80-438d-11ea-9060-62c57cf5e7bf.png)
![Uploading image.png…]()

**Comment by arouinfar** [comment]
Looks good @zepumph!

**Comment by zepumph** [comment]
Thanks! We will need to cherry pick to the branch. Reopening.

**Comment by loganbraywork** [comment]
Seems to be fixed
