### ISSUE TITLE
LoL icons/descriptions

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-force-lab#241]
For https://github.com/phetsims/QA/issues/471

**Comment by arouinfar** [comment]
Icons & descriptions are ready for delivery to LoL when the sim redeploys.

**Comment by zepumph** [comment]
The sim has redeployed! Removing label.

**Comment by arouinfar** [comment]
Thanks, @zepumph. I'll deliver the sim to LoL tomorrow.

**Comment by arouinfar** [comment]
Delivered to client.
