### ISSUE TITLE
IE sim made from html template doesn't load

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab#244]
For https://github.com/phetsims/QA/issues/471. When trying to use the example code to open the sim in IE (either from using the launch button or copying the code) the sim does not load and a console error appears. Oddly, this doesn't seem to be the case when using the sim wrapper.
![console](https://user-images.githubusercontent.com/41024075/73555329-aa8dc180-440a-11ea-96e1-2b713f63f746.png)

**Comment by zepumph** [comment]
@KatieWoe I just saw that the error is coming from the `_debug` version of the sim. This is not supported on IE, and only the production version should be tested. To do this make sure to omit the `?phetioDebug` query parameter from all testing links on IE. Please let us know if it is not easy to remove `?phetioDebug` or if you have and this problem still occurs.

**Comment by zepumph** [comment]
@KatieWoe I don't think the above comment was quite right. The Index wrapper loads the template that has build in debug mode `true`. I think that to support IE, this is a case where we shouldn't have this be debug true. 



I also think that we should think about making the output of studio launch be debug: false. 

Above is the solution to this problem, but I'm not totally convinced that it is the right way to go. The wrapper index is developer aimed, and the goal is to lean them towards using the debug version for initial development. I would rather have this be set to debug: true. 

Maybe we could add a note in the wrapper template for the debug option that say "the simulation will not run on Internet Explorer when in debug: true."

<details>

```diff
Index: common/html/wrapperTemplateSkeleton.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- common/html/wrapperTemplateSkeleton.html	(revision 71c7d09051aea38724df4c77cf2ce4b690669be0)
+++ common/html/wrapperTemplateSkeleton.html	(date 1580783293153)
@@ -74,7 +74,7 @@
      * This will launch the simulation with added error throwing to catch mistakes and problems easier.
      * {boolean}
      */
-    debug: true,
+    //{{DEBUG_OPTION_WITH_COMMA}}
 
     /**
      * Called for each new event from the sim's data stream
Index: common/js/loadWrapperTemplate.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- common/js/loadWrapperTemplate.js	(revision 71c7d09051aea38724df4c77cf2ce4b690669be0)
+++ common/js/loadWrapperTemplate.js	(date 1580783454053)
@@ -35,6 +35,10 @@
     width: '768', // {string} - value for the width attribute on the iframe element in the wrapper template
     height: '464', // {string} - value for the height attribute on the iframe element in the wrapper template
 
+    // {boolean} By default, load the debug version of the sim, but optionally adjust the template to load the
+    // production version.
+    debug: true,
+
     // {string} - supplemental options to pass to Client.prototype.launchSim() in the template
     launchSimOptions: '',
 
@@ -65,6 +69,7 @@
     templateString = templateString.replace( new RegExp( '{{{HEIGHT}}}', 'g' ), options.height );
     templateString = templateString.replace( new RegExp( '//{{{LAUNCH_OPTIONS}}}', 'g' ), options.launchSimOptions );
     templateString = templateString.replace( new RegExp( '//{{{AFTER_SIM_INITIALIZED}}}', 'g' ), options.afterSimInitialized );
+    templateString = templateString.replace( new RegExp( '//{{DEBUG_OPTION_WITH_COMMA}}', 'g' ), `debug: ${options.debug},` );
 
     assert && assert( templateString.indexOf( '{{{' ) === -1, 'loadWrapperTemplate should fill in all template values' );
     callback( templateString );
Index: index/index.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- index/index.js	(revision 71c7d09051aea38724df4c77cf2ce4b690669be0)
+++ index/index.js	(date 1580783155585)
@@ -93,6 +93,7 @@
       }
     };
   }, {
-    pathToCommon: window.phetio.Client.IS_BUILT ? 'wrappers/' : '../'
+    pathToCommon: window.phetio.Client.IS_BUILT ? 'wrappers/' : '../',
+    debug: false
   } );
 } )();
\ No newline at end of file

```

I have confirmed that the above patch works. Tagging in for some assistance of opinion by phet-io sub-team.

**Comment by chrisklus** [comment]
>The wrapper index is developer aimed, and the goal is to lean them towards using the debug version for initial development. I would rather have this be set to debug: true.

Yeah agreed, defaulting with debugging on seems much more important than being IE friendly

**Comment by KatieWoe** [comment]
Modifying the code with this fix does allow the file to run in IE.

**Comment by zepumph** [comment]
From discussing this earlier today with @samreid, we want to support the above patch with the following features:

- [ ] Radio Buttons in studio, default to value of ?phetioDebug, that dictate the `debug` flag of "launched" wrappers.
- [ ] IE opt out of debug:true, with a console.log about it. (in launchSim)
- [ ] In loadWrapperTemplate, opt out of debug:true if on IE, perhaps with an added comment line too, "Debug not supported on IE"

**Comment by zepumph** [comment]
I implemented the first two above. Since this code in on the wrapper side, I had to port over IE detection from platform.js. This was less than ideal and made me decide against doing the third bullet with the following thoughts. We don't support our wrapper suite in IE, as no developer client of PhET-iO is using IE. We know this chiefly because we don't support studio in IE. Thus I don't feel like adding this IE workaround in the wrapper suite (the wrapper index) is useful at all. Note that this is chiefly useful because the value of `debug` in the customized wrapper when previewed/downloaded from studio states the correct value of debug given the radio button value on "action"

@samreid will you please review before I cherry-pick into GFL rc shas. I'm especially interested in a name for the radio buttons. It would be nice if that could be better.

**Comment by samreid** [comment]
I thought a good name for those radio buttons would be "HTML Output".

**Comment by samreid** [comment]
Once we move to ES6 modules, will it be easier to reuse the platform.js code in sims and wrappers?

**Comment by samreid** [comment]
I didn't spot any problems skimming through the change sets.  Can you recommend how these changes can be tested?  Should I try to trick my computer into simulating IE?

**Comment by zepumph** [comment]
@samreid and I looked into this together, and decided that a `silent` mode, along with a few other tweaks was really nice. I think this is ready to be cherry-picked to the RC branch.

**Comment by KatieWoe** [comment]
Looks fixed in rc.2 you do get a warning:
![allowblockedcontent](https://user-images.githubusercontent.com/41024075/74885367-9adf0a00-5332-11ea-9d3e-68a71394e8cd.png)
If you click allow, then it loads
