### ISSUE TITLE
If item is dragged so that cursor is over reset all button, reset all button won't work

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/gravity-force-lab#246]
**Test Device**

MacBook Air

**Operating System**

macOS 10.15.2

**Browser**

Chrome, Firefox, Safari

**Problem Description**

For https://github.com/phetsims/QA/issues/471. This is a weird bug that I'm just documenting so that it's documented. If you're dragging an item and you move your cursor over the reset all button, let go of the item you're dragging, and then press the reset all button, the reset all button won't work. The problem doesn't persist. If you move your cursor elsewhere and then try to click the reset all button, the reset all button will work.

**Steps to Reproduce**

1. Grab an item.
2. Without letting the item go, drag your cursor over the reset all button.
3. Let the item go.
4. Try to press the reset all button.

**Visuals**

![issue](https://user-images.githubusercontent.com/31285590/73582639-450df500-444b-11ea-91c1-ab8ace37a939.gif)

<details>
<summary><b>Troubleshooting Information</b></summary>
!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity Force Lab‬
URL: https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-rc.1/phet/gravity-force-lab_all_phet.html
Version: 2.2.0-rc.1 2020-01-28 03:08:20 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Language: en-US
Window: 1440x821
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by lmulhall-phet** [comment]
This happens on older versions of macOS too.

**Comment by zepumph** [comment]
>The problem doesn't persist. If you move your cursor elsewhere and then try to click the reset all button, the reset all button will work.

Yes I found this too, even if you just move your mouse one pixel, the reset all button will work again.

steps to reproduce:
* firefox
* https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-rc.1/phet/gravity-force-lab_all_phet.html
* drag ruler so that mouse is on top of reset all button
* let go without moving the mouse a single pixel
* Note you cannot click on the reset all button until you move the mouse again

It can also be reproduced with a basic drag listener on a Node, i.e. in this link take the rectangle and drag it behind the phetMenu, you will not be able to click the phetButton.

http://localhost/scenery-phet/scenery-phet_en.html?brand=phet&ea&screens=3&component=GrabDragInteraction

This can be done on any button, i.e. the GFL mass tweaker buttons, sound toggle button, etc. . . , but not with other components. The slider, checkbox, and radio buttons do not have this problem.

I think @jonathanolson should be in charge of triaging this, as I think that it is an issue with general scenery listeners. Let me know what you think. Do we need to fix this? Is is a simple fix?

**Comment by zepumph** [comment]
@jessegreenberg and I looked at this a bit more today. We found a patch that fixed this bug in firefox.

<details>

```diff
Index: js/listeners/PressListener.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/listeners/PressListener.js	(revision 2a54156feffff8d239afe48bbe49e41a43d6e4cb)
+++ js/listeners/PressListener.js	(date 1580846016975)
@@ -240,6 +240,11 @@
       interrupt: this.pointerInterrupt.bind( this )
     };
 
+    // @private {Object} - A listener added to all pointers that come over this Node
+    this._overPointerListener = {
+      up: this.invalidateOver.bind( this )
+    };
+
     // @private {Action} - Executed on press event
     // The main implementation of "press" handling is implemented as a callback to the Action, so things are nested
     // nicely for phet-io.
@@ -649,6 +654,9 @@
 
       this.overPointers.push( event.pointer );
 
+      // if ever this pointer, regardless of what it is attached to, releases, then invalidate our over pointers.
+      event.pointer.addInputListener( this._overPointerListener );
+
       sceneryLog && sceneryLog.InputListener && sceneryLog.pop();
     },
 
@@ -684,6 +692,8 @@
       // no-op, which ObservableArray allows.
       this.overPointers.remove( event.pointer );
 
+      event.pointer.hasInputListener( this._overPointerListener ) && event.pointer.removeInputListener( this._overPointerListener );
+
       sceneryLog && sceneryLog.InputListener && sceneryLog.pop();
     },
 

```
</details>

We still have some questions though:
* We couldn't reproduce this in Chrome
* We found this bug only to effect Nodes that have a PressListener attached to them (hence why slider and its thumb isn't effected).
* We are curious about why this is different on each platform, and wonder if there is something else, underlying, here. It isn't obvious why this patch is needed for one browser but not the other.

@jonathanolson please investigate this patch, and review its validity. Thanks!

**Comment by zepumph** [comment]
I paired on this with @jonathanolson and we came up with the above solution. It is simple and works well! @jonathanolson also mentioned that @jessegreenberg and my patch above would likely have caused memory leaks since `exit` often wouldn't have shown up.

I'll cherry pick this and have QA test.

**Comment by loganbraywork** [comment]
Appears to be fixed!
