### ISSUE TITLE
GFL Sound Feature Video Script & Recording

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/gravity-force-lab#247]
Make sound features video script and review with team

https://drive.google.com/open?id=1zcE1cbsDlgAiAwRxipFJiw5QzBx-weidVG2bD_rojNc

Recording will happen after.

**Comment by BLFiedler** [comment]
Initial script created: https://docs.google.com/document/d/1zcE1cbsDlgAiAwRxipFJiw5QzBx-weidVG2bD_rojNc/edit?usp=sharing

Note: I have no mention of the ruler. Should that be included?

@emily-phet

**Comment by emily-phet** [comment]
Added a piece re ruler - feel free to edit! Made a few tweaks/comments throughout. Looks good to go to me!

**Comment by BLFiedler** [comment]
Draft 1 complete (no intro/outro, might need some sound quality finesse): https://drive.google.com/file/d/1tYXrMFAlfadAtkCjvNQxnkMEVlXlMgzl/view?usp=sharing

**Comment by emily-phet** [comment]
@BLFiedler - I think this is very nice, and good to go for publication.

Two thoughts, in case there was a need to re-record this. I think it would be nice to 1) indicate explicitly that the enhanced sound plays alongside the force sound, and 2) to indicate explicitly that the percussive sound gets deeper as the mass increases. I think the mapping of mass increasing and pitch decreasing might not be immediately interpreted as, as the object gets bigger the sound gets deeper. I think indicating this latter cueing may be easier for those who don't think as much about sound to rapidly interpret the idea.

**Comment by BLFiedler** [comment]
I will probably re-record, as Ashton gave me some good pointers on improving the sound quality on the recording platform I use (OBS). I can implement those changes.

**Comment by BLFiedler** [comment]
Re-recorded. Next steps (by end of day tomorrow): Adding intro & outro, uploading to YouTube, Captions, and addition to For Teachers section of simulation webpage.

**Comment by BLFiedler** [comment]
Published

https://www.youtube.com/embed/2M0OY6LqJOk
