### ISSUE TITLE
Ruler behind slider panel can be dragged

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab#253]
I noticed that you can drag the ruler from behind the slider boxes. Doesn't cause any problems and I don't think it needs anything done if it isn't an easy fix. For https://github.com/phetsims/QA/issues/480
![shoulddrag](https://user-images.githubusercontent.com/41024075/74776723-529dea00-5255-11ea-9ad4-36ca06332182.gif)

**Comment by zepumph** [comment]
I tried to set both `pickable: false` and `pickable: true` on the mass control panels (the `Panel` itself), and neither worked. I would have thought that either of those would block pointer events from reaching the ruler at a lower z-layer.

**Comment by samreid** [comment]
Try `Panel.options.backgroundPickable = true`

**Comment by zepumph** [comment]
Thanks @samreid! To add this in only one spot, I did a bit of refactoring too. Both of these can go into the next RC. Thanks all!

**Comment by KatieWoe** [comment]
Looks good in rc.3
