### ISSUE TITLE
When slider is disabled and opacity is at 0 the launched html simulation displays a gray, not transparent, slider

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/gravity-force-lab#255]
**Test device**
Windows 10 Laptop
**Operating System**
Windows 10
**Browser**
Edge
**Problem description**
For https://github.com/phetsims/QA/issues/480

In Phet-io studio, if the slider is disabled and opacity set to 0, the html version of the sim launches with the slider grayed out, not invisible.
**Steps to reproduce**
1. Go to the mass slider in Phet-io studio
2. Disable the mass slider
3. Set slider opacity to 0
4. Launch the sim

**Visuals**
![2020-02-19GFLPhtIOSldrVw](https://user-images.githubusercontent.com/54685448/74881604-db3a8a00-532a-11ea-8179-a209181dcb12.gif)

<details><summary>Troubleshooting information:</summary>
!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity Force Lab‬
URL: https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-rc.2/phet/gravity-force-lab_all_phet.html
Version: 2.2.0-rc.2 2020-02-13 23:11:52 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Language: en-US
Window: 1604x792
Pixel Ratio: 1.1979166269302368/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by zepumph** [comment]
Enabled works by setting the the opacityProperty, so this is a race condition where the opacity is set first, and then the enabledProperty is set, which resets the opacity. @samreid do you think we need to fix this? We have already largely solved this by featuring the enabledProperty.

**Comment by zepumph** [comment]
After discussing this with @samreid, he said:

>. . . I don’t think it’s scalable to operate under the philosophy that we will try to make it impossible for clients to “shoot themselves in the foot”, instead we should focus on making it easy for them to understand what’s happening and easily test their changes.

I agree. I think it is more important for the "launch" button to serve as an easy guide to check the customizations and make sure that what they set is as expected. I'm going to close this as a won't fix.
