### ISSUE TITLE
Can't compare with diff wrapper

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab#258]
For https://github.com/phetsims/QA/issues/480. Win 10 Chrome
When discussing with @zepumph he provided a link to use to test the rc2 diff wrapper. When pasting this link into the diff wrapper I got an error. I also tried taking the end of the provided url so that it was the wrapper index url (we have been told to use this in these tests) I still got an error.
![stillcantdiff](https://user-images.githubusercontent.com/41024075/74980725-3b463480-53ee-11ea-9e9a-3427a7722f06.gif)

**Comment by zepumph** [comment]
This is largely an issue with the documentation. 

>When discussing with @zepumph he provided a link to use to test the rc2 diff wrapper. When pasting this link into the diff wrapper I got an error.

I recommend running loading the following link, and when you do, you do not need to type anything into the input box (the link has that info built into it): https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-rc.2/phet-io/wrappers/diff/?newSimURL=https://phet-dev.colorado.edu/html/gravity-force-lab/2.3.0-dev.2/phet-io/

If you want to load a diff wrapper link where you then paste in the "other sim URL":
* Go to https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-rc.2/phet-io/wrappers/diff/
* Paste in https://phet-dev.colorado.edu/html/gravity-force-lab/2.3.0-dev.2/phet-io/

Note that the diff wrapper only wants the link up to `phet-io/`. And potentially one of the errors with the above video is that `wrappers/` is included in the URL as well.

**Comment by KatieWoe** [comment]
My mistake. Closing
