### ISSUE TITLE
move a11y strings into main strings json

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab#263]
From phetsims/chipper#795

**Comment by zepumph** [comment]
I did the first pass conversion, but I didn't delete the file because I still want to look through it for organizational comments and then refactor the new strings with nested objects.

**Comment by zepumph** [comment]
Largely this issue is the same as many of the others. In addition to the refactor moving strings to the en.json file, I also did a fair bit of renaming. @jessegreenberg when you review this one can you please focus on the naming in https://github.com/phetsims/gravity-force-lab/commit/9794c84120c4537f5b43d20e878c3504d87f1218 and let me know if that is what you were thinking was reasonable for naming convention.

**Comment by jessegreenberg** [comment]
The strings file looks good to me. I reviewed the nesting and naming and tried to think of the keys and strings out of context (as if viewed by a translator), and I think they are understandable. Key names in https://github.com/phetsims/gravity-force-lab/commit/9794c84120c4537f5b43d20e878c3504d87f1218 are in line with what we are doing currently.
