### ISSUE TITLE
User request: separate masses by 10 m

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/gravity-force-lab#265]
> I was able to measure the force for a particular arrangement of masses before the recent update. Back then, I used
> m1=100 kg
> m2=100 kg
> r1=0 m
> r2=10 m
>  
> But I can no longer separate masses apart by 10 m in this updated simulation even though a 10-m stick is available. Let’s use the full potential of the available tool!
>
> **Steps to reproduce**
> Run the sim, set masses to 100 kg, pull m1 all the way to the left, pull m2 all the way to the right, set the ruler 0 position on the center of m1. Then, the center of m2 is at 9.6 m.

**Comment by jessegreenberg** [comment]
@arouinfar @zepumph do you have any thoughts on what (if anything) should be done for this?

**Comment by zepumph** [comment]
The above increases the max distance to 10km in both GFL and basics without messing with CL, which seemed to already have it correct. While working on this suite, I was always curious as to why the max distance wasn't 10km, but never thought to ask, as it was like that when I took it over. 

I had to shorten the PullerNode "rope" length to keep things in the dev bounds @arouinfar please review. This would be a simple maintenance release that I would be happy to do.

**Comment by arouinfar** [comment]
Thanks @zepumph! All ISLC sims are looking good in master.

**Comment by zepumph** [comment]
The above assertion was more strict than was needed. It wasn't in GravityForceLabForceDescriber, so I just removed it. I think we are ready for a maintenance release here.

**Comment by terracoda** [comment]
@zepumph, does this change have any impact on the ranges for the described regions?

**Comment by zepumph** [comment]
The minimum range is now smaller for both sims, but it seems to be negligible. For GFLB, it still rounds up to .7, so there is actually no visual change, and for GFL it now has a slightly smaller min. I don't think it changes the regions, but instead just adds .3 x 10^-12 newtons (for GFL) to the lowest region. How does that sound?

**Comment by terracoda** [comment]
I think it is good that that learners can set the spheres 10 metres apart - makes perfect sense. I had a listen, and the described distance sound fine.

I listened to the sim on localhost/PhETMarks and I was not getting sonfication for the ruler, or any position or movement responses for the ruler.

I listened to the published version and I get position and movement responses, but no sonification while moving the ruler around.

Shall I open issues for sonfication and responses?

**Comment by terracoda** [comment]
@zepumph, oh sorry, the clicking sound for the ruler is and "Enhanced sound". It's there.

**Comment by terracoda** [comment]
And I tested again, and I now hear the ruler position and movement responses. Not sure why I didn't hear them the first time. Computer glitch, I guess.

I shall not open any new issue . Distance sounds great.

**Comment by zepumph** [comment]
This MR has been published, see 
https://phet.colorado.edu/sims/html/gravity-force-lab/latest/gravity-force-lab_en.html
https://phet-io.colorado.edu/sims/gravity-force-lab/2.2/
https://phet.colorado.edu/sims/html/gravity-force-lab-basics/latest/gravity-force-lab-basics_en.html

Over to @oliver-phet to email/close.

**Comment by oliver-phet** [comment]
User has been notified, closing.
