### ISSUE TITLE
Maintenance release GFL and GFL:B

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab#266]
For is mostly https://github.com/phetsims/gravity-force-lab/issues/265, and should be quick and easy.

@ariel-phet, GFLB RC shas were taken 9/19, and GFL in 1/20. Is there anything else that I should add here in this maintenance release?

**Comment by ariel-phet** [comment]
Nothing else needs to be added, no. Proceed @zepumph

**Comment by zepumph** [comment]
Alright, MR will be done over in https://github.com/phetsims/gravity-force-lab/issues/265
