### ISSUE TITLE
PhET-iO API looks out of date

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-force-lab#282]
We needed to update the phet-io api for https://github.com/phetsims/studio/issues/243, however I saw a lot of other unrelated changes.  I'll commit the update to fix https://github.com/phetsims/studio/issues/243 but the other changes should be reviewed and signed off.  Assigning to responsible dev.

**Comment by zepumph** [comment]
I think all the changes in that commit are specific to your change. Unlike other sims, the `phetioElementMouseOverProperty` was the only instance of a `PropertyIO<NullableIO<StringIO>>`, so we added a bunch of supporting types as well (`Nullable<StringIO>`, `FunctionIO(NullableIO<StringIO>)=>VoidIO`, `ArrayIO<NullableIO<StringIO>>` etc).

Ready to close.

**Comment by samreid** [comment]
Thanks, closing.
