### ISSUE TITLE
Address user suggestion: ability to change mass without changing size of object

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/gravity-force-lab#36]
We're currently working on the Gravity Force Lab Simulation. It's a great way to collect data and graph the relationship between mass, distance, and gravitational force.

We did notice something though. Because the size of the ball increases when we increase the mass, it sometimes interferes with the distance between the balls. In addition, it seems to reinforce the misconception that size is related to mass.

I was wondering if it would be possible to change the way it is simulated so that increasing the mass changes the color of the ball, but not the size. Maybe the darker the ball, the more massive it is. 

Keeping the size might be interesting because then one can notice that changing the size doesn't actually change the force at all.

**Comment by ariel-phet** [comment]
@arouinfar when we make the teacher tips for GFL we should include these points in the model/student thinking sections

1. The spheres are assumed to be solid and of constant density, so changing the mass increases the size. we made this decision for the sake of clear feedback

2. Consider reminding students that mass and size are not in general related, but in the case of a solid constant density material they are.

**Comment by ariel-phet** [comment]
@aadish since we are making some other changes to the sim...I am now curious....

How difficult would it be to have a checkbox that says "constant size" and to have a mode of the sim where the masses are held at a fixed size (in terms of radius) and as you adjust the mass the shading of the ball varies from dark to light? 

Please comment on how difficult of an enhancement you think this would be, and a time estimate for implementing it (but do not actually make the change yet).

**Comment by arouinfar** [comment]
@ariel-phet, this is an excellent suggestion. I would really like to see a "constant size" feature implemented, if feasible. I think it would add a lot of investigative power to the sim.

**Comment by aadish** [comment]
@ariel-phet estimated time will be 20 hrs this also includes the time for refactoring the code for maintainability and pulling out things from the view and put it in the model. 
Once with the code refactoring implementing this feature will be easy, only thing to look will be how to change the color for this feature

**Comment by ariel-phet** [comment]
OK @aadish lets plan on implementing this feature after the refactor and code cleanup.

@arouinfar please make a mockup (could just be a screenshot with an additional check box) and put it in this issue.

**Comment by arouinfar** [comment]
@ariel-phet @aadish Here's a mockup. I noticed that the dev boundary is not at the correct aspect ratio (which has been noted in #46) so I pushed down the force labels. With the new scaling, the max radius will be a bit smaller, so it should work. 

I added the Constant Size checkbox below Show Values. To accommodate the slightly larger string, I expanded the panel 15 px to the left and shifted the reset all so it remains centered.

![image](https://cloud.githubusercontent.com/assets/8419308/12564741/2c1d2762-c36e-11e5-9a89-af6adf31d4de.png)

@aadish please let me know if you need anything else.

**Comment by jbphet** [comment]
@arouinfar - @aadish and I have several questions about this:
+ Should the objects look any different when in "Constant Size" mode?  I feel like this would be a good cue to the user that something is different, but I don't see any differences in the mockup.
+ Should the objects change to some fixed size in "Constant Size" mode?  Or should it be possible for the user to use the sim in the regular mode, then click the "Constant Size" check box and have the sizes essentially freeze at whether they had configured?
+ Do we really want to have the sizes different in this mode, as shown in the mockup?

**Comment by ariel-phet** [comment]
My suggestion would be the objects change to a fixed size in "constant size" mode and be of equal size, with some clear cue that "density" is changing (light to dark seems like a simple easy cue).

My thoughts - obviously wait to hear @arouinfar opinion

**Comment by aadish** [comment]
This has been implemented and put as a dev version. You can find it [here](http://www.colorado.edu/physics/phet/dev/html/gravity-force-lab/2.0.0-dev.1/gravity-force-lab_en.html)

Assigning to @ariel-phet  for feedback

**Comment by ariel-phet** [comment]
@aadish this feature is generally working as expected. Two issues:

1. The force vector arrows are not scaling properly (for one they do not seem to be affected by the separation distance, and they are not scaling linearly with the mass)

2. We probably need to adjust the range of the color change, but the behavior is correct. Perhaps you and I should just sit down and tweak this range in person at some point

Please address the issue (1) first. I would say make the maximum value go just off screen, and ideally the value with a mass of 10 kg for each mass and around 1 m separation for the force arrow to barely be visible. If the arrows nearly disappear when the mass is 1 kg that is fine.

**Comment by aadish** [comment]
@samreid Fixing this issue required adding the button listener to the periodic table cell. The piece of code change also has the tandem emitters. 
Here is the code change https://github.com/phetsims/shred/commit/a1fe879177bb988efa0ac3f4e3bd4e0e04538f6f

Can you review it to see the change has no effect on tandem emitters

**Comment by aadish** [comment]
@ariel-phet have made changes so that force vector scales properly. Can you pull and check if this looks good

**Comment by ariel-phet** [comment]
@aadish yes, I can take a look. In future, any time you need something from me, please assign the issue to me, thanks!

**Comment by ariel-phet** [comment]
self assigning

**Comment by ariel-phet** [comment]
@aadish two change requests:

1. The vectors are scaling properly now, but lets make a change so that when both masses are 1000 kg and at the default separation (~4 m) the vectors just hit the dev bounds. If they are brought closer, the vectors will go off the screen. This will mean that for small masses the vectors are very small or nearly invisible, but that is OK.

2. For the constant radius mode, please have the gradient go to a much lighter color, so that when the mass is 1 kg, the sphere looks pretty "airy"

**Comment by ariel-phet** [comment]
Just a note, this scaling will match the java version more closely. Although those masses only go up to 100 kg, the dynamic range is about the same (from .1 kg to 100 kg).

**Comment by ariel-phet** [comment]
This all looks great! Closing
