### ISSUE TITLE
Random Lines Appear on iPad 2 iOS 8.4

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/gravity-force-lab#40]
Test device: iPad 2, Lave

Operating System: iOS 8.4.1

Browser: Safari 600.1.4

Problem description: When the ruler is moved around thin black lines will appear randomly around the screen. Typically only 2-3 so they don't interfere with the sim.

Steps to reproduce: Move ruler around screen.

Severity: Minor

Screenshots: 
![image](https://cloud.githubusercontent.com/assets/12610678/12239575/a473b4d4-b846-11e5-9697-5c44c9cb9812.jpg)

Troubleshooting information (do not edit):
Name: ‪Gravity Force Lab‬
URL: http://www.colorado.edu/physics/phet/dev/html/gravity-force-lab/1.2.0-rc.1/gravity-force-lab_en.html
Version: 1.2.0-rc.1 2016-01-08 20:53:50 UTC
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 8_4_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H321 Safari/600.1.4
Language: en-us
Window: 1024x648
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX543-115.5)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"HEAD"},"axon":{"sha":"5a39ec57","branch":"HEAD"},"babel":{"sha":"ddb09d1b","branch":"master"},"brand":{"sha":"c9282935","branch":"HEAD"},"chipper":{"sha":"4e863d13","branch":"HEAD"},"dot":{"sha":"7a28b1a9","branch":"HEAD"},"gravity-force-lab":{"sha":"c8ad3e0a","branch":"HEAD"},"joist":{"sha":"aa84f2d5","branch":"HEAD"},"kite":{"sha":"4a947119","branch":"HEAD"},"phet-core":{"sha":"73a034c6","branch":"HEAD"},"phetcommon":{"sha":"d712ace0","branch":"HEAD"},"scenery":{"sha":"ace9a1cc","branch":"HEAD"},"scenery-phet":{"sha":"6898cf73","branch":"HEAD"},"sherpa":{"sha":"f6999215","branch":"HEAD"},"sun":{"sha":"5a01f87b","branch":"HEAD"},"tandem":{"sha":"873e0387","branch":"HEAD"}}

**Comment by elisemorgan** [comment]
It does not appear on iOS 9.

**Comment by jbphet** [comment]
@ariel-phet - we can pursue this issue by checking in with @jonathanolson on it, and I know we've done things to tackle problems like this in the past (e.g. added an extended invisible edge).  I thought I'd ask you first whether we should make the effort on an iOS8 issue.  Note that the ruler is a common code element.

**Comment by ariel-phet** [comment]
@jbphet not worth fixing, since it is an iOS 8 bug (current app store numbers are 77% users are on iOS9). Going to leave open, but tagging as won't fix. We can close once the sim is redeployed, but will be good to leave open and report as a known issue when we do the RC.

**Comment by ariel-phet** [comment]
Assigning to @aadish to include a note when we do the RC testing.

**Comment by jessegreenberg** [comment]
@ariel-phet @aadish can this issue be closed now?

**Comment by ariel-phet** [comment]
@jessegreenberg yes. Closing
