### ISSUE TITLE
Text Issues on iOS 9 HTML download

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/gravity-force-lab#41]
Test device: iPad 2, Tycho

Operating System: iOS 9.2 (13C75)

Browser: Safari 601.1

Problem description: The force text initially appears to be squished. Once the masses are moved, the text becomes repetitive. See screenshots. 

Steps to reproduce: Save sin to home screen. Open sim from home screen. 

Severity: 

Screenshots:
After moving masses:
![image](https://cloud.githubusercontent.com/assets/12610678/12240083/f4cb10c4-b848-11e5-918a-641c45b27926.png)
Upon opening:
![image](https://cloud.githubusercontent.com/assets/12610678/12240084/f4f08d2c-b848-11e5-9f05-1d4dace24a18.png)

Troubleshooting information (do not edit):
Name: ‪Gravity Force Lab‬
URL: http://www.colorado.edu/physics/phet/dev/html/gravity-force-lab/1.2.0-rc.1/gravity-force-lab_en.html
Version: 1.2.0-rc.1 2016-01-08 20:53:50 UTC
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 9_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13C75
Language: en-us
Window: 1024x748
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX543-124.1)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"HEAD"},"axon":{"sha":"5a39ec57","branch":"HEAD"},"babel":{"sha":"ddb09d1b","branch":"master"},"brand":{"sha":"c9282935","branch":"HEAD"},"chipper":{"sha":"4e863d13","branch":"HEAD"},"dot":{"sha":"7a28b1a9","branch":"HEAD"},"gravity-force-lab":{"sha":"c8ad3e0a","branch":"HEAD"},"joist":{"sha":"aa84f2d5","branch":"HEAD"},"kite":{"sha":"4a947119","branch":"HEAD"},"phet-core":{"sha":"73a034c6","branch":"HEAD"},"phetcommon":{"sha":"d712ace0","branch":"HEAD"},"scenery":{"sha":"ace9a1cc","branch":"HEAD"},"scenery-phet":{"sha":"6898cf73","branch":"HEAD"},"sherpa":{"sha":"f6999215","branch":"HEAD"},"sun":{"sha":"5a01f87b","branch":"HEAD"},"tandem":{"sha":"873e0387","branch":"HEAD"}}

**Comment by jbphet** [comment]
Assigned to @aadish to investigate, he will assign to @jonathanolson if nothing obvious can be found.

**Comment by aadish** [comment]
fixed closing

**Comment by elisemorgan** [comment]
This issue is still present on Tycho @aadish

**Comment by aadish** [comment]
@jonathanolson Can you take a look at this and see why this would happen. 

This does not happen when opened in Safari Browser but if we save it on the Home Screen and then open from the home screen the text becomes as shown in the screen shot. Tested on iOS 9.2 and 9.3

**Comment by aadish** [comment]
in place of util.toFixed java script toFixed was used and correcting that seems to resolve this issue but would have to test with the next build

**Comment by ariel-phet** [comment]
Tried on iPad2 iOS 9.2.1, problem is fixed.
