### ISSUE TITLE
iPad left and right bounds

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-force-lab#43]
@jbphet the bounds on an iPad seem to be too far, a user can drag the masses all the way to the edge of the screen. This doesn't break the sim (at least not as far as I can tell, yet), but it's sort of a nuisance to drag the masses back towards the center. Note, this is regardless of landscape or portrait view.

![img_0088](https://cloud.githubusercontent.com/assets/5863899/12240766/88b74b88-b84c-11e5-9b83-d2532ee04a73.PNG)

Comparison with Win 8.1:

![win distance compare](https://cloud.githubusercontent.com/assets/5863899/12240825/d626607a-b84c-11e5-831e-d57c6808dd72.PNG)

**Comment by elisemorgan** [comment]
Also seen on IE11and Firefox in iFrame

**Comment by elisemorgan** [comment]
Also present on Chromebook but only in *fullscreen*

**Comment by BryceAG** [comment]
Also present on Edge in iFrame, but not while full screen (and masses are still 1).

**Comment by aadish** [comment]
fixed closing

**Comment by elisemorgan** [comment]
The figures no longer go out of the screen bounds, but the text still does. This still differs from the Win 8 screenshot above, where the text is contained in the bounds

**Comment by elisemorgan** [comment]
![image](https://cloud.githubusercontent.com/assets/12610678/13153070/64154478-d62f-11e5-9f94-6c33f04d8f3a.png)

**Comment by aadish** [comment]
me and @jbphet discussed this and decided that images should be in the bounds and text can go out of bounds and that will be fine.

@ariel-phet what do you think about it?

**Comment by ariel-phet** [comment]
@aadish I think in this case it is fine for the text to go our of bounds. Usually in such an instance, I would ask for a change, but since the forces are symmetric in value, you can still tell what the value of the force would be in this case (even though slightly cut off on the right).

Fine to leave as is, closing.
