### ISSUE TITLE
Resetting when masses are touching

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/gravity-force-lab#45]
Test device: Dirac

Operating System: 10.11.12

Browser: Firefox, Safari, Chrome

Problem description: When the two masses are dragged as close to each other as possible, if the blue mass is to the left of where it starts out, and you click reset, the blue mass will stay where it is rather than going back to its initial position. If the masses are changed before doing this, the size of the masses will change as normal but M1 will still stay where it is.

Steps to reproduce: Drag M1, the blue mass, to the left, then drag M2 into it, and click reset. 

Severity:

Screenshots:
![screen shot 2016-01-13 at 12 31 23 pm](https://cloud.githubusercontent.com/assets/11947677/12305364/a35065f0-b9f1-11e5-9773-0246479b1db8.png)
Then reset
![screen shot 2016-01-13 at 12 32 26 pm](https://cloud.githubusercontent.com/assets/11947677/12305383/c1b83108-b9f1-11e5-8d66-dc35111e9f9e.png)
(This does not have to be on the very edge, just anywhere to the left of its initial position. It's just easiest to see this way.)

Troubleshooting information (do not edit):
Name: ‪Gravity Force Lab‬
URL: http://www.colorado.edu/physics/phet/dev/html/gravity-force-lab/1.2.0-rc.1/gravity-force-lab_en.html?dev
Version: 1.2.0-rc.1 2016-01-08 20:53:50 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:43.0) Gecko/20100101 Firefox/43.0
Language: en-US
Window: 1207x585
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 16 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"HEAD"},"axon":{"sha":"5a39ec57","branch":"HEAD"},"babel":{"sha":"ddb09d1b","branch":"master"},"brand":{"sha":"c9282935","branch":"HEAD"},"chipper":{"sha":"4e863d13","branch":"HEAD"},"dot":{"sha":"7a28b1a9","branch":"HEAD"},"gravity-force-lab":{"sha":"c8ad3e0a","branch":"HEAD"},"joist":{"sha":"aa84f2d5","branch":"HEAD"},"kite":{"sha":"4a947119","branch":"HEAD"},"phet-core":{"sha":"73a034c6","branch":"HEAD"},"phetcommon":{"sha":"d712ace0","branch":"HEAD"},"scenery":{"sha":"ace9a1cc","branch":"HEAD"},"scenery-phet":{"sha":"6898cf73","branch":"HEAD"},"sherpa":{"sha":"f6999215","branch":"HEAD"},"sun":{"sha":"5a01f87b","branch":"HEAD"},"tandem":{"sha":"873e0387","branch":"HEAD"}}

**Comment by aadish** [comment]
fixed closing
