### ISSUE TITLE
Current implementation does not keep a constant density assumption

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/gravity-force-lab#47]
The current published version of the sim has several issues.

Currently, the sim does not assume a constant density. You will notice that the lowest value on the slider is 1 kg, whereas the lowest value on the slider for the java implementation is 0.01 kg. This causes multiple issues, 

From @samreid 
>The original Scala implementation for computing the radius for a given mass is:
>
>//scala
>def massToRadiusFn(m: Double) = pow(m, 1 / 3.0) / 10.0 * 4.0
>
>the JS implementation is
>//javascript
>var massToScale = new LinearFunction( options.model.massRange.min, >options.model.massRange.max, 0.05, 0.95, true );

In addition, in both the original simulation and in the current implementation the density is unrealistically low. At the largest size, the Java and HTML5 have equivalent densities of ~ 3kg/m^3 (this is only about 3 times the density of *air*!)

@jbphet and I agreed that a density more along the lines of 150 kg/m^3 would have reasonable size spherical masses at 10 kg and 1000 kg, with enough dynamic range on the slider. 150 kg/m^3 is approximately the density of balsa wood which seems a much better real world connection.

**Comment by ariel-phet** [comment]
@aadish please try implementing a slider with max value 1000 kg, minimum value 1kg and using a constant density of around 150 kg/m^3 for scaling the radius. When you have made this change please publish a dev version so I can take a look and see how it feels.

**Comment by ariel-phet** [comment]
@arouinfar as another physics expert in the group please see the comments above and let me know if you agree or have further thoughts!

**Comment by ariel-phet** [comment]
For reference in current 1.1.0 version published on the web

- At 1 kg, radius ~ 0.1 m, volume of ~ 0.0042 m^3, implies density ~ 240 kg/m^3
- At 100 kg, radius ~ 1.9 m, volume of ~ 28.7 m^3, implies density ~ 3.5 kg/m^3

**Comment by arouinfar** [comment]
@ariel-phet thanks for including me in this issue. Changing the density to 150 kg/m^3 seems reasonable to me. 

For comparison, here are the radii at the new specs
* At 10 kg, density of 150 kg/m^3, volume of 0.067 m^3, implies radius ~ 0.25 m
* At 1000 kg, density of 150 kg/m^3, volume of 6.67 m^3, implies radius ~ 1.2 m

Here's what the new max/min sizes would look like.
![image](https://cloud.githubusercontent.com/assets/8419308/12562209/42047cea-c361-11e5-88e8-91e636bb5359.png)

For comparison, here are the max/min sizes in 1.1.0
![image](https://cloud.githubusercontent.com/assets/8419308/12562224/58ed8e88-c361-11e5-8bd8-cbe7788ce145.png)

It seems like we'd lose a bit in terms of radius, but with the updated values there's still enough range to test a factor of four difference in the radius.

**Comment by arouinfar** [comment]
I just realized I calculated for 10 kg minimum instead of 1 kg... I'll update the calculations and screenshots above in a minute.

**Comment by aadish** [comment]
This has been implemented and put as a dev version. You can find it [here](http://www.colorado.edu/physics/phet/dev/html/gravity-force-lab/2.0.0-dev.1/gravity-force-lab_en.html)

Assigning to @ariel-phet for feedback

**Comment by ariel-phet** [comment]
@aadish, this feature is now working as expected. One improvement:

Please set the default starting state of the sim to Mass 1 = 50 kg and Mass 2 = 200 kg

**Comment by aadish** [comment]
Referencing the commit 1521ce5d398a30055d92562c6870f890c4333a32 for the default values of masses

**Comment by aadish** [comment]
setting the new default masses, closing it
