### ISSUE TITLE
Click-boxes extend beyond smaller mass sizes

### ISSUE THREAD

**Issue by BryceAG** [phetsims/gravity-force-lab#51]
Test device: 
Schrodinger, Bates, Galileo

Operating System:
Windows 7, 8.1, and 10

Browser:
Chrome

Problem description:
The click-boxes can extend beyond the size of the mass. They start being bigger when the mass is 30 kg and below, and constant radius is turned off. If the masses are as close together as possible, the click-box can partially overlap the other mass object below 10 kg. This is more apparent with both masses being 1 kg. Although this applies to both masses, the right mass takes priority and can render parts of the left mass unclickable.

Steps to reproduce:
With constant radius off, adjust the masses to the sizes previously mentioned. To get overlap, move the masses as close as possible to each other first.

Severity:

Screenshots:
![image](https://cloud.githubusercontent.com/assets/15327201/13186461/9a39ccfc-d703-11e5-96c0-c7bc275f6717.png)
If I click where the red spot is I will be able to move the right mass instead of the left (m2 is set to 1 kg and m1 is set to 1000 kg)

Troubleshooting information (do not edit):
Name: ‪Gravity Force Lab‬
URL: http://www.colorado.edu/physics/phet/dev/html/gravity-force-lab/2.0.0-dev.2/gravity-force-lab_en.html?showPointerAreas
Version: 2.0.0-dev.2 2016-02-17 19:48:51 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36
Language: en-US
Window: 1920x971
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"60213ff7","branch":"master"},"babel":{"sha":"8afd6088","branch":"master"},"brand":{"sha":"ac9ccaa7","branch":"master"},"chipper":{"sha":"9375d494","branch":"master"},"dot":{"sha":"da78031b","branch":"master"},"gravity-force-lab":{"sha":"5c94e94b","branch":"master"},"joist":{"sha":"10671cfc","branch":"master"},"kite":{"sha":"10ca8bf2","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"140ddaeb","branch":"master"},"scenery":{"sha":"9332b6e7","branch":"master"},"scenery-phet":{"sha":"e217d38e","branch":"master"},"sherpa":{"sha":"bb68bbbc","branch":"master"},"sun":{"sha":"60350ec5","branch":"master"},"tandem":{"sha":"2441eec6","branch":"master"}}

related to phetsims/tasks#517

**Comment by brroberts1231** [comment]
Related to #42

**Comment by aadish** [comment]
fixed, closing
