### ISSUE TITLE
Pixel polishing session with AP

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/gravity-force-lab#52]
@aadish when you feel the code is in a stable state and *before* @jbphet performs his formal code review, you and I should sit down in person and do some final "pixel polishing"

Please assign this issue back to me when you feel the sim is in a good state for you and I making a few layout/design tweaks (colors, positions, and sizes of a few elements).

**Comment by aadish** [comment]
@ariel-phet the sim is in good state and we can both together do some changes. Let me know when will it be good time to meet you. I can't do it tomorrow every other day will be fine to meet and do it.

**Comment by ariel-phet** [comment]
@aadish are you available on Friday? If so, could you please send me an email with a time that would work I should be free after about 12:30 pm on Friday

**Comment by aadish** [comment]
@ariel-phet the thumb colors of the sliders have been changed to the ones of mass objects, have a look at it

**Comment by ariel-phet** [comment]
@aadish all looks excellent! Closing
