### ISSUE TITLE
ControlShowValues should extend panel

### ISSUE THREAD

**Issue by jbphet** [phetsims/gravity-force-lab#64]
ControlShowValues currently extends Node, and adds a Panel to itself, and manually passes through a collection of options.  It would simplify the scene graph if this were made to extend Panel, and the options were sent through using the ```mutate``` call.

**Comment by aadish** [comment]
@jbphet ControlShowValues currently extends panel only, could not understand this commit

**Comment by jbphet** [comment]
My bad - I thought I saw the same pattern here that I'd seen in some other code, but this one was indeed just an extension of Panel.  Closing.
