### ISSUE TITLE
Panel Capitalization is inconsistent

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-force-lab#67]
@ariel-phet the "R" in radius is capitalized, but the "v" in values is lower case. May you make a decision on which to do so both are the same? I have no preference. For phetsims/tasks/issues/543.

![gflcap](https://cloud.githubusercontent.com/assets/5863899/13794643/96c1c0f2-eac2-11e5-9ec8-af3139d33334.PNG)

**Comment by ariel-phet** [comment]
Good catch @phet-steele 

@aadish this should be "Show Values"

**Comment by aadish** [comment]
fixed closing

**Comment by ariel-phet** [comment]
fixed, closing
