### ISSUE TITLE
Mass Gradient

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-force-lab#68]
@ariel-phet  @aadish can we move the gradient on the masses to the upper left instead of upper right in order to match the reset all button? It is more a less a standard to have our light source coming from the top left. For phetsims/tasks/issues/543.

**Comment by ariel-phet** [comment]
@aadish @phet-steele is correct, that is the standard lighting direction

**Comment by ariel-phet** [comment]
Gradient looks correct now, closing
