### ISSUE TITLE
Mass gradient doesn't update as mass resizes

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-force-lab#69]
The gradient does not update until "Constant Radius" is checked then unchecked. The gradient will then resize to match the radius of the red and blue masses, but will then continue to not be updated.

1. Mess with the mass of the masses just to see that the gradient isn't changing, then set both masses to 1 kg
2. Check "Constant Radius"
3. Uncheck "Constant Radius"
4. Increase the masses of both to 1000 kg and notice the gradients stayed small and in the middle.
5. Repeat steps 2 & 3.
6. The gradients will then update to the correct size and location.

gif through step 4:
![gfl01](https://cloud.githubusercontent.com/assets/5863899/13829541/2289b6b0-eb8d-11e5-8f5f-9fdbf3b9de60.gif)

What the gradient should look like at 1000 kg:
![gflgradient](https://cloud.githubusercontent.com/assets/5863899/13829507/fd86347e-eb8c-11e5-8149-7c79b1b0ee2f.PNG)

Seen on all Win 10 browsers. For phetsims/tasks/issues/543.

Troubleshooting information:
Name: ‪Gravity Force Lab‬
URL: http://www.colorado.edu/physics/phet/dev/html/gravity-force-lab/2.0.0-rc.1/gravity-force-lab_en.html
Version: 2.0.0-rc.1 2016-03-11 19:52:00 UTC
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
Language: en-US
Window: 1600x775
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"9457f36a","branch":"HEAD"},"babel":{"sha":"12d292eb","branch":"master"},"brand":{"sha":"ac9ccaa7","branch":"HEAD"},"chipper":{"sha":"b3a8a3c2","branch":"HEAD"},"dot":{"sha":"da78031b","branch":"HEAD"},"gravity-force-lab":{"sha":"5e52dba7","branch":"HEAD"},"joist":{"sha":"28f51008","branch":"HEAD"},"kite":{"sha":"10ca8bf2","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"380b1fb5","branch":"HEAD"},"scenery":{"sha":"b34b4fea","branch":"HEAD"},"scenery-phet":{"sha":"71a9c763","branch":"HEAD"},"sherpa":{"sha":"bb68bbbc","branch":"HEAD"},"sun":{"sha":"2b83e994","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"}}

**Comment by ariel-phet** [comment]
fixed in 2.0.0-rc.2
