### ISSUE TITLE
Labels on slider appear clickable

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-force-lab#70]
@aadish both the "1" and "1000" labels on the mass sliders appear to be clickable due to my cursor changing to a hand. Clicking or dragging them does nothing though. What's up with these labels? Can they be changed to not have a changing cursor on mouse over? For phetsims/tasks/issues/543.

![gfllabel](https://cloud.githubusercontent.com/assets/5863899/13830447/5143a114-eb92-11e5-9d4b-0a976a9c50d4.PNG)

**Comment by jbphet** [comment]
This should be fixed.  I just checked the behavior on the currently published version, and the cursor does not change when hovering over these labels.

**Comment by ariel-phet** [comment]
Resolved, closing
