### ISSUE TITLE
User suggestion: improve usability for younger students

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/gravity-force-lab#72]
Hello,

I am a middle school science teacher and I absolutely love your online simulations, and my students do too! With the new science standards, NGSS, one of the standards relates to how gravity force is impacted by changes in distance and mass. Your online simulation is the best way I have found to communicate this idea to my students. The problem that I encounter is that the simulation is not as user friendly for middle school students as it could be. I understand that the decimal numbers for force are a reflection of actual force values, and this is why they are incredibly small. However, it is difficult for middle schoolers to understand these kinds of decimals because they've never seen them or needed them. They have a difficult time understanding the changes in these numbers, ie telling if the force strength is going up or down. Also, the simulation is so accurate, that even being the tiniest sliver off, will drastically change the numbers. Unfortunately, this confuses students because their answers are very different than those of their partner even though their simulation set ups appear to be the same.

I don't know how complicated it would be to make these changes and adapt the simulation to make a simpler version for middle schoolers, but I thought I would make the suggestion because I love your online simulations and I know they are created to ensure schools make science as hands on as possible.

I appreciate your consideration and all that you do for making science interactive!
Thank you

**Comment by pixelzoom** [comment]
6/30/16: @ariel-phet will talk with @kathy-phet about creating "Gravity Force Lab: Basics".

**Comment by ariel-phet** [comment]
@kathy-phet said this seemed reasonable...we should run through the numbers and see what might work.

**Comment by ariel-phet** [comment]
@arouinfar you and I should discuss sometime. I have a few simple thoughts. Might be good to have a mockup for when Aadish returns. I am guessing this would be quite quick to turn around.

**Comment by arouinfar** [comment]
@ariel-phet sounds good. I play around with GFL abut and see if I have any ideas to address the teacher's concerns in Basics. Mockups should be straightforward. 

Do you have time to chat after design meeting tomorrow or perhaps sometime Friday?

**Comment by ariel-phet** [comment]
After design meeting should work...my basic idea was to change the mass sliders to pickers (so we could do millions of kg or such), and make the numbers easier to work with. then perhaps have a distance slider to vary the distance. But yes, lets talk.

**Comment by ariel-phet** [comment]
@kathy-phet suggested using "snap to" sliders. @arouinfar is going to make a mock up, assigning to her for the moment

**Comment by arouinfar** [comment]
When developer bandwidth permits, we will be creating a Gravity Force Lab: Basics simulation. The sim has a preliminary design, which addresses the teacher's concerns. The design doc can be found here: https://docs.google.com/document/d/1JTGePaScn9PkWIdTXFAuBc_RaEJQ6Jg7Q2murRIBbSE/edit#

Closing.
