### ISSUE TITLE
Force strings extend off-screen

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-force-lab#73]
At maximum separation, the strings describing the force run off-screen if Values is on. Currently, the text is always centered over the mass.

<img width="1094" alt="screen shot 2016-08-22 at 11 13 38 am" src="https://cloud.githubusercontent.com/assets/8419308/17864049/8b90ca1a-6859-11e6-9805-b937052f5a82.png">
<img width="1093" alt="screen shot 2016-08-22 at 11 12 15 am" src="https://cloud.githubusercontent.com/assets/8419308/17863988/55b418c0-6859-11e6-9f69-8dbace4aacee.png">
<br>
To prevent this issue, the text could pushed inward once it reaches the edge of the window.
<img width="729" alt="screen shot 2016-08-22 at 11 20 42 am" src="https://cloud.githubusercontent.com/assets/8419308/17864253/8843d07c-685a-11e6-9e11-34d7904a4367.png">

The approach could be general, and allow strings like these to stay centered over the masses, because the full string is visible within the window (though it escapes dev).
<img width="1208" alt="screen shot 2016-08-22 at 11 22 28 am" src="https://cloud.githubusercontent.com/assets/8419308/17864297/c0e186a4-685a-11e6-8bb6-74a6be1912ed.png">

I think this may merit a maintenance release, but @ariel-phet should make that call.

**Comment by phet-steele** [comment]
A comment from @ariel-phet https://github.com/phetsims/gravity-force-lab/issues/43#issuecomment-187261724 to serve as a memory refresher 😄 :

> I think in this case it is fine for the text to go our of bounds. Usually in such an instance, I would ask for a change, but since the forces are symmetric in value, you can still tell what the value of the force would be in this case (even though slightly cut off on the right).

>Fine to leave as is, closing.

**Comment by arouinfar** [comment]
Thanks for finding this @phet-steele.

> since the forces are symmetric in value, you can still tell what the value of the force would be in this case (even though slightly cut off on the right)

I would argue that noticing the values are the same is one of the learning goals. It's possible that the students may notice this before the values go off-screen, but I don't know if I would count on it.

For Gravity Force Lab: Basics, I think we would definitely want to make this change given the target audience is younger. Perhaps we can sit on this until it's addressed in GLF:B, and then migrate the change to GFL.

**Comment by ariel-phet** [comment]
@arouinfar if we make the change for GFL:B we will want it to also be present in GFL

A big chunk of the work of making GFL:B will be setting up the repos so GFL:B borrows almost all of its code from GFL, so the more consistency between the two the better (much like the relationship between something like SOM and atomic interactions)

Pushing the text inwards once it reaches the bounds sounds good. Will assign back to you and @aadish to discuss.

**Comment by arouinfar** [comment]
@aadish has been working on this behavior, and gave me a preview yesterday. 

In the demo, the string stopped moving outward once it hit the dev boundary, even at wider aspect ratios where the text would still be on-screen, but out-of-dev. While this slightly different than what I had first described, I think it looks great. No need to make further changes @aadish.

**Comment by aadish** [comment]
the dev enhancement has been made and will be published in future release

**Comment by phet-steele** [comment]
Good to go in http://www.colorado.edu/physics/phet/dev/html/gravity-force-lab/2.1.0-rc.1/gravity-force-lab_en.html?dev 👍

**Comment by phet-steele** [comment]
I take that back. There are *very* brief moments where text goes off screen:

1. Make both masses = 1 kg
2. Slide m2 all the way right
3. Slide m1 all the way right so the masses are as close to each other as possible
4. Increment m2's mass by ONE with the right tweaker. The text for m1 will go off screen.
5. Increment again and the text will fix itself, but increment a third time and it breaks....repeat until 10 kg.

![screen shot 2017-02-06 at 4 08 13 pm](https://cloud.githubusercontent.com/assets/5863899/22670467/86d20d3e-ec86-11e6-8878-63fd1e5c12e5.png)

Or
1. Make both masses = 1 kg
2. Slide m1 all the way left
3. Slide m2 all the way left
4. Increment m1's mass by ONE with the right tweaker. The text for m1 will go off screen.
5. I don't think you can then repeat.

![screen shot 2017-02-06 at 4 10 25 pm](https://cloud.githubusercontent.com/assets/5863899/22670524/cd6ac8d0-ec86-11e6-96e3-87ebe59e591b.png)

**Comment by BryceAG** [comment]
Additionally if you set both to one kg and slide to the left, and increment m2 up by 1 then back down by 1, m2 will be off screen until dragged, or do the same with m1 and both dragged to the right.

Just in general if the mass is 2 and at the boundary, when scaled down to one the text goes out of bounds.

**Comment by jessegreenberg** [comment]
> Increment m3 by ONE

:0

**Comment by jessegreenberg** [comment]
Thanks @aadish, with https://github.com/phetsims/gravity-force-lab/commit/e93ac13cbbee5d614759a9d0a66c7633a01ee527 I cannot reproduce the issue.

**Comment by phet-steele** [comment]
> Increment m3 by ONE
> :0

You've never seen that slider?

**Comment by jessegreenberg** [comment]
Thanks @phet-steele I see it now.

**Comment by phet-steele** [comment]
@aadish @jessegreenberg the force string for mass 2 now, unnecessarily, starts to the right of the mass on sim startup (instead of centered over it). Dragging m(3-1) very lowly to the left will further detach the mass from its string.

![gfl01](https://cloud.githubusercontent.com/assets/5863899/22985860/fe80a6d8-f366-11e6-9fa8-5dcb3a823de9.gif)

**Comment by phet-steele** [comment]
> Dragging m(3-1) very lowly to the left will further detach the mass from its string.

This process is true of both masses in any scenario. Slow drags in general do not move the force string along with the mass.

**Comment by phet-steele** [comment]
@jessegreenberg oh, this is probably because of you commits in #85 that limit drag precision?

**Comment by phet-steele** [comment]
> this is probably because of you commits in #85 that limit drag precision?

@jessegreenberg said, "Probably not."

**Comment by aadish** [comment]
@phet-steele @jessegreenberg  my bad didn't commit a piece of code  

 b13cbbd commit should hopefully fix this

**Comment by jessegreenberg** [comment]
Thanks @aadish!

**Comment by jessegreenberg** [comment]
I cherry-picked https://github.com/phetsims/gravity-force-lab/commit/b13cbbd44a0f6f171577a3500c17fa78a4483380 into 2.1, it is ready to be verified.

**Comment by phet-steele** [comment]
Works, thanks @aadish and @jessegreenberg.
