### ISSUE TITLE
Remove notifyObserversStatic calls

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-force-lab#79]
During code review in #78 I noticed this commit: 98f0ea9221a85b587c2c227a4be25393578abbf4 which adds these two lines of code:

```js
      this.mass1.positionProperty.notifyObserversStatic();
      this.mass2.positionProperty.notifyObserversStatic();
```

It seems these lines of code should not be doing anything, so I wanted to ask @aadish why they were introduced and if they can be removed.

**Comment by aadish** [comment]
was using this as a hack to keep the arrow text in bounds when the force changes, fixed with better logic

closing
