### ISSUE TITLE
Pi is approximated as 22/7

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-force-lab#80]
During #78 I saw this code:

```js
    /**
     * calculates the radius based on mass of object maintaining constant density
     * calculations are made using the density formula and volume of a sphere
     * @private
     */
    calculateRadius: function( mass ) {
      return Math.pow( ( mass * 3 * 7 / DENSITY / 4 / 22 ), 1 / 3 );
    },
```

Aside from this being an awkward way to represent the density of a sphere, it appears pi is approximated as 22/7.

**Comment by samreid** [comment]
It looks like this formula was introduced in 58d8b6698ecc8ee71d84bbc594b785cd0da8316d

@aadish do you have time to look into simplifying this formula?

**Comment by samreid** [comment]
To be more specific, we should use V = (4/3) pi* R^3 and density = m/v to compute the radius of the mass.

**Comment by aadish** [comment]
@samreid thanks for pointing it out will simplify the formula

**Comment by aadish** [comment]
fixed, closing
