### ISSUE TITLE
Can MassControl be replaced by a number control?

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-force-lab#81]
Discovered during #78, I noticed that MassControl has 129 lines of code to render this:

![image](https://cloud.githubusercontent.com/assets/679486/20246324/dd50eac0-a971-11e6-9344-651c1a72678e.png)

Can we instead use some pre-existing number control?

**Comment by samreid** [comment]
Here are some pre-existing number controls from scenery-phet:

![image](https://cloud.githubusercontent.com/assets/679486/20246347/3245a066-a972-11e6-8a9c-7d649ac22221.png)

**Comment by samreid** [comment]
Using NumberControl, I have nearly matched the look of the original:

![image](https://cloud.githubusercontent.com/assets/679486/20255412/8c6769bc-a9f9-11e6-8f8a-21178cb1b29c.png)

To Do:
1. black stroke around text box
2. fix text box width
3. center text in text box
4. fix i18n

**Comment by samreid** [comment]
I noticed this in the old code.  How important is this to be a floor and not a round?

```js
valueLabel.text = StringUtils.format( pattern0Value1UnitsString, Math.floor( value ), unitsKgString );
```

**Comment by samreid** [comment]
First commit above, lint is passing, most features working.  

> 3. center text in text box

I no longer recommend to do this, after testing with right-aligned it seems to better convey the change in numbers.

To Do:
1. black stroke around text box
2. fix text box width

**Comment by samreid** [comment]
@pixelzoom said:

> [11/14/16, 2:49:33 PM] Chris Malley: I'm adding 2 options, to be passed to NumberDisplay:
> [11/14/16, 2:49:41 PM] Chris Malley: valueBackgroundStroke: 'lightGray',
>       valueBackgroundLineWidth: 1,

**Comment by samreid** [comment]
Here's the original:
![image](https://cloud.githubusercontent.com/assets/679486/20284805/06d8e3d8-aa7c-11e6-8a39-1c5b77330b34.png)

Here's how far I got by eliminating duplicated code and Reusing NumberControl:
![image](https://cloud.githubusercontent.com/assets/679486/20284820/18797706-aa7c-11e6-868b-e908ad037639.png)

@ariel-phet is this close enough?  You can test on phettest.colorado.edu to see it in action.

Should we slightly round the corners of the text box?  Anything else to change?

**Comment by ariel-phet** [comment]
@samreid 

1. Yes we should round the corners of the text box (changed directly in NumberControl)

2. The original has a bit more negative space between the text box and the tweakers, I think that is aesthetically preferable (leave defaults in NumberControl, but generalize so this case can be accomodated)

3. In the original text box the value and unit remain centered in the text box as the value grows and shrinks. I am not sure if this is necessary (it seems nice aesthetically, but I don't think it causes any usability issues or such). However, noting the difference. it seems like we might want to at least have the dynamic centering as an option in NumberControl.

**Comment by samreid** [comment]
Sounds good, thanks for the review.

> In the original text box the value and unit remain centered in the text box as the value grows and shrinks. I am not sure if this is necessary (it seems nice aesthetically, but I don't think it causes any usability issues or such). However, noting the difference. it seems like we might want to at least have the dynamic centering as an option in NumberControl.

After experimenting with both, it much easier to visually understand the orders of magnitude in the "right-aligned" one, because the "kg" marker stays in the same spot and you can see the numbers bumping to the left as they go up by orders of magnitude.  In the centered strategy (which I originally thought looked more appealing), this effect is washed out.  But I agree we should add this as an option for potential usage in other contexts.

**Comment by pixelzoom** [comment]
> 2. The original has a bit more negative space between the text box and the tweakers, I think that is aesthetically preferable (leave defaults in NumberControl, but generalize so this case can be accommodated)

Use `layoutFunction: NumberControl.createLayoutFunction1( { ySpacing: YOU_VALUE } )`

> 3. ... it seems like we might want to at least have the dynamic centering as an option in NumberControl.

Use NumberControl option `valueAlign:'center'`, added in above commit.

**Comment by samreid** [comment]
> Yes we should round the corners of the text box (changed directly in NumberControl)

@pixelzoom argued that the amount of rounding should remain application specific, since it is in pixels, and he recommended to just supply the corner radius from the sim.  Hence I'll proceed with that for now.

**Comment by samreid** [comment]
I changed the spacing from the default of 5 to 10.

Old one:
![image](https://cloud.githubusercontent.com/assets/679486/20360534/4f5580aa-abf1-11e6-99d5-377f7ebbe494.png)

New one:
![image](https://cloud.githubusercontent.com/assets/679486/20360543/57a5dfe8-abf1-11e6-8d18-080aa9c4a68d.png)

**Comment by samreid** [comment]
@ariel-phet would you like to review?

**Comment by ariel-phet** [comment]
@samreid looks good to me. However, we should also check with @arouinfar since she is the lead designer for this sim. @arouinfar this looks pretty good to me but I would have two main questions unless you see other tweaks:

1. Are you OK with the readout being fixed, (not dynamically centering as in the published version). Take a look on phettest to see the difference
2. What should the alignment relationship be between the sliders and tweakers. In @samreid new one he has aligned the tweakers to the outer edges of the tick mark labels (it seems the other obvious choice is aligning to to the edge tick marks)
3. it seems to me the tick mark labels should be a bit closer to the tick marks (that would be a slight tweak over the original).

**Comment by arouinfar** [comment]
In general, things look pretty good to me @samreid @ariel-phet.

> Are you OK with the readout being fixed, (not dynamically centering as in the published version). Take a look on phettest to see the difference

It looks fine to me, since the text at max width is centered within the readout.


> What should the alignment relationship be between the sliders and tweakers. In @samreid new one he has aligned the tweakers to the outer edges of the tick mark labels (it seems the other obvious choice is aligning to to the edge tick marks)

At first glance it looks reasonable, though when comparing the slider track the alignment seems a bit off. I have a slight preference for aligning the tweakers to the edge tick marks instead.

> it seems to me the tick mark labels should be a bit closer to the tick marks (that would be a slight tweak over the original).

Agreed. I think 1 or 2 px would do the trick.

**Comment by samreid** [comment]
In the above commit, I reduced the tickLabelSpacing from 6 to 2, it now looks like this:

![image](https://cloud.githubusercontent.com/assets/679486/20874671/51f232ca-ba71-11e6-84c9-f21440579149.png)

@arouinfar anything else to do here?  You can test in context on phettest if you wish.

**Comment by arouinfar** [comment]
Looks good to me @samreid.
