### ISSUE TITLE
User reported issue: force of gravity is not calculating correctly

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/gravity-force-lab#83]
> A 10.0 kg mass and a 12.0 kg mass separated by 4.0m should be 5.00 nN, not what I'm getting on my screen.

**Comment by ariel-phet** [comment]
@oliver-phet the sim is doing the calculation correctly. For the users parameters the answer should be 0.50 nN (not 5.00 nN). 

Perhaps have the user send a screenshot, and then forward the email to me and I can respond.

**Comment by oliver-phet** [comment]
I'll have the user send a screenshot, but I tried to set up this situation, it did seem the distance was off?
<img width="896" alt="screen shot 2017-01-13 at 12 16 58 pm" src="https://cloud.githubusercontent.com/assets/5090275/21942424/4a236702-d98a-11e6-8f9d-176a66e31187.png">

**Comment by oliver-phet** [comment]
Here's the image by the user:
![image](https://cloud.githubusercontent.com/assets/5090275/21948966/ce4e6830-d9ab-11e6-9f9a-947d5a2942c4.png)

**Comment by ariel-phet** [comment]
@oliver-phet yes, it looks like there might be some slight discrepancy between the actual distance in the sim, and the scaling of the ruler. 

@jessegreenberg can you let me know what the default separation distance is when you first load the sim? I assume it is meant to be a round number like 4 m? If so we may need to adjust the scaling of the ruler a bit.

**Comment by ariel-phet** [comment]
@oliver-phet please email the user back and let them know there might be a minor scaling issue in the sim that we will look into and fix promptly, and thank them for pointing it out.

**Comment by jessegreenberg** [comment]
![capture](https://cloud.githubusercontent.com/assets/6396244/21949906/3324935e-d9b3-11e6-8a1a-cfecae6f44f8.PNG)

That is correct, 4m on sim load.

**Comment by jessegreenberg** [comment]
The scaling looks a bit better for me:
![capture](https://cloud.githubusercontent.com/assets/6396244/21950059/6c1db3ec-d9b4-11e6-90fb-c64f699dce78.PNG)

**Comment by jessegreenberg** [comment]
@oliver-phet could you please provide platform details?

**Comment by jessegreenberg** [comment]
Could not reproduce on a MacBook pro, Windows 10, or Chromebook, but I was able to see the bug on Windows 7 (Bates) for Chrome, Firefox, and IE.

**Comment by jessegreenberg** [comment]
This is a model issue, not a scaling issue.  If you modify the masses with the sliders, you will likely see incorrect forces like https://github.com/phetsims/gravity-force-lab/issues/83#issuecomment-272574145.  If you modify it with the tweakers, the values are correct.

By modifying the sliders, I was able to see the bug in Windows 10 Chrome.

**Comment by jessegreenberg** [comment]
By changing the mass with the sliders I can consistently reproduce this issue.

**Comment by jessegreenberg** [comment]
When the slider is used, the mass values aren't rounded to the nearest integer, so in the screen shots above, the masses are incorrect.  Will check to see if this is happening in master, but the implementation in master is pretty different than the released version.

**Comment by jessegreenberg** [comment]
Master uses a NumberControl which constrains the value correctly.  We could redeploy off of master (requires full testing) or patch 2.0, I will see how much needs to be done to patch 2.0.

**Comment by jessegreenberg** [comment]
Should be fixed in the commit above.  This was a minor fix and a maintenance release could be deployed without any testing.

@ariel-phet it looks like #73 is also fixed and is waiting for a redeploy.  That issue required bigger changes and would require a new RC to be built off of master.  Would you like to do a maintenance release for this issue or would you like to go through QA testing to include #73 now?

**Comment by ariel-phet** [comment]
@jessegreenberg since this a relatively easy sim to test, I think it would good to do a release that includes much of the latest (#73, but also the new navbar/loading screen).

**Comment by phet-steele** [comment]
@jessegreenberg @ariel-phet I did quite a bit a math under different scenarios. Looks accurate.

**Comment by phet-steele** [comment]
Reopening for @oliver-phet to send an email when the rc is released.

**Comment by jessegreenberg** [comment]
@oliver-phet 2.1.0 has been deployed to the website and should fix this issue:
https://phet.colorado.edu/sims/html/gravity-force-lab/latest/gravity-force-lab_en.html

**Comment by oliver-phet** [comment]
User emailed. Closing.
