### ISSUE TITLE
User suggestion: Coulomb's Law sim

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/gravity-force-lab#84]
> It seems to me that you could easily create a Coulomb's Law PhET sim by
> making a few changes to your Gravity Force Lab sim:

@ariel-phet wrote:

> I don't think we had planned on it, but the teacher is correct, we could easily make a Coulomb's law sim (gravitational and electrical attraction are more or less the same equation G*m1*m2/r^2 vs k*q1*q2/r^2 so charges instead of masses and a different constant)

**Comment by arouinfar** [comment]
@ariel-phet I think the general framework of GFL could transfer nicely to a Coulomb's Law sim. Off the top of my head, I can think of a few things we'd need to address
* Repulsive forces -- figures would need to push against the charges
* Scaling should be comfortably within the point-charge regime. (Distance between charges >> charge radius.)
* Charge diameter should be fixed and relatively small. 
* Charge should be represented using a color gradient, like the Constant Radius option in GFL. 
* We may want to consider discretizing charge like we do to the mass in GLF:B.

**Comment by ariel-phet** [comment]
@kathy-phet agreed this seems reasonable as a potential sim (perhaps for an intern...Martin...Jessy after GLF:B etc). 

@arouinfar perhaps do a rough design in the next couple weeks and you and I can talk through it to see if there are any big hurdles?

**Comment by arouinfar** [comment]
Sounds good @ariel-phet! I'll keep you posted.

**Comment by arouinfar** [comment]
Note to self: Consider integer multiples of e for charge and Å as a possible scale for distances. This would allow chem teachers to look at the force between the nucleus and a valence electron.

**Comment by jessegreenberg** [comment]
I recently created https://github.com/phetsims/coulombs-law for this.

**Comment by arouinfar** [comment]
We're moving forward with the design of the Coulomb's Law sim, so this issue seems stale. 

@oliver-phet you can let the user know that we will be working on creating the new sim (but we're still in the early stages of the design process) and then close this issue.

**Comment by oliver-phet** [comment]
Replied to user. Closing.
