### ISSUE TITLE
Inconsistent Forces at the edges of the simulation

### ISSUE THREAD

**Issue by EthanWJohnson** [phetsims/gravity-force-lab#85]
When both masses are dragged to the very edge of the playing area, it doesn't seem that dragging the mass closest to the edge should be able to change the registered force at all; it has no "space" to maneuver being sandwiched between the edge and the other mass. Yet, in several circumstances, this is not the case. 

![exhibit a](https://cloud.githubusercontent.com/assets/22551096/22671072/9b4b5a4c-ec89-11e6-94f2-eab39fcd9f9b.gif)

In constant radius mode, on the left hand side, when both masses are dragged all the way left, the blue mass (leftmost) can be dragged back and forth between the wall and the red mass--and every time it does so, the force changes. It seems that, every drag the blue mass is pushing the red mass away, giving it a range of motion that can significantly change the registered force. It's incredibly subtle as the red mass doesn't move much every time it is wiggled, so the force is changing without any visible change to the distance. 

![exhibit b](https://cloud.githubusercontent.com/assets/22551096/22671366/3fb4831e-ec8b-11e6-8b2c-208b62ac1b86.gif)

In this case (without constant radius) the force oscillates between two discreet values without any visible movement; the blue mass seems to have some minor wiggle room despite being sandwiched against the wall. This happens on the right wall as well, to a lesser extent. 

Seen on: Windows 10, MacOS

Related to: https://github.com/phetsims/tasks/issues/775

Debug Info:

Name: ‪Gravity Force Lab‬
URL: http://www.colorado.edu/physics/phet/dev/html/gravity-force-lab/2.1.0-rc.1/gravity-force-lab_en.html
Version: 2.1.0-rc.1 2017-01-30 18:04:33 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Language: en-US
Window: 1680x881
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"a707328c","branch":"HEAD"},"axon":{"sha":"1cf10281","branch":"HEAD"},"babel":{"sha":"10f77fec","branch":"master"},"brand":{"sha":"0be722ee","branch":"HEAD"},"chipper":{"sha":"f4cd39bf","branch":"HEAD"},"dot":{"sha":"75380061","branch":"HEAD"},"gravity-force-lab":{"sha":"021d9ff0","branch":"HEAD"},"joist":{"sha":"d15e6fab","branch":"HEAD"},"kite":{"sha":"6059ebb0","branch":"HEAD"},"phet-core":{"sha":"84747dff","branch":"HEAD"},"phetcommon":{"sha":"1cb33196","branch":"HEAD"},"query-string-machine":{"sha":"d8a4ff18","branch":"HEAD"},"scenery":{"sha":"550df01a","branch":"HEAD"},"scenery-phet":{"sha":"b04d8086","branch":"HEAD"},"sherpa":{"sha":"785a536c","branch":"HEAD"},"sun":{"sha":"d0708aa5","branch":"HEAD"},"tandem":{"sha":"d9c124e5","branch":"HEAD"}}

**Comment by jessegreenberg** [comment]
Thanks @EthanWJohnson, this is also an issue for the deployed version as well.

**Comment by jessegreenberg** [comment]
Should be fixed in the above commit.

**Comment by phet-steele** [comment]
Looks fixed to me! But I will let @EthanWJohnson verify.

**Comment by EthanWJohnson** [comment]
Yep, everything seems fine. When the masses have their backs against the wall, there is now no room for error. 

Closing.
