### ISSUE TITLE
User suggestion: Electric Force lab

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/gravity-force-lab#86]
> Introduction of a new app based on the Gravity Force lab called Electric Force lab. Same set up but with charged particles instead of particles with mass. I use the Gravity force lab so determine G and to introduce linearisation of graphs which students tell me they find particularly useful.

Related to https://github.com/phetsims/gravity-force-lab/issues/84?

**Comment by arouinfar** [comment]
@oliver-phet yes, this is the same request as #84. You can let the user know that we are in the process of designing a new Coulomb's Law simulation.  Our new a11y intern will be working on the development, but the design process is still in the early stages, so it'll be a while before the sim is out.

**Comment by oliver-phet** [comment]
Replied to user. Closing.
