### ISSUE TITLE
Propagate snapping distance to GFL

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-force-lab#89]
As discussed in status, now that the snapping distance feature has been added to `inverse-square-law` it would be nice to add it to the full version of GFL as well.

**Comment by jessegreenberg** [comment]
@arouinfar what should the resolution be for snapping in this sim?

**Comment by arouinfar** [comment]
@jessegreenberg let's start with the GFL:B grid and see how it looks.

**Comment by jessegreenberg** [comment]
The  masses snap in GFL now. But it looks like they don't quite snap exactly to the grid lines. Same with the ruler:
![capture](https://user-images.githubusercontent.com/6396244/40810993-c6a83228-64ec-11e8-99bf-ec52bc9ec621.PNG)

**Comment by jessegreenberg** [comment]
Actually, I am seeing this in coulombs-law and gravity-force-lab-basics. So Ill make an issue for https://github.com/phetsims/gravity-force-lab/issues/89#issuecomment-393697135 in ISLC

**Comment by jessegreenberg** [comment]
Is there anything else to do for this issue @arouinfar?

**Comment by arouinfar** [comment]
Good catch @jessegreenberg! The grid size is excellent, but it should be aligned with the sim elements.

**Comment by jessegreenberg** [comment]
Thanks @arouinfar, sounds good. We are going to look into that in  https://github.com/phetsims/inverse-square-law-common/issues/49. Closing this issue.
