### ISSUE TITLE
Use ISLRuler

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/gravity-force-lab#90]
The ISLRuler needs to be used in order to support #89.

**Comment by zepumph** [comment]
This seems to have been accomplished. @mbarlow12 could you please close or reframe what work needs to be done in this issue?

**Comment by mbarlow12** [comment]
@zepumph it looks like this is done as `GravityForceLabScreenView` uses `ISLCRulerNode` (ln 155).  Closing.
