### ISSUE TITLE
New PhET-iO version request

### ISSUE THREAD

**Issue by mikewinters10** [phetsims/gravity-force-lab#99]
The current PhET-iO version of Gravity Force Lab was published on November 29, 2016. We need an updated version for sound design purposes.

**Comment by mikewinters10** [comment]
@jbphet having trouble adding you as an assignee.

**Comment by jbphet** [comment]
@samreid and/or @zepumph - is this sim in a state where we can deploy a phet-io version for the purposes of prototyping the sound design with a sonification wrapper?

**Comment by jbphet** [comment]
@samreid responded to a Slack question on this topic just as I was creating this issue.  Here is what he said:

> I’m not sure but I’ll take a look
> It looks like @mbarlow12  has been working on this most recently, in April and May.
> I spot checked studio and it seemed to be working (though not a sparse, thoughtful instrumentation)
> @zepumph  really knows the most about the sonification + PhET-iO overlap, and deployment, but he is out today.
> Would it work to try building a version and see how it goes?
> Would it work to start building a wrapper using your local requirejs version?

In response to a couple of the questions above, I'd rather not do a build and deploy until we hear from @zepumph just to make sure I'm not wasting my time.  Also, running locally isn't really and option, since the Georgia Tech folks will be doing the bulk of the wrapper development.

**Comment by zepumph** [comment]
I ran tests and poked through studio, I think it is good enough to begin sonification design work.

https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-dev.5/phet-io/wrappers/index/

@mikewinters10 let me know if you find any shortcomings in the current implementation. As @samreid said, it is not instrumented as thoughtfully as the final publication will be.

**Comment by mikewinters10** [comment]
I may be having an issue with using the API:

```javascript
<script type="text/javascript" src="https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-dev.5/phet-io/lib/phet-io.js"></script>

<script>

  // Select the sim you want to use by giving its hyphenated name and version string
  var sim = WrapperUtils.getSim( 'gravity-force-lab', '2.2.0-dev.5' );

...

</script>
```

Gives me 'Uncaught ReferenceError: WrapperUtils is not defined.' 

I'm not really sure what the error is.  The only difference I'm seeing with the usual implementation is that the source is coming from phet-dev.colorado.edu, where it has been bayes.colorado.edu.

**Comment by samreid** [comment]
I think it is called `phet.WrapperUtils` now, please see the template at https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-dev.5/phet-io/wrappers/index/

**Comment by mikewinters10** [comment]
I got it to work! Just copied the example API code from the link that you shared, and then added some specific code from the phet-osc-bridge.

Thanks!
